// Isolated synthetic visual fixture; excluded from production.
import React from 'react';import {createRoot} from 'react-dom/client';
import Journal from '../app/journal';import '../app/globals.css';
import {localDate} from '../lib/domain';
let fixture:any={user:{id:'sample',role:'member',email:'sample@example.test',coupleId:'sample-pair',relationshipVersion:1,dataEpoch:1},couple:{emblem:'neutral'},own:[{owner:'sample',kind:'profile',key:'me',version:2,data:{name:'Participante',ideal:'',shareSchedule:false,shareNotes:false,shareIdeal:false}}],shared:[],partner:{name:'Mi pareja',ideal:'',records:[]},marriageIdeal:{text:'',version:0,confirmations:0,confirmedByMe:false},today:localDate()};
let community:any={groups:[{id:'group1',name:'Curso de prueba',motto:'Caminar juntos',ideal:'',version:1,ownerId:'sample',members:[{id:'sample',name:'Participante'},{id:'other',name:'Otro participante'}],purposes:[{id:'p1',title:'Escuchar con atención',reason:'Llevar a la vida lo que conversamos',start:localDate(),end:localDate(),target:3,unit:'person',decision:'',version:1,joined:true,share:false,logs:[{day:localDate(),amount:1,version:1}],summary:null}],meeting:{version:1,data:{date:localDate(),time:'19:00',place:'Encuentro del curso',material:'',question:'¿Qué nos ayudó esta semana?',roles:'Oración: un matrimonio del curso'},responses:[]}}],rosaries:[{id:'r1',ownerId:'sample',groupId:'group1',coupleId:null,mystery:'joyful',mode:'free',intention:'Por nuestras familias',cancelled:false,slots:[{decade:1,userId:'other',done:true},{decade:2,userId:'sample',done:false}],mine:[]}]};
async function request(init?:RequestInit){if(init?.method!=='POST')return Response.json(fixture);const p=JSON.parse(String(init.body));const record={owner:'sample',kind:p.kind,key:p.key,version:p.version+1,data:p.data};fixture.own=[...fixture.own.filter((r:any)=>r.kind!==p.kind||r.key!==p.key),record];return Response.json({record});}
async function communityTransport(p:any){if(p.action==='purpose_log'){community.groups[0].purposes[0].logs=[{day:p.day,amount:p.amount,version:p.version+1}];}if(p.action==='rosary_complete'){const r=community.rosaries.find((r:any)=>r.id===p.id);r.slots=r.slots.filter((s:any)=>s.decade!==p.decade);r.slots.push({decade:p.decade,userId:'sample',done:true});r.mine.push({decade:p.decade,day:localDate()});}return Response.json(community);}
createRoot(document.getElementById('root')!).render(<Journal dataRequest={request} communityTransport={communityTransport} onSignOut={()=>location.reload()} assetBase="./"/>);
