import {PGlite} from '@electric-sql/pglite';
import {readFile,readdir} from 'node:fs/promises';
import {createHash,randomUUID} from 'node:crypto';
import assert from 'node:assert/strict';
const db=new PGlite();
const id=n=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0');
const proof='a'.repeat(64),digest=s=>createHash('sha256').update(s).digest('hex');
const query=async(sql,args=[]) => (await db.query(sql,args)).rows[0]?.v;
try{
 await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to authenticated,anon;grant execute on function auth.uid() to authenticated,anon;`);
 const files=(await readdir('supabase/migrations')).filter(f=>f.endsWith('.sql')).sort();
 for(const f of files.filter(f=>f<'20260909143538'))await db.exec(await readFile('supabase/migrations/'+f,'utf8'));
 await db.exec(`insert into auth.users values('${id(1)}','admin@example.test',now()),('${id(2)}','legacy@example.test',null);insert into alianza_private.members values('${id(1)}','jose','A',''),('${id(2)}','neca','B','');`);
 for(const f of files.filter(f=>f>='20260909143538'))await db.exec(await readFile('supabase/migrations/'+f,'utf8'));
 await db.query('insert into alianza_private.admin_members values($1)',[id(1)]);
 const before=(await db.query('select row_to_json(m) v from alianza_private.members m where id=$1',[id(2)])).rows[0].v;
 async function as(n,role=n?'authenticated':'anon'){await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[n?id(n):'']);await db.exec('set role '+role);}
 const op=async p=>query('select public.alianza_invitation_operator($1::jsonb) v',[JSON.stringify(p)]);
 const entry=async p=>query('select public.alianza_invitation_entry($1::jsonb) v',[JSON.stringify(p)]);
 const list=()=>query('select public.alianza_invitation_list() v');
 const request=(action,email,version=0)=>({actor:id(1),action,email,version,requestId:randomUUID(),proofHash:digest(proof)});
 await as(1);assert.equal((await list()).people.length,2);await assert.rejects(()=>op(request('invite','new@example.test')),e=>e.code==='42501');
 await as(null);await assert.rejects(list,e=>e.code==='42501');
 await as(null,'service_role');await assert.rejects(()=>op({...request('invite','new@example.test'),actor:id(2)}),e=>e.code==='42501');
 let pending=request('invite',' New@example.test '),r=await op(pending);assert(r.id);assert.equal(r.email,'new@example.test');assert.equal((await op(pending)).replay,true);
 assert(!JSON.stringify(r).includes(proof));
 await assert.rejects(()=>op(request('invite','admin@example.test')),e=>e.code==='PT409');
 await assert.rejects(()=>op(request('renew','new@example.test',1)),e=>e.code==='PT429');
 await db.exec('reset role');await db.query('insert into auth.users values($1,$2,now())',[id(3),'new@example.test']);
 await as(3);await assert.rejects(()=>query('select public.alianza_data(null) v'),e=>e.code==='42501');
 assert.equal((await entry({action:'status'})).state,'pending');
 await assert.rejects(()=>entry({action:'accept',id:r.id,proof:'b'.repeat(64),metrics:false}),e=>e.code==='42501');
 assert.equal((await entry({action:'accept',id:r.id,proof,metrics:false})).state,'accepted');
 assert.equal((await entry({action:'accept',id:r.id,proof,metrics:false})).state,'accepted');
 const snapshot=await query('select public.alianza_data(null) v');assert.equal(snapshot.user.coupleId,null);
 const metric=p=>query('select public.alianza_pilot_metrics($1::jsonb) v',[JSON.stringify(p)]);
 assert.deepEqual(await metric({action:'status'}),{enabled:false,optional:true});
 await metric({action:'event',event:'open'});
 await db.exec('reset role');assert.equal((await db.query('select count(*) n from alianza_private.pilot_days where user_id=$1',[id(3)])).rows[0].n,0);
 await as(3);await metric({action:'consent',enabled:true});await metric({action:'event',event:'open'});await metric({action:'consent',enabled:false});
 await as(1);assert.equal((await metric({action:'consent',enabled:false})).enabled,true,'Legacy agreement preserved');
 await as(null,'service_role');await assert.rejects(()=>op(request('cancel','new@example.test',1)),e=>e.code==='PT409');
 pending=request('invite','legacy@example.test');r=await op(pending);
 await db.exec('reset role');await db.query('update auth.users set email_confirmed_at=now() where id=$1',[id(2)]);
 await as(2);for(const sql of ['select public.alianza_data(null)','select public.alianza_relationship(\'{"action":"snapshot"}\')','select public.alianza_community(\'{}\')','select public.alianza_pilot_metrics(\'{}\')','select public.alianza_product_metrics(\'{"action":"status"}\')'])await assert.rejects(()=>db.query(sql),e=>e.code==='42501');
 await as(null,'service_role');await op(request('cancel','legacy@example.test',1));
 await as(2);await assert.rejects(()=>entry({action:'accept',id:r.id,proof,metrics:true}),e=>e.code==='42501');
 await db.exec('reset role');await db.query("update auth.users set email='changed@example.test' where id=$1",[id(2)]);
 await as(2);await assert.rejects(()=>query('select public.alianza_data(null) v'),e=>e.code==='42501');
 await db.exec('reset role');await db.query("update auth.users set email='legacy@example.test' where id=$1",[id(2)]);
 await db.query("update alianza_private.pilot_invitations set updated_at=now()-interval '2 minutes' where email='legacy@example.test'");
 await as(null,'service_role');const newer={...request('renew','legacy@example.test',2),proofHash:digest('c'.repeat(64))};const renewed=await op(newer);assert(renewed.confirmed);
 assert.equal((await op({actor:id(1),action:'finish',requestId:pending.requestId,result:'error'})).current,false);
 assert.equal((await op({actor:id(1),action:'finish',requestId:newer.requestId,result:'requested'})).current,true);
 await as(2);await assert.rejects(()=>entry({action:'accept',id:r.id,proof,metrics:false}),e=>e.code==='42501');
 await entry({action:'accept',id:r.id,proof:'c'.repeat(64),metrics:false});
 await db.exec('reset role');assert.deepEqual((await db.query('select row_to_json(m) v from alianza_private.members m where id=$1',[id(2)])).rows[0].v,before,'Renewal preserves original identity and pair');
 await as(2);assert.equal((await metric({action:'status'})).enabled,true);await assert.rejects(list,e=>e.code==='42501');
 await as(1);assert(!(await list()).people.some(p=>'proof_hash' in p));
 await db.exec('reset role');await db.query('delete from alianza_private.admin_members where user_id=$1',[id(1)]);
 await as(null,'service_role');await assert.rejects(()=>op(request('invite','blocked@example.test')),e=>e.code==='42501');
 await as(1);await assert.rejects(list,e=>e.code==='42501');
 await assert.rejects(()=>db.query('select * from alianza_private.pilot_invitations'),e=>e.code==='42501');
 console.log('PASS invitation metadata boundary, idempotency, gates, cancel/renew, legacy preservation, individual entry and optional metrics');
}catch(e){console.error('FAIL',e.message,e.code??'',e.where??'');process.exitCode=1;}finally{await db.close();}
