import assert from 'node:assert/strict';import {dom} from './dom.mjs';
const React=await import('react');const {render,screen,fireEvent,cleanup,waitFor}=await import('@testing-library/react');const {PilotPanel}=await import('../github/pilot.tsx');const {UserEnvironment}=await import('../github/admin.tsx');const {usePilotEvent}=await import('../app/pilot-events.tsx');
const summary={asOf:'2026-09-16',consenting:4,active7:4,active30:4,totals30:{view_day:{count:7,people:4},save_error:{count:1,people:1}}};let enabled=false,fail=false;const calls=[];
const client={rpc:async(name,args)=>{calls.push({name,args});if(fail)return{error:{code:'42501'}};if(name==='alianza_admin_pilot')return{data:summary};if(name==='alianza_pilot_metrics'){if(args?.payload.action==='consent')enabled=args.payload.enabled;return{data:{enabled}};}return{data:false};}};
function Feature(){const event=usePilotEvent();return React.createElement('button',{onClick:()=>event('view_week')},'Abrir semana');}
try{
 render(React.createElement(PilotPanel,{client}));await screen.findByText('Funciones utilizadas · últimos 30 días');assert(screen.getByText('Errores al guardar').parentElement.textContent.includes('1'));assert(screen.getByText('Participan en la medición').parentElement.textContent.includes('4'));assert(!document.body.textContent.includes('@'));fail=true;fireEvent.click(screen.getByRole('button',{name:'Actualizar piloto'}));await screen.findByRole('alert');assert(!screen.queryByText('Funciones utilizadas · últimos 30 días'));cleanup();fail=false;
 render(React.createElement(UserEnvironment,{client,userId:'fixture'},React.createElement(Feature)));await screen.findByText('Participar en el piloto cercano');fireEvent.click(screen.getByRole('button',{name:'Abrir semana'}));assert(!calls.some(c=>c.args?.payload.event==='view_week'));
 fireEvent.click(screen.getByLabelText('Participar en el piloto cercano'));await waitFor(()=>assert(enabled));await waitFor(()=>assert(screen.getByLabelText('Participar en el piloto cercano').checked));fireEvent.click(screen.getByRole('button',{name:'Abrir semana'}));await waitFor(()=>assert(calls.some(c=>c.args?.payload.event==='view_week')));assert(calls.filter(c=>c.args?.payload.action==='event').every(c=>Object.keys(c.args.payload).length===2));
 fireEvent.click(screen.getByLabelText('Participar en el piloto cercano'));await waitFor(()=>assert(!screen.getByLabelText('Participar en el piloto cercano').checked));const count=calls.length;fireEvent.click(screen.getByRole('button',{name:'Abrir semana'}));assert.equal(calls.length,count);
 console.log('PASS small pilot dashboard, visible error count, stale result clearing, separate voluntary consent and fixed feature events only while enabled');
}finally{cleanup();dom.window.close();}
