// Isolated UI harness, never imported by the production build. In-memory fixtures only.
import React from 'react';import {createRoot} from 'react-dom/client';
import Journal from '../app/journal';import '../app/globals.css';
import {localDate} from '../lib/domain';
const linked=new URLSearchParams(location.search).has('linked');
let fixture:any={user:{id:'sample',role:'member',email:'sample@example.test',coupleId:linked?'sample-pair':null,relationshipVersion:1},couple:linked?{emblem:'neutral'}:null,own:[{owner:'sample',kind:'profile',key:'me',version:1,updated:'',data:{name:'Persona de prueba',ideal:'',shareSchedule:false,shareNotes:false,shareIdeal:false}}],shared:[],partner:linked?{name:'Cónyuge de prueba',ideal:'',shareSchedule:false,shareNotes:false,records:[]}:null,marriageIdeal:linked?{text:'',version:0,confirmations:0,confirmedByMe:false}:null,invitations:[],archives:[],today:localDate()};
async function request(init?:RequestInit){if(init?.method!=='POST')return Response.json(fixture);const p=JSON.parse(String(init.body));if(p.action){if(p.action==='preview')return Response.json({invitation:{name:'Persona de prueba',email:'spouse@example.test'}});if(p.action==='create')return Response.json({token:'a'.repeat(64),state:{...fixture,invitations:[{id:'example',email:p.email,expiresAt:'2026-09-19'}]}});if(p.action==='cancel')fixture.invitations=[];else if(p.action==='ideal_save')fixture.marriageIdeal={text:p.text,version:fixture.marriageIdeal.version+1,confirmations:0,confirmedByMe:false};else if(p.action==='ideal_confirm')fixture.marriageIdeal={...fixture.marriageIdeal,confirmations:1,confirmedByMe:true};else return Response.json({error:'Esta vista solo simula los formularios. Las transiciones se prueban en la suite de integración.'},{status:400});return Response.json({state:fixture});}
const field=p.kind==='rs'?'shared':'own';const record={owner:field==='shared'?'couple:sample-pair':'sample',kind:p.kind,key:p.key,version:p.version+1,updated:'',data:p.data};fixture={...fixture,[field]:[...fixture[field].filter((r:any)=>r.kind!==p.kind||r.key!==p.key),record]};return Response.json({record});}
createRoot(document.getElementById('root')!).render(<Journal dataRequest={request} onSignOut={()=>location.reload()}/>);
