import assert from 'node:assert/strict';
import {dom} from './dom.mjs';
const React=await import('react');
const {render,screen,fireEvent,waitFor,cleanup}=await import('@testing-library/react');
const {default:Journal}=await import('../app/journal.tsx');
const {ReflectionSummary}=await import('../app/reflection-summary.tsx');
const {localDate}=await import('../lib/domain.ts');
const today=localDate(),month=today.slice(0,7);
const row=(kind,key,data)=>({owner:'fixture',kind,key,data,version:1,updated:new Date().toISOString()});
const habit=(key,title,period,target,unit='days')=>[row('habit',key,{title,moment:'Mañana',active:true,frequency:{period,target,unit}}),row('habit_plan',key,{versions:[{from:month+'-01',active:true,period,target,unit}]})];
const fixture={user:{id:'fixture',role:'member',email:'fixture@example.test',relationshipVersion:1,coupleId:null},own:[row('profile','me',{name:'Persona',ideal:'',shareSchedule:false,shareNotes:false}),...habit('offer','Ofrecer mi día','day',1),...habit('rosary','Dos rosarios al mes','month',2,'times'),row('checks',today,{offer:'done'})],shared:[],partner:null,today};
const writes=[];
async function request(init){if(init?.method!=='POST')return Response.json(fixture);const p=JSON.parse(init.body);writes.push(p);const record={...row(p.kind,p.key,p.data),version:p.version+1};fixture.own=[...fixture.own.filter(r=>r.kind!==p.kind||r.key!==p.key),record];return Response.json({record});}
try{
 render(React.createElement(Journal,{dataRequest:request,onSignOut(){}}));
 await screen.findByRole('heading',{name:/^(Hoy|Mi día)$/});
 assert.equal(screen.getByRole('progressbar',{name:'Compromisos diarios'}).getAttribute('aria-valuenow'),'1');
 await screen.findByText('Dos rosarios al mes');
 assert(screen.getByText(/este mes/));
 assert.equal(screen.queryByRole('button',{name:'Agregar otro'})===null,true);
 assert.equal(screen.getAllByRole('checkbox').length,2);
 fireEvent.click(screen.getByRole('checkbox',{name:'Dos rosarios al mes'}));
 await waitFor(()=>assert.equal(fixture.own.find(r=>r.kind==='checks').data.rosary,1));
 fireEvent.click(await screen.findByRole('button',{name:'Agregar otro'}));
 await waitFor(()=>assert.equal(fixture.own.find(r=>r.kind==='checks').data.rosary,2));
 await waitFor(()=>assert(screen.getByText(/2 de 2 veces/)));
 fireEvent.pointerDown(screen.getByRole('button',{name:'Editar: Dos rosarios al mes'}),{button:0,ctrlKey:false,pointerType:'mouse'});
 fireEvent.click(await screen.findByRole('menuitem',{name:'Deshacer último'}));
 await waitFor(()=>assert.equal(fixture.own.find(r=>r.kind==='checks').data.rosary,1));
 assert.equal(screen.getByRole('progressbar',{name:'Compromisos diarios'}).getAttribute('aria-valuenow'),'1');
 fireEvent.click(screen.getByRole('checkbox',{name:'Dos rosarios al mes'}));
 await waitFor(()=>assert.equal(screen.queryByRole('button',{name:'Agregar otro'})===null,true));
 assert.equal(screen.getByRole('checkbox',{name:'Dos rosarios al mes'}).getAttribute('aria-checked'),'false');
 cleanup();
 render(React.createElement(ReflectionSummary,{rows:[row('journal',today,{gratitude:'Por la familia',offering:'Mi esfuerzo',meditation:'Una palabra que guardo'})],start:month+'-01',end:today}));
 assert(screen.getByRole('button',{name:'Mis agradecimientos'}));assert(screen.getByText('Por la familia'));assert.equal(screen.queryByText('Mi esfuerzo'),null);
 fireEvent.click(screen.getByRole('button',{name:'Mis ofrecimientos a la Mater'}));assert(screen.getByText('Mi esfuerzo'));
 fireEvent.click(screen.getByRole('button',{name:'Mis meditaciones'}));assert(screen.getByText('Una palabra que guardo'));
 assert.equal(document.querySelectorAll('time[datetime="'+today+'"]').length,1);
 console.log('PASS one commitment view, visible cadence chips, repeated monthly occasions and undo, dated gratitude, meditation and offering groups');
}finally{cleanup();dom.window.close();}
