import {PGlite} from '@electric-sql/pglite';
import {readFile,readdir} from 'node:fs/promises';
import assert from 'node:assert/strict';
const db=new PGlite(),id=n=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0');
try{
 await db.exec(`create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to authenticated,anon;grant execute on function auth.uid() to authenticated,anon;`);
 const files=(await readdir('supabase/migrations')).filter(f=>f.endsWith('.sql')).sort();
 for(const f of files.filter(f=>f<'20260909143538'))await db.exec(await readFile('supabase/migrations/'+f,'utf8'));
 for(let n=1;n<=4;n++)await db.query('insert into auth.users values($1,$2,now())',[id(n),`session${n}@example.test`]);
 await db.query("insert into alianza_private.members values($1,'jose','A','Uno'),($2,'neca','B','Dos')",[id(1),id(2)]);
 for(const f of files.filter(f=>f>='20260909143538'))await db.exec(await readFile('supabase/migrations/'+f,'utf8'));
 for(let n=3;n<=4;n++)await db.query("insert into alianza_private.members(id,name) values($1,'Synthetic')",[id(n)]);
 await db.query('insert into alianza_private.admin_members values($1)',[id(1)]);
 const as=async n=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id(n)]);await db.exec('set role authenticated');};
 const rpc=async(name,p)=> (await db.query(`select public.${name}($1::jsonb) v`,[p===null?null:JSON.stringify({dataEpoch:1,relationshipVersion:1,...p})])).rows[0].v;
 const data=p=>rpc('alianza_data',p??null),act=p=>rpc('alianza_community',p??{}),pair=p=>rpc('alianza_relationship',p);
 const save=(kind,key,data,version=0)=>rpc('alianza_data',{kind,key,data,version});
 await as(1);const initial=await data();const rv=initial.user.relationshipVersion;assert.equal(rv,1);
 const today=initial.today,month=today.slice(0,7),next=(await db.query("select to_char((now() at time zone 'America/Costa_Rica')+interval '1 month','YYYY-MM') v")).rows[0].v;
 const h={title:'Caminar',moment:'Mañana',anchor:'secret anchor',minimum:'secret note',active:true,frequency:{period:'day',target:1,unit:'days'}};
 await save('habit','walk',h);await save('journal',today,{gratitude:'Shared gratitude',offering:'Private offering',meditation:'Private meditation'});
 const policy={relationshipVersion:rv,symbol:false,categories:{habit:{mode:'choose',keys:['walk'],future:false,progress:false},gratitude:{mode:'all',keys:[today],future:false,progress:false}}};
 await save('sharing','me',policy);
 await as(2);let snapshot=await data();assert(snapshot.partner.records.some(r=>r.key==='walk'));assert(!JSON.stringify(snapshot.partner).includes('secret'));assert(!JSON.stringify(snapshot.partner).includes('Private offering'));assert(!JSON.stringify(snapshot.partner).includes('Private meditation'));assert.equal(snapshot.partner.appearance,undefined);assert.equal(snapshot.partner.symbol,'');
 await as(3);assert.equal((await data()).partner,null);
 await as(1);await assert.rejects(()=>save('sharing','me',{...policy,relationshipVersion:2},1),e=>e.code==='PT409');
 await save('sharing','me',{...policy,categories:{}},1);await as(2);assert.equal((await data()).partner.records.length,0);
 await as(1);const own=(await data()).own;const habit=own.find(r=>r.key==='walk'&&r.kind==='habit');
 const plan=await pair({action:'prepare_month',month:next,purpose:'Next month',items:[{key:'walk',version:habit.version,keep:false,data:h}],version:0});assert.equal(plan.state.own.find(r=>r.key==='walk'&&r.kind==='habit').data.active,true);assert.equal(plan.state.own.find(r=>r.kind==='month_plan').data.purpose,'Next month');
 await assert.rejects(()=>pair({action:'prepare_month',month:next,purpose:'Duplicate',items:[],version:0}),e=>e.code==='PT409');
 await db.exec('reset role');await db.query('update alianza_private.month_plans set month=$1 where owner=$2',[month,id(1)]);await as(1);snapshot=await data();assert.equal(snapshot.own.find(r=>r.key==='walk'&&r.kind==='habit').data.active,false);const appliedVersion=snapshot.own.find(r=>r.key==='walk'&&r.kind==='habit').version;assert.equal((await data()).own.find(r=>r.key==='walk'&&r.kind==='habit').version,appliedVersion);
 const group=(await act({action:'group_create',name:'Synthetic course',displayName:'Uno'})).groups[0];
 await act({action:'course_invite',groupId:group.id,email:'session3@example.test'});await act({action:'course_invite',groupId:group.id,email:'session3@example.test'});
 await as(3);let inbox=(await act()).invitations;assert.equal(inbox.length,1);const invite=inbox[0];
 await as(4);assert.equal((await act()).invitations.length,0);await assert.rejects(()=>act({action:'course_accept',id:invite.id,version:1}),e=>e.code==='42501');await assert.rejects(()=>act({action:'course_invite',groupId:group.id,email:'session2@example.test'}),e=>e.code==='42501');
 await as(3);let result=await act({action:'course_decline',id:invite.id,version:1});assert.equal(result.invitations[0].status,'declined');assert.equal(result.groups.length,0);await assert.rejects(()=>act({action:'course_restore',id:invite.id,version:1}),e=>e.code==='PT409');result=await act({action:'course_restore',id:invite.id,version:2});assert.equal(result.invitations[0].status,'pending');assert.equal(result.groups.length,0);result=await act({action:'course_accept',id:invite.id,version:3});assert(result.groups.some(g=>g.id===group.id));assert.equal(result.invitations.length,0);
 await as(1);await save('rosary_preferences','me',{include:true,mary:'trinitarian',position:'end'});const rosaryId=id(80);result=await act({action:'rosary_create',id:rosaryId,scope:'personal',mystery:'joyful',mode:'free',intention:''});assert.equal(result.rosaries.find(r=>r.id===rosaryId).opening.position,'end');assert.equal(result.rosaries.find(r=>r.id===rosaryId).opening.mary,'trinitarian');
 const scheduled={...h,title:'Ten scheduled days',frequency:{period:'day',target:1,unit:'days',course:{start:today,days:10,weekdays:[0,1,2,3,4,5,6]}}};await save('habit','bounded',scheduled);
 await db.exec('reset role');await db.query('update alianza_private.members set data_epoch=data_epoch+1 where id=$1',[id(1)]);await as(1);assert.equal((await data()).own.filter(r=>r.kind==='month_plan').length,0);
 console.log('PASS session3: server-side per-category privacy, private notes, revocation, recipient-only invitations, rejection/recovery, optimistic versions, future-month isolation and exactly-once application');
}catch(e){console.error('FAIL',e.message,e.code??'',e.where??'');process.exitCode=1;}finally{await db.close();}
