import React,{useState,type ReactNode,type ButtonHTMLAttributes} from 'react';
import {TreeDeciduous,Plus,Undo2,Pencil,ChevronLeft,ChevronRight,Pause,SlidersHorizontal,Copy,Check,Sun,Cross,UserRound} from 'lucide-react';
import {Mass} from '../../app/mass';

type Tone='primary'|'secondary'|'quiet'|'danger';
function Action({tone='secondary',children,...props}:ButtonHTMLAttributes<HTMLButtonElement>&{tone?:Tone}){return <button type="button" className={'ux-action ux-'+tone} {...props}>{children}</button>}
function Actions({children}:{children:ReactNode}){return <div className="ux-actions">{children}</div>}
const areas=['Galería','Compromisos','Rosario','Misa','Edición','Pareja y grupos','Administración'] as const;
export function ReviewGallery(){
 const [area,setArea]=useState<(typeof areas)[number]>('Compromisos');
 return <div id="integral-review"><header className="review-tools"><p>Alianza · revisión de experiencia</p><label>Sección a revisar<select value={area} onChange={e=>setArea(e.target.value as typeof area)}>{areas.map(x=><option key={x}>{x}</option>)}</select></label><p className="review-note">Datos ficticios. Las acciones solo cambian esta demostración; no envían invitaciones ni guardan datos.</p></header><section className="review-phone" aria-label={'Propuesta: '+area}><div className="review-body">{area==='Galería'?<Gallery/>:area==='Compromisos'?<Commitments/>:area==='Rosario'?<Rosary/>:area==='Misa'?<Mass now={()=>new Date('2026-09-20T16:00:00Z')}/>:area==='Edición'?<Editor/>:area==='Pareja y grupos'?<Relationships/>:<Admin/>}</div><div className="ux-nav" aria-label="Navegación ilustrativa"><span><Sun/>Hoy</span><span><Cross/>Oración</span><span><UserRound/>Mi espacio</span></div></section></div>
}
function Gallery(){return <><h1>Botones de Alianza</h1><p className="ux-muted">Una jerarquía común, con tamaño visual liviano.</p><h2>Acciones principales</h2><Actions><Action tone="primary">Guardar cambios</Action><Action tone="primary" disabled aria-busy="true">Guardando…</Action></Actions><h2>Acciones secundarias</h2><Actions><Action><Pencil/>Editar</Action><Action><Plus/>Registrar otro</Action><Action tone="quiet"><Undo2/>Deshacer último</Action></Actions><h2>Navegación y selección</h2><Actions><Action tone="quiet"><ChevronLeft/>Volver</Action><Action aria-pressed="true">Diario</Action><Action aria-pressed="false">Semanal</Action></Actions><h2>Acción delicada</h2><Actions><Action tone="danger">Cancelar invitación</Action></Actions><h2>Sin conexión</h2><p role="status" className="ux-muted">Conectate para guardar. Tu borrador se conserva.</p><Action disabled>Guardar cambios</Action><h2>Texto largo</h2><Action>Renovar la invitación y obtener un enlace nuevo</Action><p className="ux-muted">Ejemplos de apariencia; estos botones no realizan operaciones.</p></>}
function Commitments(){const [morning,M]=useState(true),[night,N]=useState(false),[week,W]=useState(false),[extra,E]=useState(0),[empty,Z]=useState(false);const done=+morning + +night;return <><h1>Mis compromisos</h1><div className="ux-hero"><div className="ux-symbol" role="progressbar" aria-label="Avance diario" aria-valuemin={0} aria-valuemax={empty?1:2} aria-valuenow={empty?0:done} aria-valuetext={empty?'Sin compromisos diarios':done+' de 2 diarios'}><TreeDeciduous/><span style={{clipPath:`inset(${empty?100:100-done*50}% 0 0 0)`}}><TreeDeciduous/></span></div><div><strong>{empty?'Sin metas diarias':done+' de 2'}</strong><p className="ux-muted">{empty?'Podés registrar lo semanal y mensual':'Compromisos diarios'}</p></div></div><p className="ux-ideal">Líder de amor</p>
{!empty&&<><h2>Mañana</h2><section className="ux-card"><div className="ux-habit"><button className="ux-check" aria-label="Oración matutina" aria-pressed={morning} onClick={()=>M(!morning)}>{morning&&<Check/>}</button><div>Oración matutina <span className="ux-chip">Diario</span></div></div><details className="ux-disclosure"><summary>Ofrecimiento · opcional</summary><p>Espacio de ejemplo para escribir.</p></details></section></>}
<h2>Durante el día</h2><section className="ux-card"><div className="ux-habit"><button className="ux-check" aria-label="Ejercicio de hoy" aria-pressed={week} onClick={()=>W(!week)}>{week&&<Check/>}</button><div>Ejercicio <span className="ux-chip">Semanal</span><meter min="0" max="3" value={week?2:1} aria-label="Avance semanal"/><p className="ux-muted">{week?2:1} de 3 días esta semana</p></div></div><div className="ux-habit"><span className={'ux-small-symbol '+(extra?'ux-halo':'')} aria-hidden="true"><TreeDeciduous/></span><div>Rezar el rosario <span className="ux-chip">Mensual</span><meter min="0" max="2" value="2" aria-label="Meta mensual cumplida"/><p className="ux-muted">2 de 2 ocasiones · cumplido</p><p className="ux-extra" aria-live="polite">{extra>0?'+'+extra+(extra===1?' adicional':' adicionales'):''}</p><Actions><Action onClick={()=>E(extra+1)}><Plus/>Registrar otro</Action>{extra>0&&<Action tone="quiet" onClick={()=>E(extra-1)}><Undo2/>Deshacer último</Action>}</Actions></div></div></section>
{!empty&&<><h2>Noche</h2><section className="ux-card"><div className="ux-habit"><button className="ux-check" aria-label="Oración de la noche" aria-pressed={night} onClick={()=>N(!night)}>{night&&<Check/>}</button><div>Oración de la noche <span className="ux-chip">Diario</span></div></div><details className="ux-disclosure"><summary>Agradecimiento · opcional</summary><p>Espacio de ejemplo para escribir.</p></details></section></>}
<details className="review-cases"><summary>Escenario de revisión</summary><label><input type="checkbox" checked={empty} onChange={e=>Z(e.target.checked)}/> Sin compromisos diarios</label></details></>}
function Rosary(){const [step,S]=useState(1),[paused,P]=useState(false),[expanded,X]=useState(false),[options,O]=useState(false);return <><h1>Mi rosario</h1><p className="ux-muted">Misterio de ejemplo</p><Actions><Action tone="quiet" onClick={()=>P(!paused)}><Pause/>{paused?'Continuar rezo':'Pausar'}</Action></Actions><div className="ux-rosary-count"><Cross/><strong>Avemaría {step} de 10</strong></div><Action aria-expanded={expanded} onClick={()=>X(!expanded)}>{expanded?'Ocultar oración':'Ver oración'}</Action>{expanded&&<p className="ux-muted">Vista de lectura. Este dummy no reproduce textos de oración.</p>}<Actions><Action tone="primary" disabled={paused||step===10} onClick={()=>S(step+1)}>Avanzar<ChevronRight/></Action><Action tone="quiet" disabled={step===1} onClick={()=>S(step-1)}><ChevronLeft/>Atrás</Action><Action aria-expanded={options} onClick={()=>O(!options)}><SlidersHorizontal/>Opciones</Action></Actions>{options&&<section className="ux-card ux-pad"><label><input type="checkbox"/> Mantener pantalla encendida</label><p className="ux-muted">Control ilustrativo; no activa funciones del dispositivo.</p></section>}</>}
function Editor(){const [name,N]=useState('Oración matutina'),[saved,S]=useState(name),[state,T]=useState('idle'),[offline,F]=useState(false),[fail,Q]=useState(false),[discard,D]=useState(false);function save(){T('saving');setTimeout(()=>{if(fail)T('error');else{S(name);T('saved')}},650)}return <><h1>Editar compromiso</h1><label className="ux-field">Nombre<input value={name} onChange={e=>{N(e.target.value);T('idle')}}/></label><p className="ux-muted">Frecuencia: diario · Mañana</p><Actions><Action tone="primary" disabled={offline||state==='saving'||!name.trim()} aria-busy={state==='saving'} onClick={save}>{state==='saving'?'Guardando…':'Guardar cambios'}</Action><Action tone="quiet" disabled={state==='saving'} onClick={()=>{if(name!==saved)D(true);else T('idle')}}>Cancelar edición</Action></Actions>{discard&&<section className="ux-confirm" role="group" aria-label="Confirmar descarte de edición"><p>¿Descartar los cambios sin guardar?</p><Actions><Action tone="quiet" onClick={()=>D(false)}>Seguir editando</Action><Action tone="danger" onClick={()=>{N(saved);T('idle');D(false)}}>Descartar cambios</Action></Actions></section>}{state==='error'&&<p role="alert">No se guardó. Conservamos lo que escribiste; podés reintentar.</p>}{state==='saved'&&<p role="status">Guardado en esta demostración.</p>}{offline&&<p role="status">Sin conexión. Tu borrador sigue aquí.</p>}<details className="review-cases"><summary>Escenarios de revisión</summary><label><input type="checkbox" checked={offline} onChange={e=>F(e.target.checked)}/> Sin conexión</label><label><input type="checkbox" checked={fail} onChange={e=>Q(e.target.checked)}/> Simular error al guardar</label></details></>}
function Relationships(){const [paired,P]=useState(false),[confirm,C]=useState(false),[count,N]=useState(1),[cancelled,X]=useState(false);return <><h1>Pareja y grupos</h1><section className="ux-card ux-pad"><h2>Solicitud de Alex</h2><p className="ux-muted">{paired?'Vinculación aceptada en la demo.':cancelled?'Solicitud rechazada en la demo.':'Vincularse requiere la aceptación de ambos.'}</p>{!paired&&!cancelled&&<Actions><Action tone="primary" onClick={()=>P(true)}>Aceptar solicitud</Action><Action tone="quiet" onClick={()=>C(true)}>Rechazar</Action></Actions>}{confirm&&<section className="ux-confirm" role="group" aria-label="Confirmar rechazo"><p>¿Rechazar la solicitud de Alex?</p><Actions><Action tone="quiet" onClick={()=>C(false)}>Conservar solicitud</Action><Action tone="danger" onClick={()=>{X(true);C(false)}}>Rechazar solicitud</Action></Actions></section>}</section><section className="ux-card ux-pad"><h2>Propósito del grupo</h2><p aria-live="polite">{count} {count===1?'aporte':'aportes'} en esta demostración</p><Actions><Action onClick={()=>N(count+1)}><Plus/>Registrar aporte</Action><Action tone="quiet" disabled={!count} onClick={()=>N(count-1)}><Undo2/>Deshacer aporte</Action></Actions></section></>}
function Admin(){const [status,S]=useState('Vencida'),[confirm,C]=useState(false),[message,M]=useState(''),[link,L]=useState(false);return <><h1>Personas e invitaciones</h1><label className="ux-field">Buscar participante<input placeholder="Nombre o correo" defaultValue="Alex"/></label><section className="ux-card ux-pad"><h2>Alex · cuenta de ejemplo</h2><p aria-live="polite">Invitación: {status}</p><Actions><Action disabled={status==='Cancelada'} onClick={()=>{S('Pendiente');L(true);M('Nuevo enlace simulado. No se emitió una invitación real.')}}>{link?'Renovar enlace':'Renovar invitación'}</Action>{link&&<Action onClick={()=>M('Copia simulada. No se modificó tu portapapeles.')}><Copy/>Copiar enlace</Action>}</Actions>{status!=='Cancelada'&&<Actions><Action tone="danger" onClick={()=>C(true)}>Cancelar invitación</Action></Actions>}{confirm&&<section className="ux-confirm" role="group" aria-label="Confirmar cancelación"><p>¿Cancelar la invitación de Alex?</p><Actions><Action tone="quiet" onClick={()=>C(false)}>Conservar invitación</Action><Action tone="danger" onClick={()=>{S('Cancelada');C(false);L(false);M('Invitación cancelada solo en la demo.')}}>Confirmar cancelación</Action></Actions></section>}<p role="status" className="ux-muted">{message}</p></section><p className="ux-muted">La administración no muestra diarios, oraciones ni compromisos privados.</p></>}
