import '../../tests/dom.mjs';
import React from 'react';
import assert from 'node:assert/strict';
import {render,screen,fireEvent,cleanup,waitFor} from '@testing-library/react';
import {ReviewGallery} from './gallery.tsx';
const change=name=>fireEvent.change(screen.getByLabelText('Sección a revisar'),{target:{value:name}});
render(React.createElement(ReviewGallery));
assert.equal(screen.getByRole('progressbar',{name:'Avance diario'}).getAttribute('aria-valuenow'),'1');
fireEvent.click(screen.getByRole('button',{name:'Ejercicio de hoy'}));
assert.equal(screen.getByRole('progressbar',{name:'Avance diario'}).getAttribute('aria-valuenow'),'1');
fireEvent.click(screen.getByRole('button',{name:'Registrar otro'}));
fireEvent.click(screen.getByRole('button',{name:'Registrar otro'}));
assert(screen.getByText('+2 adicionales'));
fireEvent.click(screen.getByRole('button',{name:'Deshacer último'}));
assert(screen.getByText('+1 adicional'));
fireEvent.click(screen.getByRole('button',{name:'Oración de la noche'}));
assert.equal(screen.getByRole('progressbar',{name:'Avance diario'}).getAttribute('aria-valuenow'),'2');
fireEvent.click(screen.getByLabelText('Sin compromisos diarios'));
assert.equal(screen.getByRole('progressbar',{name:'Avance diario'}).getAttribute('aria-valuetext'),'Sin compromisos diarios');
change('Edición');fireEvent.change(screen.getByLabelText('Nombre'),{target:{value:'Mi borrador'}});
fireEvent.click(screen.getByLabelText('Simular error al guardar'));
fireEvent.click(screen.getByRole('button',{name:'Guardar cambios'}));
assert(screen.getByRole('button',{name:'Guardando…'}).disabled);
await waitFor(()=>assert(screen.getByRole('alert')));
assert.equal(screen.getByLabelText('Nombre').value,'Mi borrador');
fireEvent.click(screen.getByLabelText('Sin conexión'));
assert(screen.getByRole('button',{name:'Guardar cambios'}).disabled);
fireEvent.click(screen.getByRole('button',{name:'Cancelar edición'}));
assert(screen.getByRole('group',{name:'Confirmar descarte de edición'}));
fireEvent.click(screen.getByRole('button',{name:'Seguir editando'}));
assert.equal(screen.getByLabelText('Nombre').value,'Mi borrador');
change('Pareja y grupos');fireEvent.click(screen.getByRole('button',{name:'Rechazar',exact:true}));
fireEvent.click(screen.getByRole('button',{name:'Conservar solicitud'}));
assert(screen.getByRole('button',{name:'Aceptar solicitud'}));
change('Administración');fireEvent.click(screen.getByRole('button',{name:'Renovar invitación'}));
fireEvent.click(screen.getByRole('button',{name:'Copiar enlace'}));
assert(screen.getByText('Copia simulada. No se modificó tu portapapeles.'));
fireEvent.click(screen.getByRole('button',{name:'Cancelar invitación',exact:true}));
fireEvent.click(screen.getByRole('button',{name:'Conservar invitación'}));
assert(screen.getByText('Invitación: Pendiente'));
change('Rosario');fireEvent.click(screen.getByRole('button',{name:'Pausar'}));
assert(screen.getByRole('button',{name:'Avanzar'}).disabled);
change('Misa');assert(screen.getByRole('region',{name:'Misa'}));
fireEvent.click(screen.getByRole('button',{name:'Lecturas',exact:true}));
assert(screen.getByText(/Las lecturas de esta celebración todavía no están disponibles/));
change('Galería');assert(screen.getByRole('heading',{name:'Botones de Alianza'}));
cleanup();console.log('PASS review gallery: 7 vistas, períodos separados, extras/deshacer, error sin perder borrador, offline, confirmación reversible, operaciones sintéticas y Misa real vacía. Sin medición visual ni humana.');
