import {useState} from 'react';
import type {CommunityAction,CourseInvitation} from '@/lib/community';
import {BackButton} from './back-button';
export function CourseInvitations({invitations,act,busy}:{invitations:CourseInvitation[];act:CommunityAction;busy:boolean}){
 const [accepted,setAccepted]=useState(''),[selected,setSelected]=useState(''),[rejected,setRejected]=useState(false),[confirm,setConfirm]=useState(false),[error,setError]=useState(''),[undo,setUndo]=useState('');
 const current=invitations.find(i=>i.id===selected),undone=invitations.find(i=>i.id===undo&&i.status==='declined');
 async function respond(i:CourseInvitation,action:string){setError('');try{await act({action,id:i.id,version:i.version});setConfirm(false);setSelected('');if(action==='course_accept')setAccepted(i.name);if(action==='course_decline')setUndo(i.id);else setUndo('');}catch(e){setError((e as Error).message);}}
 if(!invitations.length&&!error&&!accepted)return null;
 return <section className="s3-invites"><h2>Mis invitaciones</h2>{accepted&&<p role="status">Ya participás en {accepted}. Encontrás el curso en Mi curso, a continuación.</p>}{error&&<p role="alert">{error}</p>}{undone&&<div role="status"><p>Invitación rechazada.</p><button disabled={busy} onClick={()=>respond(undone,'course_restore')}>Deshacer</button></div>}{current?<><BackButton label="Volver a mis invitaciones" onClick={()=>{setSelected('');setConfirm(false);}}/><h3>{current.name}</h3><p>{current.senderName} te invitó a participar.</p>{current.status==='declined'?<button disabled={busy} onClick={()=>respond(current,'course_restore')}>Recuperar invitación</button>:confirm?<><p>¿Rechazar esta invitación?</p><div className="s3-actions"><button disabled={busy} onClick={()=>setConfirm(false)}>Conservar invitación</button><button disabled={busy} onClick={()=>respond(current,'course_decline')}>Sí, rechazar</button></div></>:<><p className="muted">Tu nombre y pertenencia al curso serán visibles para sus miembros. Tus reflexiones personales siguen privadas.</p><div className="s3-actions"><button className="primary" disabled={busy} onClick={()=>respond(current,'course_accept')}>Aceptar invitación</button><button onClick={()=>setSelected('')}>Ahora no</button></div><button onClick={()=>setConfirm(true)}>Rechazar invitación</button></>}</>:<>{invitations.filter(i=>i.status===(rejected?'declined':'pending')).map(i=><div className="card s3-invite-card" key={i.id}><div><h3>{i.name}</h3><p className="muted">{i.senderName} te invitó</p></div><button onClick={()=>setSelected(i.id)}>{rejected?'Recuperar invitación':'Ver invitación'}</button></div>)}<button className="s3-invite-history" onClick={()=>setRejected(!rejected)}>{rejected?'Ver pendientes':'Ver rechazadas'}</button></>}</section>;
}
