import {useRef,useState} from 'react';
import {Users,Plus,ChevronLeft,Heart,Check,BookOpen} from 'lucide-react';
import {type CommunityState,type CommunityAction,type CommunityGroup,type GroupCapability,type PermissionRule} from '@/lib/community';
import {localDate,prettyDate} from '@/lib/domain';
import {PersonalSymbol} from './personal-symbol';
import {prepareSymbol} from './symbol-picker';
import {Form,Input,PurposeCard,CreateRosary,RosaryCard} from './community';
import {AppPanel} from './app-panel';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
const capabilities:[GroupCapability,string][]=[['rosary','Rosarios'],['purpose','Propósitos'],['meeting','Encuentros y encargos'],['capital','Capital de gracias'],['materials','Avisos y materiales'],['invites','Invitaciones'],['identity','Identidad del grupo']];
export function canGroup(g:CommunityGroup,user:string,cap:GroupCapability){if(g.ownerId===user||g.coordinators?.includes(user))return true;const rule=g.permissions?.[cap];return rule?.mode==='all'||(rule?.mode==='selected'&&rule.users.includes(user))||(!rule&&cap==='rosary');}
function GroupPermissions({group,userId,act,busy}:{group:CommunityGroup;userId:string;act:CommunityAction;busy:boolean}){
 const [rules,setRules]=useState(group.permissions||{}),[coordinators,setCoordinators]=useState(group.coordinators||[]);const baseVersion=useRef(group.version);const latest=useRef({rules,coordinators});latest.current={rules,coordinators};
 return <Form title="Permisos y responsabilidades" busy={busy} submit={async()=>{await act({action:'group_permissions',groupId:group.id,version:baseVersion.current,permissions:latest.current.rules,coordinators:latest.current.coordinators});baseVersion.current++;}}>
 <p>Coordinadores</p>{group.members.filter(m=>m.id!==group.ownerId).map(m=><label className="member-choice" key={m.id}><input type="checkbox" checked={coordinators.includes(m.id)} onChange={e=>setCoordinators(e.target.checked?[...coordinators,m.id]:coordinators.filter(x=>x!==m.id))}/>{m.name}</label>)}
 {capabilities.map(([id,label])=>{const rule:PermissionRule=rules[id]||{mode:id==='rosary'?'all':'coordinators',users:[]};return <div className="permission-row" key={id}><strong>{label}</strong><label><span className="sr-only">Quién puede administrar {label.toLowerCase()}</span><select aria-label={'Permiso: '+label} value={rule.mode} onChange={e=>setRules({...rules,[id]:{...rule,mode:e.target.value as PermissionRule['mode']}})}><option value="coordinators">Solo coordinadores</option><option value="selected">Personas específicas</option><option value="all">Todos los miembros</option></select></label>{rule.mode==='selected'&&group.members.filter(m=>m.id!==group.ownerId&&!coordinators.includes(m.id)).map(m=><label className="member-choice" key={m.id}><input type="checkbox" checked={rule.users.includes(m.id)} onChange={e=>setRules({...rules,[id]:{...rule,users:e.target.checked?[...rule.users,m.id]:rule.users.filter(x=>x!==m.id)}})}/>{m.name}</label>)}</div>;})}<p className="form-hint">Estos permisos no dan acceso a registros espirituales personales.</p></Form>;
}
function Identity({group,act,busy}:{group:CommunityGroup;act:CommunityAction;busy:boolean}){
 const [photo,setPhoto]=useState(group.photo||''),[symbolImage,setSymbolImage]=useState(group.symbolImage||''),[processing,setProcessing]=useState(false),[error,setError]=useState('');
 const baseVersion=useRef(group.version);const latest=useRef({photo,symbolImage});latest.current={photo,symbolImage};
 async function upload(file:File|undefined,symbol:boolean){if(!file)return;setProcessing(true);setError('');try{const image=await prepareSymbol(file,!symbol);if(symbol)setSymbolImage(image);else setPhoto(image);}catch(e){setError((e as Error).message);}finally{setProcessing(false);}}
 return <Form title="Identidad del grupo" busy={busy||processing} submit={async f=>{await act({action:'group_update',groupId:group.id,version:baseVersion.current,...Object.fromEntries(f.entries()),photo:latest.current.photo,symbolImage:latest.current.symbolImage});baseVersion.current++;}}><Input name="name" label="Nombre" required max={80} value={group.name}/><Input name="ideal" label="Nuestro ideal" max={500} value={group.ideal}/><Input name="motto" label="Lema" max={120} value={group.motto}/><label>Símbolo<select name="symbol" defaultValue={group.symbol||'heart'}>{[['church','Santuario'],['heart','Corazón'],['tree','Árbol'],['rosary','Rosario'],['cross','Cruz'],['flame','Fuego'],['star','Estrella']].map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>Subir nuestro símbolo<input type="file" accept="image/jpeg,image/png,image/webp" disabled={processing} onChange={e=>upload(e.target.files?.[0],true)}/></label>{symbolImage&&<><PersonalSymbol image={symbolImage} size={70}/><button type="button" className="text-button" onClick={()=>setSymbolImage('')}>Quitar imagen del símbolo</button></>}<label>Foto del grupo<input type="file" accept="image/jpeg,image/png,image/webp" disabled={processing} onChange={e=>upload(e.target.files?.[0],false)}/></label>{photo&&<><img src={photo} alt="Vista previa del grupo" width={150}/><button type="button" className="text-button" onClick={()=>setPhoto('')}>Quitar foto</button></>}{error&&<p role="alert">{error}</p>}</Form>;
}
export function GroupsWorkspace({state,act,userId,name,coupleId,busy}:{state:CommunityState;act:CommunityAction;userId:string;name:string;coupleId?:string|null;busy:boolean}){
 const [id,setId]=useState(''),[view,setView]=useState('purpose'),[panel,setPanel]=useState(''),[error,setError]=useState(''),[token,setToken]=useState(''),[invite,setInvite]=useState(()=>new URLSearchParams(location.hash.slice(1)).get('grupo')||''),[inviteName,setInviteName]=useState(''),[purposeId,setPurposeId]=useState(''),[roleView,setRoleView]=useState('member');
 const createId=useRef(crypto.randomUUID());const group=state.groups.find(g=>g.id===id);const owner=group?.ownerId===userId,coordinator=!!group&&(owner||!!group.coordinators?.includes(userId)),can=(cap:GroupCapability)=>!!group&&canGroup(group,userId,cap);
 async function send(payload:Record<string,unknown>){setError('');try{return await act(payload);}catch(e){setError((e as Error).message);return null;}}
 const names=Object.fromEntries(group?.members.map(m=>[m.id,m.name])||[]),today=localDate();
 const current=group?.purposes.filter(p=>p.start<=today&&p.end>=today)||[],editing=group?.purposes.find(p=>p.id===purposeId);
 function openPanel(next:string){createId.current=crypto.randomUUID();setPanel(next);setError('');}
 return <>{error&&<p role="alert" className="notice">{error}</p>}{!group?<><div className="page-heading"><h1>Mis cursos y grupos</h1><Users size={30}/></div>{state.groups.map(g=><button className="card home-option" key={g.id} onClick={()=>{setId(g.id);setView('purpose');}}><PersonalSymbol image={g.symbolImage} symbol={g.symbol||'heart'} size={42}/><strong>{g.name}</strong><span>{g.motto||'Abrir grupo'}</span></button>)}<div className="group-actions"><button className="soft-button" onClick={()=>openPanel('create')}><Plus size={18}/>Crear grupo</button><button className="soft-button" onClick={()=>openPanel('join')}>Tengo una invitación</button></div>{invite&&!panel&&<button className="primary" onClick={()=>openPanel('join')}>Abrir mi invitación</button>}</>:<><button className="text-button" onClick={()=>{setId('');setToken('');}}><ChevronLeft size={18}/>Mis grupos</button><div className="group-cover">{group.photo&&<img src={group.photo} alt={'Foto de '+group.name}/>}<div className="group-identity"><PersonalSymbol symbol={group.symbol||'heart'} image={group.symbolImage} size={64}/><div><h2>{group.name}</h2>{group.ideal&&<p>{group.ideal}</p>}{group.motto&&<small>{group.motto}</small>}</div></div></div>
 {(coordinator||capabilities.some(([c])=>can(c)))&&<div className="view-switch" role="group" aria-label="Mi responsabilidad"><button aria-pressed={roleView==='member'} onClick={()=>setRoleView('member')}>Mi participación</button><button aria-pressed={roleView==='organize'} onClick={()=>setRoleView('organize')}>Organizar</button></div>}
 {roleView==='organize'&&<section className="card"><h3>Organizar el grupo</h3>{can('identity')&&<button className="soft-button" onClick={()=>openPanel('identity')}>Editar identidad y fotos</button>}{coordinator&&<button className="soft-button" onClick={()=>openPanel('permissions')}>Permisos y responsabilidades</button>}{can('invites')&&<button className="soft-button" disabled={busy} onClick={async()=>{const v=await send({action:'invite_create',groupId:group.id});if(v){setToken(v.token);openPanel('invite');}}}>Crear invitación</button>}{owner&&<button className="text-button" onClick={()=>openPanel('transfer')}>Transferir coordinación principal</button>}</section>}
 <nav className="group-tabs" aria-label="Secciones del grupo">{[['purpose','Propósito'],['prayer','Rosario'],['capital','Capital de gracias'],['meeting','Encuentro'],['materials','Materiales'],['history','Anteriores']].map(([v,l])=><button key={v} aria-pressed={view===v} onClick={()=>setView(v)}>{l}</button>)}</nav>
 {view==='purpose'&&<>{can('purpose')&&<div className="group-actions"><button className="soft-button" onClick={()=>{setPurposeId('');openPanel('purpose');}}>Nuevo propósito</button></div>}{!current.length&&<p className="empty-text">Todavía no hay un propósito para este período.</p>}{current.map(p=><div key={p.id}>{can('purpose')&&<button className="text-button" onClick={()=>{setPurposeId(p.id);openPanel('purpose');}}>Editar propósito</button>}<PurposeCard p={p} group={group} act={act} userId={userId} coupleId={coupleId} busy={busy}/></div>)}</>}
 {view==='prayer'&&<>{can('rosary')&&<button className="primary" onClick={()=>openPanel('rosary')}>Iniciar rosario del grupo</button>}{state.rosaries.filter(r=>r.groupId===group.id&&!r.cancelled).map(r=><RosaryCard key={r.id} r={r} act={act} busy={busy} userId={userId} names={names} canManage={can('rosary')}/>)}{!state.rosaries.some(r=>r.groupId===group.id)&&<p className="empty-text">Aquí podrán rezar y repartir las decenas.</p>}</>}
 {view==='capital'&&<>{can('capital')&&<button className="soft-button" onClick={()=>openPanel('capital')}>Proponer una intención</button>}{(group.capital||[]).map(c=>{const log=c.mine.find(l=>l.day===today),total=c.mine.reduce((n,l)=>n+l.amount,0),active=c.start<=today&&c.end>=today;return <section className="card" key={c.id}><p className="eyebrow">CAPITAL DE GRACIAS</p><h3>{c.title}</h3><p>{prettyDate(c.start)} — {prettyDate(c.end)}</p><div className="capital-counter"><PersonalSymbol symbol="church" size={50}/><p><strong>{total}</strong> aportes propios</p></div>{active&&<button className="primary" disabled={busy||(log?.amount||0)>=100} onClick={()=>send({action:'capital_log',groupId:group.id,id:c.id,day:today,amount:(log?.amount||0)+1,version:log?.version||0})}>Ofrecer un aporte</button>}{active&&!!log?.amount&&<button className="text-button" disabled={busy} onClick={()=>send({action:'capital_log',groupId:group.id,id:c.id,day:today,amount:log.amount-1,version:log.version})}>Deshacer un aporte de hoy</button>}<label className="member-choice"><input type="checkbox" checked={c.share} disabled={busy} onChange={e=>send({action:'capital_share',groupId:group.id,id:c.id,share:e.target.checked})}/>Incluir mis aportes en el total colectivo</label><p className="group-summary">{c.summary?`${c.summary.range} aportes compartidos al cierre`:'El resumen colectivo se publica al cerrar el período cuando puede protegerse la privacidad.'}</p></section>;})}{!group.capital?.length&&<p className="empty-text">Una intención común y los aportes que cada uno quiera ofrecer.</p>}</>}
 {view==='meeting'&&<>{can('meeting')&&<button className="soft-button" onClick={()=>openPanel('meeting')}>{group.meeting?'Editar encuentro':'Preparar encuentro'}</button>}{group.meeting&&<section className="card"><p className="eyebrow">PRÓXIMO ENCUENTRO</p><h3>{prettyDate(group.meeting.data.date)} · {group.meeting.data.time}</h3><p>{group.meeting.data.place}</p>{group.meeting.data.question&&<p>{group.meeting.data.question}</p>}{group.meeting.data.material&&<a href={group.meeting.data.material} target="_blank" rel="noreferrer">Abrir material</a>}<div className="group-actions">{[[true,'Voy a asistir'],[false,'No puedo asistir']].map(([v,l])=><button className="soft-button" key={String(v)} aria-pressed={group.meeting!.responses.some(r=>r.userId===userId&&r.attending===v)} disabled={busy} onClick={()=>send({action:'meeting_rsvp',groupId:group.id,version:group.meeting!.version,attending:v})}>{l}</button>)}</div>{roleView==='organize'&&can('meeting')&&<div>{group.members.map(m=><p key={m.id}>{m.name} · {group.meeting!.responses.find(r=>r.userId===m.id)?.attending===true?'Asiste':group.meeting!.responses.find(r=>r.userId===m.id)?.attending===false?'No asiste':'Por confirmar'}</p>)}</div>}</section>}<h3>{roleView==='organize'?'Encargos del grupo':'Mis encargos'}</h3>{(group.tasks||[]).filter(t=>roleView==='organize'||t.assignee===userId).map(t=><section className="card" key={t.id}><strong>{t.title}</strong><p>{names[t.assignee]}</p><button className="soft-button" disabled={busy||!(can('meeting')||t.assignee===userId)} onClick={()=>send({action:'task_complete',groupId:group.id,id:t.id,version:t.version,done:!t.done})}>{t.done?'Completado · Deshacer':'Marcar completado'}</button></section>)}{can('meeting')&&<button className="text-button" onClick={()=>openPanel('task')}>Asignar un encargo</button>}</>}
 {view==='materials'&&<>{can('materials')&&<button className="soft-button" onClick={()=>openPanel('material')}>Compartir aviso o material</button>}{(group.materials||[]).map(m=><section className="card" key={m.id}><h3>{m.title}</h3>{m.url&&<a href={m.url} target="_blank" rel="noreferrer">Abrir material</a>}</section>)}</>}
 {view==='history'&&<><h3>Propósitos anteriores</h3>{group.purposes.filter(p=>p.end<today).map(p=><button className="group-history-item" key={p.id} onClick={()=>{setPurposeId(p.id);openPanel('review');}}><strong>{p.title}</strong><small>{prettyDate(p.start)} — {prettyDate(p.end)}</small></button>)}{!group.purposes.some(p=>p.end<today)&&<p className="empty-text">Los propósitos aparecerán aquí al terminar su período.</p>}</>}

 <AppPanel title="Integrantes" icon="heart">{group.members.map(m=><p key={m.id}>{m.name}{m.id===group.ownerId||group.coordinators?.includes(m.id)?' · Coordinador':''}</p>)}{!owner&&<button className="text-button" disabled={busy} onClick={()=>openPanel('leave')}>Salir del grupo</button>}</AppPanel></>}
 <Dialog open={!!panel} onOpenChange={v=>{if(!v)setPanel('');}}><DialogContent className="editor-dialog"><DialogTitle>{{create:'Crear grupo',join:'Unirme a un grupo',purpose:editing?'Editar propósito':'Nuevo propósito',rosary:'Rosario del grupo',capital:'Capital de gracias',meeting:'Nuestro encuentro',task:'Asignar encargo',material:'Compartir',identity:'Nuestra identidad',permissions:'Organizar responsabilidades',invite:'Invitar al grupo',transfer:'Transferir coordinación',review:'Propósito anterior',leave:'Salir del grupo'}[panel]||'Grupo'}</DialogTitle><DialogDescription className="sr-only">Actividad del curso</DialogDescription>{error&&<p role="alert">{error}</p>}
 {panel==='create'&&<Form title="Nuevo curso o grupo" busy={busy} submit={async f=>{await act({action:'group_create',id:createId.current,name:f.get('name'),displayName:f.get('displayName')});setPanel('');}}><Input label="Nombre del grupo" name="name" required max={80}/><Input label="Mi nombre en el grupo" name="displayName" value={name} required max={60}/></Form>}
 {panel==='join'&&<><label>Código de invitación<input value={invite} onChange={e=>{setInvite(e.target.value.trim());setInviteName('');}}/></label><button className="soft-button" disabled={busy||!invite} onClick={async()=>{const v=await send({action:'invite_preview',token:invite});if(v)setInviteName(v.invitation.name);}}>Consultar invitación</button>{inviteName&&<Form title={'Unirme a '+inviteName} busy={busy} submit={async f=>{await act({action:'invite_join',token:invite,displayName:f.get('displayName')});setPanel('');setInvite('');history.replaceState(null,'',location.pathname+location.search);}}><Input label="Mi nombre en el grupo" name="displayName" required value={name} max={60}/></Form>}</>}
 {group&&<>{panel==='identity'&&<Identity key={group.id} group={group} act={act} busy={busy}/>}{panel==='permissions'&&<GroupPermissions key={group.id} group={group} act={act} busy={busy} userId={userId}/>}
 {panel==='purpose'&&<Form title={editing?'Ajustar el texto del propósito':'Nuestro propósito'} busy={busy} submit={async f=>{await act({action:editing?'purpose_update':'purpose_create',id:editing?.id||createId.current,groupId:group.id,version:editing?.version||0,title:f.get('title'),reason:f.get('reason'),start:f.get('start'),end:f.get('end'),target:Number(f.get('target')),unit:f.get('unit')});setPanel('');}}><Input label="Propósito" name="title" value={editing?.title} required/><Input label="Una frase para recordarlo" name="reason" value={editing?.reason} max={500}/>{editing?<p className="form-hint">Las fechas y la meta se conservan. Para un nuevo período, creá otro propósito.</p>:null}<label>Desde<input name="start" type="date" required defaultValue={editing?.start||today} readOnly={!!editing}/></label><label>Hasta<input name="end" type="date" required defaultValue={editing?.end||today} readOnly={!!editing}/></label><label>Ocasiones propuestas<input name="target" type="number" min={1} max={100} required defaultValue={editing?.target||3} readOnly={!!editing}/></label><label>Registro<select name="unit" defaultValue={editing?.unit||'person'} disabled={!!editing}><option value="person">Por persona</option><option value="couple">Por matrimonio</option></select></label></Form>}
 {panel==='rosary'&&<CreateRosary act={act} busy={busy} groupId={group.id} onCreated={()=>setPanel('')}/>}
 {panel==='capital'&&<Form title="Intención común" busy={busy} submit={async f=>{await act({action:'capital_create',id:createId.current,groupId:group.id,title:f.get('title'),start:f.get('start'),end:f.get('end')});setPanel('');}}><Input label="Intención" name="title" max={240} required/><Input label="Desde" name="start" type="date" value={today} required/><Input label="Hasta" name="end" type="date" value={today} required/></Form>}
 {panel==='meeting'&&<Form title="Preparar encuentro" busy={busy} submit={async f=>{await act({action:'meeting_save',groupId:group.id,version:group.meeting?.version||0,data:Object.fromEntries(f.entries())});setPanel('');}}>{[['date','Día','date'],['time','Hora','time'],['place','Lugar','text'],['question','Tema o pregunta','text'],['material','Enlace del material','url'],['roles','Responsabilidades acordadas','text']].map(([key,label,type])=><Input key={key} name={key} label={label} type={type} value={(group.meeting?.data as any)?.[key]||(key==='date'?today:key==='time'?'19:00':'')} max={key==='material'?1000:500} required={['date','time'].includes(key)}/>)}</Form>}
 {panel==='task'&&<Form title="Un encargo concreto" busy={busy} submit={async f=>{await act({action:'task_create',id:createId.current,groupId:group.id,title:f.get('title'),assignee:f.get('assignee')});setPanel('');}}><Input name="title" label="Qué necesitamos preparar" required/><label>Responsable<select name="assignee">{group.members.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label></Form>}
 {panel==='material'&&<Form title="Aviso o material" busy={busy} submit={async f=>{await act({action:'material_create',id:createId.current,groupId:group.id,title:f.get('title'),url:f.get('url')});setPanel('');}}><Input label="Aviso o título" name="title" required max={500}/><Input label="Enlace (opcional)" name="url" type="url" max={1000}/></Form>}
 {panel==='invite'&&<><p>Compartí este enlace con quien querás invitar. Vence en siete días.</p><input aria-label="Enlace de invitación" readOnly value={new URL('./',location.href).href+'#grupo='+token}/><button className="soft-button" onClick={async()=>{try{await navigator.clipboard.writeText(new URL('./',location.href).href+'#grupo='+token);}catch{setError('Seleccioná el enlace para copiarlo.');}}}>Copiar enlace</button><button className="text-button" disabled={busy} onClick={async()=>{if(await send({action:'invite_revoke',groupId:group.id})){setToken('');setPanel('');}}}>Revocar invitaciones vigentes</button></>}
 {panel==='transfer'&&<Form title="Nueva coordinación principal" busy={busy} submit={async f=>{await act({action:'group_transfer',groupId:group.id,userId:f.get('userId')});setPanel('');}}><label>Integrante<select name="userId" required><option value="">Elegir persona</option>{group.members.filter(m=>m.id!==userId).map(m=><option value={m.id} key={m.id}>{m.name}</option>)}</select></label><p>Esta persona podrá administrar la coordinación del grupo.</p></Form>}
 {panel==='leave'&&<><p>Dejarás de acceder a las actividades de {group.name}.</p><button className="primary" disabled={busy} onClick={async()=>{if(await send({action:'group_leave',groupId:group.id})){setPanel('');setId('');}}}>Confirmar salida</button></>}
 {panel==='review'&&editing&&<><h3>{editing.title}</h3><p>{editing.decision||'Sin acuerdo de revisión registrado.'}</p>{can('purpose')&&<Form title="Acuerdo para el próximo período" busy={busy} submit={f=>act({action:'purpose_review',groupId:group.id,id:editing.id,version:editing.version,decision:f.get('decision')})}><Input label="Qué acordamos" name="decision" value={editing.decision} max={500}/></Form>}</>}
 </>}</DialogContent></Dialog></>;
}
