import {ChoiceChips} from './choice-chips';
import {ScheduleGuide} from './formation-guide';
import {Switch} from '@/components/ui/switch';
import {localDate,type Habit} from '@/lib/domain';
export function HabitFields({data,field,first,step}:{data:Habit;field:(k:string,v:any)=>void;first:boolean;step:number}){
 const frequency=data.frequency??{period:'day',target:1};
 return <>{(!first||step===0)&&<><label>¿Qué quiero cultivar?<input required maxLength={180} value={data.title} onChange={e=>field('title',e.target.value)} placeholder="Ej. Caminar diez minutos" autoFocus/></label><ScheduleGuide/></>}
 {(!first||step===1)&&<><label>Frecuencia<select value={frequency.course?'course':frequency.weekdays?'specific':frequency.period} onChange={e=>{const v=e.target.value;field('frequency',v==='course'?{period:'day',target:1,unit:'days',course:{start:localDate(),days:9}}:v==='specific'?{period:'day',target:1,unit:'days',weekdays:[new Date().getDay()]}:{period:v,target:v==='day'?1:3,unit:frequency.unit??'days'});}}><option value="day">Todos los días</option><option value="specific">Días específicos</option><option value="week">Veces por semana</option><option value="month">Veces al mes</option><option value="course">Por un tiempo</option></select></label>
 {frequency.weekdays&&<fieldset><legend>Qué días</legend><div className="weekday-options">{[['Lun',1],['Mar',2],['Mié',3],['Jue',4],['Vie',5],['Sáb',6],['Dom',0]].map(([label,day])=><label key={day}><input type="checkbox" checked={frequency.weekdays!.includes(Number(day))} onChange={e=>field('frequency',{...frequency,weekdays:e.target.checked?[...frequency.weekdays!,Number(day)].sort():frequency.weekdays!.filter(d=>d!==day)})}/>{label}</label>)}</div></fieldset>}
 {frequency.course?<><div className="course-fields"><label>Empiezo el<input type="date" required value={frequency.course.start} onChange={e=>field('frequency',{...frequency,course:{...frequency.course,start:e.target.value}})}/></label><label>Durante cuántos días<input type="number" min={1} max={365} required value={frequency.course.days} onChange={e=>field('frequency',{...frequency,course:{...frequency.course,days:Number(e.target.value)}})}/></label></div><p className="form-hint">Un día del recorrido a la vez.</p></>:<><label className="repeat-option"><input type="checkbox" checked={frequency.unit==='times'} onChange={e=>field('frequency',{...frequency,unit:e.target.checked?'times':'days',target:e.target.checked?frequency.target:Math.min(frequency.target,frequency.period==='day'?1:frequency.period==='week'?7:28)})}/>Permitir más de una vez al día</label>{(frequency.period!=='day'||frequency.unit==='times')&&<label>Cantidad de veces<input type="number" min={1} max={frequency.unit==='times'?99:frequency.period==='week'?7:28} required value={frequency.target} onChange={e=>field('frequency',{...frequency,target:Number(e.target.value)})}/></label>}</>}
 <details className="optional-details"><summary>Más opciones (opcional)</summary><ChoiceChips label="Momento del día" value={data.moment} options={[["Mañana","Mañana"],["Durante el día","Durante el día"],["Noche","Noche"]]} onChange={v=>field('moment',v)}/><label>Mi recordatorio personal<input maxLength={240} value={data.anchor} onChange={e=>field('anchor',e.target.value)} placeholder="Ej. Después de llegar a casa"/></label><label>Mi anotación de apoyo<input maxLength={240} value={data.minimum} onChange={e=>field('minimum',e.target.value)}/></label><div className="switch-row"><label htmlFor="habit-active">Incluir en mi horario</label><Switch id="habit-active" checked={data.active} onCheckedChange={v=>field('active',v)}/></div><small>Al desactivarlo, conservás su historial.</small><p className="form-hint">Los cambios de frecuencia rigen desde hoy; el historial anterior se conserva.</p></details></>}
 </>;
}
