import {APP_VERSION,RELEASE_STAGE} from './version';
import {ArrowRight,Sun,Heart,Sprout} from 'lucide-react';
export type Focus='schedule'|'rs'|'ideal';
export const RELEASE='rosary-progress-2026-09-17';
const options:[Focus,string,string][]=[['schedule','Cuidar un compromiso','Un paso concreto.'],['rs','Vivir las 4 Rs','Un momento juntos.'],['ideal','Escribir mi ideal personal','Mi frase, cuando esté listo.']];
export function Home({focus,choosing,existing,busy,linked=false,onChoose,onContinue,onChange,onExplore}:{focus:Focus;choosing:boolean;existing:boolean;busy:boolean;linked?:boolean;onChoose:(f:Focus)=>void;onContinue:()=>void;onChange:()=>void;onExplore:()=>void}){
 return <><div className="page-heading"><div><p className="eyebrow">A TU RITMO</p><h1>{choosing?'¿Qué te ayudaría hoy?':'Tu espacio para continuar'}</h1></div></div><p className="intro">Un solo paso es suficiente.</p>
 {choosing?<div className="home-options">{options.filter(o=>o[0]!=='rs'||linked).map(([id,title,description])=><button key={id} className="card home-option" disabled={busy} onClick={()=>onChoose(id)}><strong>{title}</strong><span>{description}</span><ArrowRight size={20}/></button>)}</div>:<section className="card"><h2>{options.find(x=>x[0]===focus)?.[1]}</h2><button className="primary" onClick={onContinue}>Continuar <ArrowRight size={18}/></button><button className="action-button" data-action="secondary" onClick={onChange}>Elegir otro comienzo</button></section>}
 {choosing&&<button className="action-button" data-action="navigation" onClick={onExplore}>Explorar mi horario sin elegir todavía</button>}
 </>;
}
export function ReleaseNotes({onDismiss,busy}:{onDismiss?:()=>void;busy?:boolean}){return <section className="card release-note"><p className="eyebrow">{RELEASE_STAGE} · {APP_VERSION}</p><h2>Más fácil de seguir</h2><p className="muted"><time dateTime="2026-09-27">27 de septiembre de 2026</time></p><div className="release-highlights"><p><strong>Tu día, más claro.</strong> El propósito del mes y el avance de tus compromisos, a mano. Prepará el siguiente mes cuando estés listo.</p><p><strong>Compartir, más sencillo.</strong> Elegí qué compartir con tu pareja y encontrá las invitaciones de curso dentro de la app.</p><p><strong>Un espacio para rezar.</strong> Rosario con tus preferencias guardadas y lecturas de la misa por fecha, con oraciones para seguir la celebración.</p></div><p className="form-hint">Alfa privada: versión de prueba que todavía estamos revisando.</p>{onDismiss&&<button className="soft-button" disabled={busy} onClick={onDismiss}>Entendido</button>}</section>;}
