import {APP_VERSION,RELEASE_STAGE} from './version';
import {ArrowRight,Sun,Heart,Sprout} from 'lucide-react';
export type Focus='schedule'|'rs'|'ideal';
export const RELEASE='community-2026-09';
const options:[Focus,string,string][]=[['schedule','Cuidar un compromiso','Un paso concreto.'],['rs','Vivir las 4 Rs','Un momento juntos.'],['ideal','Escribir mi ideal personal','Mi frase, cuando esté listo.']];
export function Home({focus,choosing,existing,busy,linked=false,onChoose,onContinue,onChange,onExplore}:{focus:Focus;choosing:boolean;existing:boolean;busy:boolean;linked?:boolean;onChoose:(f:Focus)=>void;onContinue:()=>void;onChange:()=>void;onExplore:()=>void}){
 return <><div className="page-heading"><div><p className="eyebrow">A TU RITMO</p><h1>{choosing?'¿Qué te ayudaría hoy?':'Tu espacio para continuar'}</h1></div></div><p className="intro">Un solo paso es suficiente.</p>
 {choosing?<div className="home-options">{options.filter(o=>o[0]!=='rs'||linked).map(([id,title,description])=><button key={id} className="card home-option" disabled={busy} onClick={()=>onChoose(id)}><strong>{title}</strong><span>{description}</span><ArrowRight size={20}/></button>)}</div>:<section className="card"><h2>{options.find(x=>x[0]===focus)?.[1]}</h2><button className="primary" onClick={onContinue}>Continuar <ArrowRight size={18}/></button><button className="text-button" onClick={onChange}>Elegir otro comienzo</button></section>}
 {choosing&&<button className="text-button" onClick={onExplore}>Explorar mi horario sin elegir todavía</button>}
 </>;
}
export function ReleaseNotes({onDismiss,busy}:{onDismiss?:()=>void;busy?:boolean}){return <section className="card release-note"><p className="eyebrow">{RELEASE_STAGE} · {APP_VERSION}</p><h2>Tu día, más sencillo</h2><p className="muted"><time dateTime="2026-09-13">13 de septiembre de 2026</time></p><p>Una versión de prueba para mejorar juntos en el piloto.</p><ul className="brief-list"><li>Hoy abre directamente en tus compromisos.</li><li>Oración y actividades del curso tienen su propio espacio.</li><li>El examen de conciencia te acompaña una pregunta a la vez.</li><li>Misterios sugeridos para hoy, con libertad para elegir otros.</li><li>Tocá el logo para verlo en grande.</li></ul><details className="optional-details"><summary>Más mejoras de esta versión</summary><ul className="brief-list"><li>Rosarios individuales, en pareja y en grupo.</li><li>Propósitos y encuentros del curso, con registro voluntario.</li><li>Ideal personal y matrimonial opcionales; las 4 Rs aparecen al vincularse.</li><li>Ajustes y ayudas separados; navegación adaptable a letra grande.</li><li>Medición voluntaria y agregada para mejorar la aplicación.</li></ul></details><details className="optional-details"><summary>Entregas anteriores</summary><p>Antes de este registro numerado: horario espiritual, vinculación de pareja, historial, símbolos personales y mejoras de primer uso. Sus cambios se conservan en el historial del proyecto.</p></details>{onDismiss&&<button className="soft-button" disabled={busy} onClick={onDismiss}>Entendido</button>}</section>;}
