'use client';
import {PairingPanel,MaritalIdeal,PairArchives,type MarriageIdeal} from './pairing';
import {Home,ReleaseNotes,RELEASE,type Focus} from './home';
import {MonthReview} from './month-review';
import {daily,frequencyLabel,plansFor,planAt,isActiveOn,progressFor,progressLabel} from '@/lib/schedule';
import {ScheduleGuide, RsGuide, FormationSource, MarriageIdealGuide, PurposeGuide} from './formation-guide';
import { useCallback, useEffect, useRef, useState } from 'react';
import { TreeDeciduous, Heart, Sun, Moon, BookOpen, Settings, LockKeyhole, Users, ChevronLeft, ChevronRight, Plus, Check, CalendarDays, Pencil, ArrowRight, Download, RefreshCw, Cross, Sparkles, LoaderCircle, ShieldCheck, LogOut, MoreHorizontal, CircleHelp } from 'lucide-react';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Switch } from '@/components/ui/switch';
import { Checkbox } from '@/components/ui/checkbox';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { AlertDialog, AlertDialogContent, AlertDialogTitle, AlertDialogDescription, AlertDialogAction, AlertDialogCancel, AlertDialogFooter } from '@/components/ui/alert-dialog';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem } from '@/components/ui/dropdown-menu';
import { Toaster, toast } from 'sonner';
import Reports from './reports';
import {PersonalSymbol} from './personal-symbol';
import {InstallGuide} from './install-guide';
import {StartCard,QuickHelp} from './start-guide';
import {MovementCostaRica} from './movement-costa-rica';
import { localDate, prettyDate, R_TYPES, rKey, type Habit, type Profile, type RecordItem } from '@/lib/domain';

type Payload={user:{id:string;role:string;email:string;symbol?:string;coupleId?:string|null;relationshipVersion?:number};couple?:{emblem:string}|null;marriageIdeal?:MarriageIdeal|null;invitations?:{id:string;email:string;expiresAt:string}[];archives?:{id:string;archivedAt:string}[];own:RecordItem[];shared:RecordItem[];partner:null|{name:string;ideal:string;symbol?:string;shareSchedule:boolean;shareNotes:boolean;records:RecordItem[]};today:string};
type Editor={kind:string;key:string;title:string;data:any;original:string;version:number;relationshipVersion?:number};
const labels:Record<string,string>={done:'Lo viví',missed:'Me costó',skip:'No aplicaba'};
const defaultR=(type:string,date:string)=>({type,periodDate:date,planDate:'',planTime:'',note:'',done:false,doneDate:''});
function download(name:string,value:string,type:string){const url=URL.createObjectURL(new Blob([value],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function calendar(title:string,date:string,time='20:00',recurrence=''){
 const start=new Date(date+'T'+(time||'20:00')+':00-06:00');const stamp=(d:Date)=>d.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');
 const content=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Alianza//ES','BEGIN:VEVENT','UID:'+crypto.randomUUID()+'@alianza','DTSTAMP:'+stamp(new Date()),'DTSTART:'+stamp(start),'DTEND:'+stamp(new Date(start.getTime()+30*60000)),'SUMMARY:'+title.replace(/[\r\n,;]/g,' '),...(recurrence?['RRULE:FREQ='+recurrence]:[]),'BEGIN:VALARM','TRIGGER:-PT10M','ACTION:DISPLAY','DESCRIPTION:Un momento para nuestra alianza','END:VALARM','END:VEVENT','END:VCALENDAR'].join('\r\n');download('alianza-recordatorio.ics',content,'text/calendar;charset=utf-8');toast.success('Recordatorio preparado. Abrilo y confirmá que se agregue a tu calendario.');}
export default function Journal({dataRequest,onSignOut,assetBase='./'}:{dataRequest:(init?:RequestInit)=>Promise<Response>;onSignOut:()=>void;assetBase?:string}){
 const [state,setState]=useState<Payload|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[online,setOnline]=useState(true);
 const [scheduleView,setScheduleView]=useState<'day'|'month'|'history'>('day'),[chooseAgain,setChooseAgain]=useState(false);
 const [help,setHelp]=useState(false),[install,setInstall]=useState(false),[movement,setMovement]=useState(false);
 const [date,setDate]=useState(localDate()),[tab,setTab]=useState('home'),[editor,setEditor]=useState<Editor|null>(null),[discard,setDiscard]=useState(false),[formError,setFormError]=useState(''),[conflict,setConflict]=useState(false),[reminderTime,setReminderTime]=useState('20:30');
 const editorRef=useRef(editor);editorRef.current=editor;const busyRef=useRef(false);const generation=useRef(0);const requestRef=useRef(0);
 const dirty=!!editor&&JSON.stringify(editor.data)!==editor.original;
 const load=useCallback(async(initial=false)=>{const token=++requestRef.current;const gen=generation.current;try{const r=await dataRequest({cache:'no-store'});const v:any=await r.json();if(!r.ok)throw new Error(v.error||'No pudimos cargar tus registros.');if(token!==requestRef.current||gen!==generation.current||busyRef.current)return;setState(v);setError('');}catch(e){setError((e as Error).message);setState(s=>s?{...s,partner:null}:s);}finally{if(initial)setLoading(false);}},[dataRequest]);
 useEffect(()=>{load(true);const refresh=()=>{if(document.visibilityState==='visible')load();else setState(s=>s?{...s,partner:null}:s);};const offline=()=>{setOnline(false);setState(s=>s?{...s,partner:null}:s);};const on=()=>{setOnline(true);load();};setOnline(navigator.onLine);document.addEventListener('visibilitychange',refresh);window.addEventListener('focus',refresh);window.addEventListener('offline',offline);window.addEventListener('online',on);const id=setInterval(()=>{if(!document.hidden&&!busyRef.current)load();},10000);return()=>{clearInterval(id);document.removeEventListener('visibilitychange',refresh);window.removeEventListener('focus',refresh);window.removeEventListener('offline',offline);window.removeEventListener('online',on);};},[load]);
 useEffect(()=>{const guard=(e:BeforeUnloadEvent)=>{if(editorRef.current&&JSON.stringify(editorRef.current.data)!==editorRef.current.original){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard);},[]);
 const rec=(kind:string,key:string,source=state?.own)=>source?.find(r=>r.kind===kind&&r.key===key);
 async function save(kind:string,key:string,data:any,version?:number,relationshipVersion=state?.user.relationshipVersion){if(busyRef.current)return false;busyRef.current=true;setBusy(true);generation.current++;try{const old=rec(kind,key,kind==='rs'?state?.shared:state?.own);const r=await dataRequest({method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind,key,data,version:version??old?.version??0,...(relationshipVersion?{relationshipVersion}:{})})});const v:any=await r.json();if(!r.ok){if(r.status===409)setConflict(true);throw new Error(v.error||'No se pudo guardar.');}setState(s=>{if(!s)return s;const name=kind==='rs'?'shared':'own';return {...s,[name]:[...s[name].filter(x=>!([v.record,...(v.related??[])].some((r:RecordItem)=>r.kind===x.kind&&r.key===x.key))),v.record,...(v.related??[])]};});toast.success('Guardado');setFormError('');return true;}catch(e){const msg=(e as Error).message==='Failed to fetch'?'Sin conexión. No se guardó; tu texto sigue aquí.':(e as Error).message;setFormError(msg);toast.error(msg);return false;}finally{busyRef.current=false;setBusy(false);generation.current++;}}
 async function pairAction(payload:Record<string,unknown>){if(busyRef.current)throw new Error('Esperá a que termine el guardado.');busyRef.current=true;setBusy(true);generation.current++;try{const r=await dataRequest({method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,relationshipVersion:state?.user.relationshipVersion})});const v=await r.json();if(!r.ok)throw new Error(v.error||'No se pudo completar. Revisá tu espacio e intentá de nuevo.');if(v.state)setState(v.state);return v;}finally{busyRef.current=false;setBusy(false);generation.current++;}}
 function edit(kind:string,key:string,title:string,fallback:any){const old=rec(kind,key,kind==='rs'?state?.shared:state?.own);const data=structuredClone(old?.data??fallback);setFormError('');setConflict(false);setEditor({kind,key,title,data,original:JSON.stringify(data),version:old?.version??0,relationshipVersion:state?.user.relationshipVersion});}
 function close(){if(busy)return;if(dirty)setDiscard(true);else{setEditor(null);setFormError('');}}
 async function submit(e:React.FormEvent){e.preventDefault();if(!editor)return;if(['rs','profile'].includes(editor.kind)&&editor.relationshipVersion!==state?.user.relationshipVersion){setFormError('La vinculación cambió. Cerrá este formulario y revisá tu espacio actualizado.');return;}if(await save(editor.kind,editor.key,editor.data,editor.version,editor.relationshipVersion)){setEditor(null);if(editor.kind==='habit'){setTab('today');setScheduleView('day');}else if(editor.kind==='profile')setTab('home');}}
 function field(key:string,value:any){setEditor(e=>e?{...e,data:{...e.data,[key]:value}}:e);}
 function moveDate(delta:number){const d=new Date(date+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+delta);setDate(d.toISOString().slice(0,10));}
 function mark(key:string,value:string|undefined){const checks={...(rec('checks',date)?.data??{})};if(value)checks[key]=value;else delete checks[key];save('checks',date,checks);}
 function createHabit(habit?:Habit){edit('habit',crypto.randomUUID(),'Mi compromiso',{...(habit??{title:'',moment:'Mañana',anchor:'',minimum:'',active:true}),frequency:habit?.frequency??daily});}
 function editR(type:string){const r=R_TYPES.find(x=>x.id===type)!;edit('rs',rKey(type,date),r.title+' juntos',defaultR(type,date));}
 if(loading)return <main className="gate"><div className="brand-word">Alianza<span>FE Y AMOR</span></div><LoaderCircle className="spin"/><p>Abriendo tu espacio…</p></main>;
 if(!state)return <main className="gate"><ShieldCheck size={36}/><h1>Un espacio para ustedes</h1><p>{error||'No pudimos abrir tu espacio.'}</p><button className="primary" onClick={()=>load(true)}>Volver a intentar</button><button className="text-button" onClick={()=>onSignOut()}>Entrar con otra cuenta</button></main>;
 const profile=rec('profile','me')?.data as Profile;const habits=state.own.filter(x=>x.kind==='habit'&&isActiveOn(state.own,x,date)).sort((a,b)=>a.key.localeCompare(b.key));const checks=rec('checks',date)?.data??{};const journal=rec('journal',date)?.data??{gratitude:'',offering:''};const purpose=rec('purpose',date.slice(0,7))?.data??{text:'',review:''};const done=habits.filter(h=>checks[h.key]==='done').length;const partnerName=state.partner?.name||'tu cónyuge';const month=date.slice(0,7);const monthChecks=state.own.filter(r=>r.kind==='checks'&&r.key.startsWith(month)&&Object.keys(r.data).length>0);const monthR=state.shared.filter(r=>r.kind==='rs'&&r.data.done&&r.data.doneDate?.startsWith(month));
 const linked=state.user.relationshipVersion===undefined||!!state.user.coupleId;
 const preferences=rec('preferences','experience')?.data;const focus=(preferences?.focus??'schedule') as Focus;
 const existing=state.own.some(r=>!['profile','preferences','habit_plan'].includes(r.kind))||state.shared.length>0;
 function continueFocus(value:Focus){if(value==='schedule'){setTab('today');setScheduleView('day');}else if(value==='rs')setTab('couple');else edit('profile','me','Mi nombre y mi ideal',profile);}
 async function chooseFocus(value:Focus){if(await save('preferences','experience',{focus:value,lastSeenRelease:preferences?.lastSeenRelease??''})){setChooseAgain(false);continueFocus(value);}}
 function navigate(value:string){if(value==='journey'){setTab('today');setScheduleView('history');}else setTab(value);}
 const symbol=profile.symbol||state.user.symbol||(state.user.role==='jose'?'tree':state.user.role==='neca'?'rosary':'heart');
 const personalEmblem=state.couple?.emblem==='tree-rosary'||(!state.couple&&['jose','neca'].includes(state.user.role));
 const upcoming=state.shared.filter(r=>r.kind==='rs'&&!r.data.done&&r.data.planDate&&r.data.planDate>=state.today).sort((a,b)=>(a.data.planDate+a.data.planTime).localeCompare(b.data.planDate+b.data.planTime))[0];
 return <><Toaster position="top-center" richColors/><div className="app-shell"><aside className="desktop-brand">{personalEmblem?<img src={assetBase+"emblem.png"} alt="Árbol y rosario entrelazados"/>:<Heart size={80} className="gold-icon"/>}<div className="brand-word">Alianza<span>FE Y AMOR</span></div><p>Un camino compartido.<br/>Una entrega personal.</p><div className="side-ideals">{profile.ideal&&<><PersonalSymbol symbol={symbol}/><span>{profile.ideal}</span></>}{state.partner?.ideal&&<><PersonalSymbol symbol={state.partner.symbol}/><span>{state.partner.ideal}</span></>}</div><small>En alianza con María</small></aside><div className="workspace"><header className="topbar"><a href={assetBase} className="brand-link" aria-label="Alianza, inicio">{personalEmblem?<img src={assetBase+"emblem.png"} alt=""/>:<Heart size={30} className="gold-icon"/>}<span className="brand-word">Alianza<span>FE Y AMOR</span></span></a><div className="topbar-actions"><button className="help-button" onClick={()=>setHelp(true)}><CircleHelp size={19}/>Ayuda</button><div className="account-pill"><PersonalSymbol symbol={symbol} size={18}/><span>{profile.name}</span><LockKeyhole size={14}/></div></div></header>
 {!online&&<div className="notice" role="alert">Estás sin conexión. Conservá esta pantalla; esperá a reconectar para guardar.</div>}{error&&<div className="notice" role="alert">{error}<button onClick={()=>load()}>Reintentar</button></div>}
 <Tabs value={tab} onValueChange={setTab} className="main-tabs"><TabsList className="bottom-nav"><TabsTrigger value="home"><BookOpen/><span>Inicio</span></TabsTrigger><TabsTrigger value="today"><Sun/><span>Horario</span></TabsTrigger><TabsTrigger value="couple"><Heart/><span>Las 4 Rs</span></TabsTrigger><TabsTrigger value="settings"><Settings/><span>Mi espacio</span></TabsTrigger></TabsList>
 {((tab==='couple'&&linked)||(tab==='today'&&scheduleView!=='month'))&&<div className="datebar"><button className="icon-button" onClick={()=>moveDate(-1)} aria-label="Día anterior"><ChevronLeft/></button><label className="date-control"><span>{date===state.today?'Hoy · ':''}{prettyDate(date)}</span><input aria-label="Fecha de los registros" type="date" value={date} max={state.today} onInput={e=>{if((e.target as HTMLInputElement).value&&(e.target as HTMLInputElement).value<=state.today)setDate((e.target as HTMLInputElement).value);}}/></label><button className="icon-button" disabled={date>=state.today} onClick={()=>moveDate(1)} aria-label="Día siguiente"><ChevronRight/></button>{date!==state.today&&<button className="text-button" onClick={()=>setDate(state.today)}>Hoy</button>}</div>}
 <TabsContent value="home" className="pane"><Home focus={focus} choosing={!preferences||chooseAgain} existing={existing} busy={busy||!online} onChoose={chooseFocus} onContinue={()=>continueFocus(focus)} onChange={()=>setChooseAgain(true)} onExplore={()=>{setTab('today');setScheduleView('day');}}/>{existing&&preferences?.lastSeenRelease!==RELEASE&&<ReleaseNotes busy={busy||!online} onDismiss={()=>save('preferences','experience',{focus,lastSeenRelease:RELEASE})}/>}</TabsContent>
 <TabsContent value="today" className="pane"><div className="schedule-nav" role="group" aria-label="Vistas del horario">{([['day','Mi día'],['month','Mi mes'],['history','Historial']] as const).map(([id,title])=><button key={id} aria-pressed={scheduleView===id} onClick={()=>setScheduleView(id)}>{title}</button>)}</div>
 {scheduleView==='day'&&<><div className="page-heading"><div><p className="eyebrow">MI HORARIO ESPIRITUAL</p><h1>{profile.ideal?<>Hoy quiero ser<br/><em>{profile.ideal.toLocaleLowerCase('es')}.</em></>:<>Un paso pequeño.<br/><em>A mi ritmo.</em></>}</h1></div><span className="heading-symbol"><PersonalSymbol symbol={symbol} size={34}/></span></div>
 {purpose.text&&<section className="purpose-strip"><Sparkles size={20}/><div><span className="small-title">Mi propósito particular · registro del mes</span><p>{purpose.text||'Un paso pequeño que exprese mi ideal.'}</p></div><button className="icon-button" aria-label="Editar mi propósito particular" onClick={()=>setScheduleView('month')}><Pencil size={18}/></button></section>}
 {habits.length>0&&<div className="section-heading"><h2>Mis compromisos</h2><span className="muted">{done} registros vividos hoy</span></div>}
 {habits.length===0&&<StartCard role={state.user.role} onCreate={createHabit} onCouple={()=>setTab('couple')}/>}
 {(['Mañana','Durante el día','Noche'] as const).map(moment=>{const list=habits.filter(h=>h.data.moment===moment);return list.length>0&&<section className="habit-group" key={moment}><h3>{moment==='Noche'?<Moon size={16}/>:<Sun size={16}/>} {moment}</h3><div className="card habit-list">{list.map(h=><div className={'habit-row '+(checks[h.key]==='done'?'is-done':'')} key={h.key}><Checkbox id={'habit-'+h.key} className="habit-check" checked={checks[h.key]==='done'} onCheckedChange={v=>mark(h.key,v?'done':undefined)} disabled={busy||!online}/><div className="habit-copy"><label htmlFor={'habit-'+h.key}>{h.data.title}</label><p>{plansFor(state.own,h.key).length&&!planAt(plansFor(state.own,h.key),date)?'Frecuencia anterior sin registrar':frequencyLabel(planAt(plansFor(state.own,h.key),date)??h.data.frequency)}</p>{(planAt(plansFor(state.own,h.key),date)?.period??h.data.frequency?.period)!=='day'&&h.data.frequency&&<p>{progressLabel(progressFor(state.own,h.key,date,state.today))}</p>}<p>{h.data.anchor}</p>{checks[h.key]&&checks[h.key]!=='done'&&<span className="status-label">{labels[checks[h.key]]}</span>}<details><summary>Para un día difícil</summary><p>{h.data.minimum||'Podés anotar que te costó o ajustar el compromiso desde sus opciones.'}</p></details></div><DropdownMenu><DropdownMenuTrigger asChild><button className="icon-button" disabled={busy} aria-label={'Opciones: '+h.data.title}><MoreHorizontal size={20}/></button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onClick={()=>mark(h.key,'missed')}>Me costó</DropdownMenuItem><DropdownMenuItem onClick={()=>mark(h.key,'skip')}>Hoy no aplicaba</DropdownMenuItem><DropdownMenuItem onClick={()=>mark(h.key,undefined)}>Quitar registro</DropdownMenuItem><DropdownMenuItem onClick={()=>edit('habit',h.key,'Editar compromiso',h.data)}>Editar compromiso</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div>)}</div></section>;})}
 {habits.length>0&&<button className="add-button" onClick={()=>createHabit()}><Plus size={18}/>Añadir compromiso</button>}
 <details className="card optional-details daily-extras"><summary>Mi reflexión del día</summary>
 <button className="journal-card" onClick={()=>edit('journal',date,'Mi pausa al cerrar el día',{gratitude:'',offering:''})}><Moon size={24}/><span><strong>Una pausa al cerrar el día</strong><span>{journal.gratitude||journal.offering?'Volver a mi reflexión':'Agradecer, ofrecer y volver a empezar.'}</span></span><ArrowRight size={20}/></button></details>
 {upcoming&&<button className="next-card" onClick={()=>{setDate(upcoming.data.periodDate);setTab('couple');edit('rs',upcoming.key,'Nuestro próximo encuentro',upcoming.data);}}><CalendarDays size={20}/><span>Próximo encuentro<strong>{R_TYPES.find(x=>x.id===upcoming.data.type)?.title} · {prettyDate(upcoming.data.planDate)}</strong></span><ChevronRight size={18}/></button>}
 <p className="gentle-note">Un día difícil no borra el camino recorrido.</p>
</>}
 {scheduleView==='month'&&<MonthReview own={state.own} month={month} today={state.today} onMonth={m=>setDate(m===state.today.slice(0,7)?state.today:m+'-01')} edit={(kind,key,title,fallback)=>{const old=rec(kind,key);if(title==='Continuar mi propósito'&&old){edit(kind,key,title,{...old.data});setEditor(e=>e?{...e,data:{...e.data,text:fallback.text}}:e);}else edit(kind,key,title,fallback);}}/>}
 {scheduleView==='history'&&<><div className="page-heading"><div><p className="eyebrow">MEMORIA Y CRECIMIENTO</p><h1>Mirar el camino.<br/><em>Elegir el próximo paso.</em></h1></div><BookOpen size={34} className="gold-icon"/></div><Reports own={state.own} shared={state.shared} date={date} today={state.today} edit={edit}/><label className="month-control">Mes del historial<input type="month" value={month} max={state.today.slice(0,7)} onInput={e=>{if((e.target as HTMLInputElement).value&&(e.target as HTMLInputElement).value<=state.today.slice(0,7))setDate((e.target as HTMLInputElement).value===state.today.slice(0,7)?state.today:(e.target as HTMLInputElement).value+'-01');}}/></label><div className="stats"><div><strong>{monthChecks.length}</strong><span>días con registro personal</span></div><div><strong>{monthR.length}</strong><span>momentos de las 4 Rs vividos</span></div></div><p className="muted">Los días sin registro no se interpretan como incumplimientos.</p>
 <section className="section"><h2>Mis reflexiones</h2>{state.own.filter(r=>r.kind==='journal'&&r.key.startsWith(month)&&(r.data.gratitude||r.data.offering)).length===0?<p className="empty-text">Tus agradecimientos y ofrecimientos aparecerán aquí.</p>:state.own.filter(r=>r.kind==='journal'&&r.key.startsWith(month)&&(r.data.gratitude||r.data.offering)).sort((a,b)=>b.key.localeCompare(a.key)).map(r=><button className="history-row" key={r.key} onClick={()=>edit('journal',r.key,prettyDate(r.key),r.data)}><span><strong>{prettyDate(r.key)}</strong><span>{(r.data.gratitude||r.data.offering).slice(0,100)}</span></span><ChevronRight size={18}/></button>)}</section>
 <section className="section"><h2>Nuestra memoria matrimonial</h2>{monthR.length===0?<p className="empty-text">Aquí quedarán los momentos que registren como vividos.</p>:monthR.sort((a,b)=>b.data.doneDate.localeCompare(a.data.doneDate)).map(r=><button className="history-row" key={r.key} onClick={()=>edit('rs',r.key,R_TYPES.find(x=>x.id===r.data.type)?.title||'Nuestro encuentro',r.data)}><span><strong>{R_TYPES.find(x=>x.id===r.data.type)?.title} · {prettyDate(r.data.doneDate)}</strong><span>{r.data.note?.slice(0,100)||'Un momento vivido juntos.'}</span></span><ChevronRight size={18}/></button>)}</section>
 {linked&&<section className="card partner-card"><div className="section-heading"><h2>Lo que {partnerName} comparte</h2><LockKeyhole size={18}/></div>{!state.partner?<p>Cuando {partnerName} entre y active la visibilidad, podrás consultar aquí lo que decida compartir.</p>:<><p>{state.partner.ideal}</p>{!state.partner.shareSchedule&&!state.partner.shareNotes&&<p>Su espacio personal está privado.</p>}{state.partner.shareSchedule&&<><h3>Horario · {prettyDate(date)}</h3>{state.partner.records.filter(r=>r.kind==='habit'&&r.data.active).map(h=><div className="partner-row" key={h.key}><span>{h.data.title}</span><span>{labels[rec('checks',date,state.partner!.records)?.data[h.key]]||'Sin registro'}</span></div>)}</>}{state.partner.shareNotes&&<><h3>Reflexión compartida · {prettyDate(date)}</h3><p className="preserve">{rec('journal',date,state.partner.records)?.data.gratitude||'Sin agradecimiento registrado.'}</p><p className="preserve">{rec('journal',date,state.partner.records)?.data.offering||''}</p><h3>Propósito y revisión del mes</h3><p className="preserve">{rec('purpose',month,state.partner.records)?.data.text||'Sin propósito registrado.'}</p><p className="preserve">{rec('purpose',month,state.partner.records)?.data.review||''}</p>{state.partner.records.filter(r=>r.kind==='review'&&r.data.end.startsWith(month)).map(r=><details key={r.key}><summary>Revisión {r.data.start} — {r.data.end}</summary><p className="preserve">{r.data.gratitude}</p><p className="preserve">{r.data.learning}</p><p className="preserve">{r.data.next}</p></details>)}</>}</>}</section>}
</>}
 </TabsContent>
 <TabsContent value="couple" className="pane">{linked?<><div className="page-heading"><div><p className="eyebrow">NUESTRO MATRIMONIO</p><h1>Elegirnos.<br/><em>Una y otra vez.</em></h1></div><Heart className="gold-icon" size={38}/></div><p className="intro"><Users size={17}/> Este espacio es compartido con {partnerName}.</p><p className="muted">Elegí el momento que quieran vivir. Nada se registra hasta que ustedes lo guarden.</p><div className="r-grid">{R_TYPES.map((r,i)=>{const row=rec('rs',rKey(r.id,date),state.shared);const v=row?.data;return <section className={'r-card '+(v?.done?'complete':'')} key={r.id}><div className="r-top"><span className="r-number">0{i+1}</span><span className="rhythm">{r.rhythm}</span>{v?.done&&<Check size={20}/>}</div><h2>{r.title}</h2><p>{r.description}</p><div className="r-status">{v?.done?'Vivido · '+prettyDate(v.doneDate):v?.planDate?'Planeado · '+prettyDate(v.planDate)+(v.planTime?' · '+v.planTime:''):'Un momento por elegir'}</div><button className="r-action" onClick={()=>editR(r.id)}>{v?.done?'Ver nuestro registro':v?.planDate?'Abrir nuestro encuentro':'Preparar este momento'}<ArrowRight size={18}/></button></section>;})}</div>{state.marriageIdeal&&state.user.coupleId&&<MaritalIdeal key={state.user.relationshipVersion} ideal={state.marriageIdeal} coupleId={state.user.coupleId} act={pairAction} busy={busy||!online}/>}<section className="quiet-card"><details><summary>Repasar las 4 Rs y consultar su fuente</summary><RsGuide/></details></section></>:<PairingPanel key={state.user.relationshipVersion} state={state} act={pairAction} busy={busy||!online} onContinue={()=>{setTab('today');setScheduleView('day');}}/>}</TabsContent>
 <TabsContent value="settings" className="pane"><div className="page-heading"><div><p className="eyebrow">A TU MANERA</p><h1>Un espacio tuyo.<br/><em>Vos elegís qué compartir.</em></h1></div><ShieldCheck size={34} className="gold-icon"/></div><section className="card settings-card"><div className="section-heading"><h2>{profile.name}</h2><button className="text-button" onClick={()=>edit('profile','me','Mi nombre y mi ideal',profile)}>Editar</button></div><p className="ideal-line">{profile.ideal}</p><p className="muted break">{state.user.email}</p></section>
 {state.user.relationshipVersion!==undefined&&<PairingPanel key={state.user.relationshipVersion} state={state} act={pairAction} busy={busy||!online} onContinue={()=>{setTab('today');setScheduleView('day');}}/>}
 {linked&&<section className="card settings-card"><h2>Visibilidad para {partnerName}</h2><p>Privado por defecto. Solo vos podés cambiar estos permisos.</p><div className="switch-row"><div><label htmlFor="shareSchedule">Compartir mi horario</label><p>Compromisos y registros, incluido el historial.</p></div><Switch id="shareSchedule" className="privacy-switch" checked={profile.shareSchedule} disabled={busy||!online} onCheckedChange={v=>save('profile','me',{...profile,shareSchedule:v})}/></div><div className="switch-row"><div><label htmlFor="shareNotes">Compartir mis reflexiones</label><p>Agradecimientos, ofrecimientos, propósito y revisiones, incluido el historial.</p></div><Switch id="shareNotes" className="privacy-switch" checked={profile.shareNotes} disabled={busy||!online} onCheckedChange={v=>save('profile','me',{...profile,shareNotes:v})}/></div><div className="switch-row"><div><label htmlFor="shareIdeal">Compartir mi ideal personal</label><p>Solo la frase que guardaste; podés volver a ocultarla.</p></div><Switch id="shareIdeal" className="privacy-switch" checked={profile.shareIdeal??false} disabled={busy||!online} onCheckedChange={v=>save('profile','me',{...profile,shareIdeal:v})}/></div><div className="privacy-note"><LockKeyhole size={17}/><p>Al apagarlo se bloquean nuevas consultas; una pantalla abierta se actualiza al reconectar o en unos segundos. Lo ya leído o copiado no se puede retirar. Las 4 Rs siempre son compartidas.</p></div></section>}
 <PairArchives key={state.user.relationshipVersion} archives={state.archives??[]} act={pairAction} busy={busy||!online}/>
 {state.own.some(r=>r.kind==='habit'&&!r.data.active)&&<section className="card settings-card"><h2>Compromisos en pausa</h2><p>Su historial se conserva. Podés ajustarlos y volver a incluirlos en tu horario.</p>{state.own.filter(r=>r.kind==='habit'&&!r.data.active).map(r=><div className="review-row" key={r.key}><strong>{r.data.title}</strong><button className="text-button" onClick={()=>edit('habit',r.key,'Retomar mi compromiso',r.data)}>Editar y retomar</button></div>)}</section>}
 <section className="card settings-card"><h2>Un recordatorio tranquilo</h2><p>Elegí una hora para tu pausa diaria. Se agrega a tu calendario con un aviso 10 minutos antes.</p><div className="inline-form"><input aria-label="Hora del recordatorio diario" type="time" value={reminderTime} onInput={e=>setReminderTime((e.target as HTMLInputElement).value)}/><button className="soft-button" disabled={!reminderTime} onClick={()=>calendar('Mi pausa diaria · Alianza',state.today,reminderTime,'DAILY')}><CalendarDays size={18}/>Añadir al calendario</button></div><small>Hay que confirmar la importación en el celular. Los avisos dependen del calendario; la app no envía notificaciones por sí sola. No importés el mismo recordatorio dos veces.</small></section>
 <section className="card settings-card"><h2>Instalar Alianza en tu teléfono</h2><p>Abrí Alianza tocando su ícono, como tus otras apps. Te guiamos paso a paso.</p><button className="primary" onClick={()=>setInstall(true)}>Instalar Alianza en mi teléfono</button><p>Entren cada uno con su correo y contraseña. Necesitás conexión para cargar y guardar registros.</p></section>
 <section className="card settings-card"><h2>Tus registros, a mano</h2><p>Podés descargar una copia de tu espacio personal y del espacio matrimonial. La copia contiene texto privado: guardala en un lugar seguro.</p><button className="soft-button" onClick={()=>download('alianza-mis-registros-'+state.today+'.json',JSON.stringify({exportedAt:new Date().toISOString(),personal:state.own,matrimonial:state.shared},null,2),'application/json')}><Download size={18}/>Descargar mis registros</button><p className="privacy-note">Los datos se guardan en el servicio que aloja la app. Los permisos separan las cuentas dentro de la aplicación; no hay cifrado de extremo a extremo y el propietario con acceso administrativo puede acceder a la base de datos. Sin publicidad ni analítica añadida.</p></section>
 <details className="card methodology"><summary>Cómo nos acompaña Alianza</summary><h3>Materiales para consultar</h3><ScheduleGuide/><RsGuide/><p>Las ideas opcionales y las preguntas de esta app son adaptables. Pueden ajustarlas con su asesor o comunidad. El emblema del árbol y rosario es personal, no un logo oficial del Movimiento.</p><h3>Ayudas para formar hábitos</h3><ul><li>Un compromiso ligado a un momento conocido: planes “si ocurre esto, haré aquello” de Peter Gollwitzer.</li><li>Una versión mínima para reducir la dificultad, inspirada en el modelo de BJ Fogg.</li><li>Repetición en un contexto estable y retorno después de las interrupciones, según la investigación de Phillippa Lally y colegas.</li><li>Registro y revisión para elegir un ajuste concreto. Los recuentos describen práctica registrada, no crecimiento espiritual.</li></ul><p>Esta aplicación no ha sido validada en un estudio; la evidencia sobre hábitos orienta su diseño y no garantiza resultados espirituales o matrimoniales.</p><h3>Fuentes</h3><ul><li><a href="https://ramadefamilias.cl/document/las-cuatro-r/" target="_blank" rel="noreferrer">Rama de Familias · Las cuatro R</a></li><li><a href="https://www.schoenstatt.org/es/vida/2015/10/agenvida-el-horario-espiritual-ahora-tambien-como-app/" target="_blank" rel="noreferrer">Schoenstatt · El horario espiritual</a></li><li><a href="https://cancercontrol.cancer.gov/brp/research/constructs/implementation-intentions" target="_blank" rel="noreferrer">National Cancer Institute · Planes de acción</a></li><li><a href="https://www.behaviormodel.org/ability" target="_blank" rel="noreferrer">BJ Fogg · Facilitar la conducta</a></li><li><a href="https://doi.org/10.1002/ejsp.674" target="_blank" rel="noreferrer">Lally et al. · Formación de hábitos</a></li><li><a href="https://www.nngroup.com/articles/progressive-disclosure/" target="_blank" rel="noreferrer">Nielsen Norman Group · Mostrar lo necesario al empezar</a></li><li><a href="https://www.nngroup.com/articles/ten-usability-heuristics/" target="_blank" rel="noreferrer">Nielsen Norman Group · Usabilidad</a></li><li><a href="https://developer.apple.com/design/tips/" target="_blank" rel="noreferrer">Apple · Diseño para el tacto</a></li></ul></details>
 <section className="card settings-card"><h2>Schoenstatt en Costa Rica</h2><p>Conocé el Movimiento, sus comunidades, su historia y sus publicaciones.</p><button className="soft-button" onClick={()=>setMovement(true)}>Conocer el Movimiento en Costa Rica</button></section>
 <ReleaseNotes/>
 <div className="settings-bottom"><button className="text-button" onClick={()=>load()}><RefreshCw size={17}/>Actualizar registros</button><button className="text-button" onClick={()=>onSignOut()}><LogOut size={17}/>Cerrar sesión</button></div></TabsContent></Tabs>
 <footer className="footer"><Cross size={15}/><span>En alianza con María · {profile.name}{state.partner?.name?' & '+state.partner.name:''}</span></footer></div></div>
 <QuickHelp open={help} onOpenChange={setHelp} onNavigate={navigate} onInstall={()=>{setHelp(false);setInstall(true);}}/>
 <InstallGuide open={install} onOpenChange={setInstall}/>
 <MovementCostaRica open={movement} onOpenChange={setMovement}/>
 <Dialog open={!!editor} onOpenChange={v=>{if(!v)close();}}><DialogContent className="editor-dialog" showCloseButton={false}><DialogTitle className="dialog-title">{editor?.title}</DialogTitle><DialogDescription>{editor?.kind==='rs'?<span className="scope-label"><Users size={15}/>Compartido con {partnerName}</span>:<span className="scope-label"><LockKeyhole size={15}/>{editor?.kind==='profile'?'Tu cuenta personal':((['journal','purpose','review'].includes(editor?.kind||'')?profile.shareNotes:profile.shareSchedule)?'Visible para '+partnerName:'Solo vos')}</span>}</DialogDescription>{editor&&['rs','profile'].includes(editor.kind)&&editor.relationshipVersion!==state.user.relationshipVersion&&<p role="alert" className="notice">La vinculación cambió. Tu borrador sigue aquí; cerrá este formulario antes de volver a editar.</p>}{editor&&<form onSubmit={submit} className="editor-form">
 {editor.kind==='habit'&&<><ScheduleGuide/><label>¿Qué quiero cultivar?<input required maxLength={180} value={editor.data.title} onChange={e=>field('title',(e.target as HTMLInputElement).value)} placeholder="Ej. Escuchar con atención a mi familia"/></label><label>¿Con qué frecuencia?<select value={editor.data.frequency?.period??'day'} onChange={e=>field('frequency',{period:e.target.value,target:e.target.value==='day'?1:3})}><option value="day">Cada día</option><option value="week">Días por semana</option><option value="month">Días por mes</option></select></label>{editor.data.frequency?.period&&editor.data.frequency.period!=='day'&&<label>Cantidad de días<input type="number" min={1} max={editor.data.frequency.period==='week'?7:28} required value={editor.data.frequency.target} onChange={e=>field('frequency',{...editor.data.frequency,target:Number(e.target.value)})}/></label>}<p className="form-hint">Cada fecha cuenta una vez. Las nuevas frecuencias y pausas rigen desde hoy; los períodos con cambios se indican como parciales.</p><label>Momento del día<Select value={editor.data.moment} onValueChange={v=>field('moment',v)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{['Mañana','Durante el día','Noche'].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></label><details className="optional-details"><summary>Más opciones (opcional)</summary><p>Un momento conocido y una versión pequeña pueden ayudarte a perseverar.</p><label>Lo haré después de…<input maxLength={240} value={editor.data.anchor} onChange={e=>field('anchor',(e.target as HTMLInputElement).value)} placeholder="Ej. Después de llegar a casa"/></label><label>En un día difícil, mi versión mínima será…<input maxLength={240} value={editor.data.minimum} onChange={e=>field('minimum',(e.target as HTMLInputElement).value)} placeholder="Ej. Dos minutos de escucha sin celular"/></label><div className="switch-row"><label htmlFor="habit-active">Incluir en mi horario</label><Switch id="habit-active" checked={editor.data.active} onCheckedChange={v=>field('active',v)}/></div><small>Al desactivarlo, conservás su historial.</small></details></>}
 {editor.kind==='journal'&&<><p className="form-hint">{prettyDate(editor.key)} · Basta una frase. También podés dejarlo en silencio.</p><label>Hoy agradezco…<textarea rows={4} maxLength={12000} value={editor.data.gratitude} onChange={e=>field('gratitude',(e.target as HTMLTextAreaElement).value)} placeholder="Un encuentro, una ayuda, un gesto…"/></label><label>Ofrezco a la Mater…<textarea rows={4} maxLength={12000} value={editor.data.offering} onChange={e=>field('offering',(e.target as HTMLTextAreaElement).value)} placeholder="Una alegría, un esfuerzo o algo que me costó."/></label></>}
 {editor.kind==='review'&&<><p>Este espacio guarda tus notas sobre el período elegido. No agrega una etapa a las 4 Rs.</p><p className="form-hint">{prettyDate(editor.data.start)} — {prettyDate(editor.data.end)}</p><label>¿Qué quiero agradecer?<textarea rows={3} maxLength={12000} value={editor.data.gratitude} onChange={e=>field('gratitude',(e.target as HTMLTextAreaElement).value)}/></label><label>¿Qué aprendí de lo que ayudó y de lo que costó?<textarea rows={4} maxLength={12000} value={editor.data.learning} onChange={e=>field('learning',(e.target as HTMLTextAreaElement).value)}/></label><label>Un próximo paso que quiero anotar<textarea rows={3} maxLength={12000} value={editor.data.next} onChange={e=>field('next',(e.target as HTMLTextAreaElement).value)} placeholder="¿Qué quiero mantener o ajustar?"/></label></>}
 {editor.kind==='purpose'&&<><PurposeGuide/><p className="form-hint">Registro de {editor.key}. Anotá el propósito que estás trabajando con tu acompañante. Podés mantenerlo durante varios meses.</p><label>Mi propósito particular<textarea rows={3} maxLength={12000} value={editor.data.text} onChange={e=>field('text',(e.target as HTMLTextAreaElement).value)} placeholder="Escribí aquí tu propósito"/></label><label>Mi revisión: qué ayudó, qué costó y un próximo paso<textarea rows={5} maxLength={12000} value={editor.data.review} onChange={e=>field('review',(e.target as HTMLTextAreaElement).value)} placeholder="¿Fue realista? ¿Qué quiero mantener o simplificar?"/></label><p className="form-hint">Estas notas mensuales ayudan a recordar tu revisión. El propósito también se cultiva y revisa en la vida diaria.</p></>}
 {editor.kind==='profile'&&<><label>Cómo quiero que me llamen<input required maxLength={60} value={editor.data.name} onChange={e=>field('name',(e.target as HTMLInputElement).value)}/></label><label>Mi ideal personal (opcional)<input maxLength={200} value={editor.data.ideal} onChange={e=>field('ideal',(e.target as HTMLInputElement).value)}/></label><label>Mi símbolo<Select value={editor.data.symbol||symbol} onValueChange={v=>field('symbol',v)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{[['heart','Corazón'],['tree','Árbol'],['rosary','Rosario'],['cross','Cruz']].map(([value,label])=><SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select></label></>}
 {editor.kind==='rs'&&<><details className="optional-details"><summary>Ideas y preguntas para este encuentro</summary><p className="form-hint">Síntesis de apoyo basada en el material enlazado.</p><p>{R_TYPES.find(x=>x.id===editor.data.type)?.suggestion}</p><div className="questions">{R_TYPES.find(x=>x.id===editor.data.type)?.prompts.map(p=><p key={p}>{p}</p>)}</div><FormationSource topic="rs"/></details><p className="form-hint">Guardá aquí solo lo que ambos quieran compartir. La reflexión individual puede mantenerse fuera de este registro compartido.</p><div className="two-fields"><label>Día del encuentro (opcional)<input type="date" value={editor.data.planDate} onInput={e=>field('planDate',(e.target as HTMLInputElement).value)}/></label><label>Hora (opcional)<input type="time" value={editor.data.planTime} onInput={e=>field('planTime',(e.target as HTMLInputElement).value)}/></label></div>{editor.data.planDate&&<button type="button" className="soft-button" onClick={()=>calendar('Nuestro encuentro · Alianza',editor.data.planDate,editor.data.planTime,({rezar:'DAILY',reencantar:'WEEKLY',revisar:'MONTHLY',renovar:'YEARLY'} as Record<string,string>)[editor.data.type])}><CalendarDays size={17}/>Crear recordatorio recurrente</button>}<small>El recordatorio sigue la frecuencia de esta R. Confirmá su importación. Cambiar la fecha aquí no modifica eventos ya agregados al calendario.</small><label>Nuestra reflexión y un acuerdo (opcional)<textarea rows={5} maxLength={12000} value={editor.data.note} onChange={e=>field('note',(e.target as HTMLTextAreaElement).value)} placeholder="¿Qué nos llevamos? ¿Qué haremos y cuándo?"/></label><div className="switch-row"><label htmlFor="r-done">Ya vivimos este momento</label><Switch id="r-done" checked={editor.data.done} onCheckedChange={v=>setEditor(e=>e?{...e,data:{...e.data,done:v,doneDate:v?(e.data.periodDate>state.today?state.today:e.data.periodDate):''}}:e)}/></div>{editor.data.done&&<label>Lo vivimos el<input required type="date" max={state.today} value={editor.data.doneDate} onInput={e=>field('doneDate',(e.target as HTMLInputElement).value)}/></label>}</>}
 {formError&&<div className="form-error" role="alert">{formError}{conflict&&<button className="text-button" type="button" onClick={async()=>{await load();setFormError('Copiá tu texto si querés conservarlo. Luego cerrá y volvé a abrir este registro para ver la versión actual.');}}>Actualizar versión disponible</button>}</div>}<div className="form-actions"><button type="button" className="soft-button" disabled={busy} onClick={close}>Cerrar</button><button type="submit" className="primary" disabled={busy||!online}>{busy?<><LoaderCircle size={18} className="spin"/>Guardando…</>:<><Check size={18}/>Guardar</>}</button></div><small className="save-hint">{dirty?'Cambios sin guardar':'Sin cambios pendientes'}</small></form>}</DialogContent></Dialog>
 <AlertDialog open={discard} onOpenChange={setDiscard}><AlertDialogContent><AlertDialogTitle>¿Cerrar sin guardar?</AlertDialogTitle><AlertDialogDescription>Los cambios de este formulario se perderán. Tus registros guardados se conservan.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>Seguir escribiendo</AlertDialogCancel><AlertDialogAction onClick={()=>{setDiscard(false);setEditor(null);setFormError('');}}>Descartar cambios</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </>;
}
