import {useRef,useState} from 'react';
import {MarriageIdealGuide,RsGuide} from './formation-guide';
import {R_TYPES,type RecordItem} from '@/lib/domain';
export type MarriageIdeal={text:string;version:number;confirmations:number;confirmedByMe:boolean};
export type PairingState={user:{id:string;coupleId?:string|null;relationshipVersion?:number};partner:null|{name:string};invitations?:{id:string;email:string;expiresAt:string}[];archives?:{id:string;archivedAt:string}[];marriageIdeal?:MarriageIdeal|null};
export type PairAction=(payload:Record<string,unknown>)=>Promise<any>;
export function PairingPanel({state,act,busy,onContinue}:{state:PairingState;act:PairAction;busy:boolean;onContinue?:()=>void}){
 const [mode,setMode]=useState<'start'|'invite'|'receive'>('start');
 const [email,setEmail]=useState(''),[token,setToken]=useState(''),[created,setCreated]=useState<{token:string;email:string}|null>(null);
 const [preview,setPreview]=useState<{name:string;email:string;token:string}|null>(null),[consent,setConsent]=useState(false),[unlink,setUnlink]=useState(false),[error,setError]=useState('');
 const previewRequest=useRef(0);
 async function run(payload:Record<string,unknown>){setError('');try{return await act(payload);}catch(e){setError((e as Error).message);return null;}}
 return <section className="card pairing-panel"><h2>{state.user.coupleId?'Tu vinculación en pareja':'Podés empezar por vos'}</h2>
 {state.user.coupleId?<><p>Tu cuenta está vinculada con {state.partner?.name||'tu cónyuge'}. Cada uno conserva su espacio personal.</p><p>Las 4 Rs y el ideal matrimonial son compartidos. El horario, las reflexiones y el ideal personal se comparten solo si cada uno activa sus permisos.</p>{!unlink?<button className="text-button" onClick={()=>setUnlink(true)}>Administrar desvinculación</button>:<div className="notice"><h3>¿Querés volver al uso individual?</h3><p>Se apagan los permisos personales de ambos. Cada uno conserva sus registros y puede consultar el historial matrimonial anterior, sin editarlo. Ese historial no se comparte con una pareja futura. Lo que alguien ya leyó o copió no se puede retirar.</p><button className="soft-button" disabled={busy} onClick={()=>run({action:'unlink',coupleId:state.user.coupleId})}>Confirmar desvinculación</button><button className="text-button" disabled={busy} onClick={()=>setUnlink(false)}>Conservar vinculación</button></div>}</>:<><p>Tu horario y tu ideal personal pueden acompañarte desde ahora. Podés vincularte después y conservar todo lo que hayas registrado.</p>
 {mode==='start'&&<div className="pair-actions"><button className="primary" disabled={busy} onClick={onContinue}>Continuar individualmente</button><button className="soft-button" onClick={()=>setMode('invite')}>Quiero usarla en pareja</button><button className="text-button" onClick={()=>setMode('receive')}>Tengo un código de vinculación</button></div>}
 {mode==='invite'&&<form onSubmit={async e=>{e.preventDefault();if(!consent)return;const result=await run({action:'create',email});if(result){setCreated({token:result.token,email});setConsent(false);}}}><label>Correo de tu cónyuge<input type="email" maxLength={254} required value={email} onChange={e=>{setEmail(e.target.value);setConsent(false);}} autoCapitalize="none"/></label><p>Ambos necesitan una cuenta habilitada en el piloto. Creá un código y compartilo por el medio que elijás; la app no envía un correo.</p><label className="consent-row"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>Quiero vincular mi cuenta con este correo cuando esa persona acepte. Las 4 Rs y el ideal matrimonial serán compartidos; mis permisos personales comenzarán apagados.</label><button className="primary" disabled={busy||!consent}>Crear código de vinculación</button>{created&&<div role="status"><p>Compartí este código con {created.email}. Vence en siete días. Se muestra solo aquí; si lo perdés, podés crear otro.</p><label>Código para compartir<textarea readOnly rows={3} value={created.token}/></label><button type="button" className="soft-button" onClick={async()=>{try{await navigator.clipboard.writeText(created.token);}catch{setError('Seleccioná el código y copialo manualmente.');}}}>Copiar código</button></div>}</form>}
 {mode==='receive'&&<form onSubmit={async e=>{e.preventDefault();const request=++previewRequest.current;const checkedToken=token.trim().toLowerCase();setPreview(null);setConsent(false);const result=await run({action:'preview',token:checkedToken});if(result&&request===previewRequest.current)setPreview({...result.invitation,token:checkedToken});}}><label>Código que recibiste<input required maxLength={64} value={token} onChange={e=>{previewRequest.current++;setToken(e.target.value);setPreview(null);setConsent(false);}} autoCapitalize="none" spellCheck={false}/></label><button className="soft-button" disabled={busy||!token.trim()}>Revisar invitación</button>{preview&&<div className="pair-preview"><h3>Vincularme con {preview.name}</h3><p className="break">{preview.email}</p><p>Sus registros personales seguirán separados. Las 4 Rs y el ideal matrimonial serán compartidos. No hace falta tener ideal matrimonial para empezar.</p><label className="consent-row"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>Reconozco a esta persona y quiero vincular nuestras cuentas.</label><button type="button" className="primary" disabled={busy||!consent} onClick={()=>run({action:'accept',token:preview.token})}>Aceptar vinculación</button><button type="button" className="text-button" disabled={busy} onClick={async()=>{if(await run({action:'reject',token:preview.token})){setPreview(null);setToken('');}}}>Rechazar invitación</button></div>}</form>}
 {mode!=='start'&&<button className="text-button" disabled={busy} onClick={()=>{previewRequest.current++;setMode('start');setError('');setPreview(null);setConsent(false);setCreated(null);}}>Volver a mis opciones</button>}
 {(state.invitations??[]).map(i=><div className="pair-pending" key={i.id}><p>Vinculación pendiente con <strong className="break">{i.email}</strong>.</p><button className="text-button" disabled={busy} onClick={async()=>{if(await run({action:'cancel',id:i.id}))setCreated(null);}}>Cancelar invitación</button></div>)}
 <details className="optional-details"><summary>Repasar las 4 Rs mientras tanto</summary><RsGuide/></details></>}
 {error&&<p className="notice" role="alert">{error}</p>}</section>;
}
export function MaritalIdeal({ideal,coupleId,act,busy}:{ideal:MarriageIdeal;coupleId:string;act:PairAction;busy:boolean}){
 const [draft,setDraft]=useState<{text:string;version:number}|null>(null),[error,setError]=useState('');
 async function run(payload:Record<string,unknown>){setError('');try{await act({...payload,coupleId});setDraft(null);}catch(e){setError((e as Error).message);}}
 const status=!ideal.text?'Todavía no tenemos ideal matrimonial':ideal.confirmations===2?'Frase confirmada por ambos':'Frase en discernimiento';
 return <details className="card optional-details marital-ideal"><summary>Nuestro ideal matrimonial · opcional</summary><h3>{status}</h3><p>Pueden vivir las 4 Rs y usar sus horarios sin completar esta sección.</p>{ideal.text&&<p className="preserve">{ideal.text}</p>}
 {draft?<form onSubmit={e=>{e.preventDefault();void run({action:'ideal_save',text:draft.text,version:draft.version});}}><label>Nuestra frase<textarea maxLength={200} rows={3} value={draft.text} onChange={e=>setDraft({...draft,text:e.target.value})}/></label><p>Guardar una frase nueva deja pendientes las confirmaciones de ambos. Pueden dejarla vacía si todavía no tienen un ideal.</p><button className="primary" disabled={busy}>Guardar borrador matrimonial</button><button type="button" className="text-button" disabled={busy} onClick={()=>{setDraft(null);setError('');}}>Cancelar edición</button></form>:<><button className="soft-button" onClick={()=>setDraft({text:ideal.text,version:ideal.version})}>{ideal.text?'Editar nuestra frase':'Anotar una frase cuando lo deseemos'}</button>{ideal.text&&<><p>{ideal.confirmations} de 2 confirmaciones de esta versión.</p><button className="text-button" disabled={busy||ideal.confirmedByMe} onClick={()=>run({action:'ideal_confirm',version:ideal.version})}>{ideal.confirmedByMe?'Ya confirmé esta frase':'Confirmo que esta frase nos representa'}</button></>}</>}
 <p>La confirmación expresa acuerdo entre ustedes. El discernimiento del ideal se trabaja con el acompañamiento del Movimiento.</p><MarriageIdealGuide/>{error&&<p role="alert" className="notice">{error}</p>}</details>;
}
export function PairArchives({archives,act,busy}:{archives:{id:string;archivedAt:string}[];act:PairAction;busy:boolean}){
 const [opened,setOpened]=useState<{id:string;records:RecordItem[];ideal:MarriageIdeal}|null>(null),[error,setError]=useState('');
 return archives.length>0?<details className="card optional-details"><summary>Mi historial matrimonial anterior</summary><p>Solo lectura para quienes participaron. No se traslada a otra pareja.</p>{archives.map(a=><div key={a.id}><button className="text-button" disabled={busy} onClick={async()=>{setError('');try{const r=await act({action:'archive',id:a.id});setOpened({id:a.id,...r});}catch(e){setError((e as Error).message);}}}>Consultar archivo del {new Date(a.archivedAt).toLocaleDateString('es-CR',{timeZone:'America/Costa_Rica'})}</button>{opened?.id===a.id&&<div>{opened.ideal?.text&&<p className="preserve">Ideal matrimonial: {opened.ideal.text}</p>}{opened.records.length===0?<p>Sin encuentros guardados.</p>:opened.records.map(r=><details key={r.kind+':'+r.key}><summary>{R_TYPES.find(t=>t.id===r.data.type)?.title??'Encuentro'} · {r.data.periodDate}</summary><p>{r.data.done?'Vivido · '+r.data.doneDate:r.data.planDate?'Planeado · '+r.data.planDate:'Sin fecha acordada'}</p><p className="preserve">{r.data.note}</p></details>)}</div>}</div>)}{error&&<p role="alert">{error}</p>}</details>:null;
}
