import {useRef,useState} from 'react';
import {Check,ChevronLeft,ChevronRight,Cross} from 'lucide-react';
import {type Rosary,type CommunityAction,MYSTERIES} from '@/lib/community';
import {ROSARY_STEPS,PRAYERS} from '@/lib/rosary-guide';
export function RosaryMap({step}:{step:number}){
 const current=ROSARY_STEPS[Math.min(step,ROSARY_STEPS.length-1)];
 return <svg className="rosary-map" viewBox="0 0 300 255" role="img" aria-label={step>=ROSARY_STEPS.length?'Rosario concluido':current.decade===0?'Oraciones iniciales':current.decade===6?'Oraciones finales':`Misterio ${current.decade} de 5`}>
 <ellipse cx="150" cy="100" rx="106" ry="76" fill="none" className="rosary-thread"/>
 {Array.from({length:50},(_,i)=>{const d=Math.floor(i/10)+1,b=i%10+1,angle=(90+(i+.5)*360/50)*Math.PI/180;const index=7+(d-1)*12+b;const done=step>index,active=current.decade===d&&current.bead===b;return <circle key={i} cx={150+106*Math.cos(angle)} cy={100+76*Math.sin(angle)} r={active?5.8:3.8} className={active?'bead-current':done?'bead-complete':'bead-pending'}/>;})}
 {Array.from({length:5},(_,i)=>{const a=(90+i*72)*Math.PI/180,idx=7+i*12;return <circle key={i} cx={150+106*Math.cos(a)} cy={100+76*Math.sin(a)} r="5" className={step===idx?'bead-current':step>idx?'bead-complete':'bead-pending'}/>;})}
 <path className="rosary-thread" d="M150 177v55m-9-7h18" fill="none"/>
 {[186,195,204].map((y,i)=><circle key={y} cx="150" cy={y} r="3" className={step>3+i?'bead-complete':'bead-pending'}/>)}
 <text x="150" y="96" textAnchor="middle">{step>=ROSARY_STEPS.length?'5 / 5':current.decade>0&&current.decade<6?`${current.decade} / 5`:current.decade===0?'Inicio':'Cierre'}</text>
 <text className="rosary-map-caption" x="150" y="120" textAnchor="middle">{current.decade>0&&current.decade<6?'misterio':'Mi rosario'}</text>
 </svg>;
}
export function PersonalRosary({r,act,busy,habits=[],onLinked}:{r:Rosary;act:CommunityAction;busy:boolean;habits?:{key:string;data:{title:string;active:boolean}}[];onLinked?:()=>void}){
 const [active,setActive]=useState(false),[expanded,setExpanded]=useState(false),[error,setError]=useState(''),[selected,setSelected]=useState(''),[linked,setLinked]=useState(false);const sending=useRef(false);
 const step=r.personalStep??(r.slots.filter(s=>s.done).length===5?ROSARY_STEPS.length:0),current=ROSARY_STEPS[Math.min(step,ROSARY_STEPS.length-1)],finished=step>=ROSARY_STEPS.length;
 async function move(next:number){if(sending.current)return;sending.current=true;setError('');try{await act({action:'rosary_step',id:r.id,step:next,version:r.progressVersion??0});setExpanded(false);}catch(e){setError((e as Error).message);}finally{sending.current=false;}}
 return <section className="card personal-rosary"><p className="eyebrow">MI ROSARIO</p><h2>Misterios {MYSTERIES[r.mystery].name.toLowerCase()}</h2>{r.intention&&<p className="muted preserve">{r.intention}</p>}<RosaryMap step={step}/>
 {finished?<><h3>Rosario concluido</h3><p>Quedó registrado en tus rosarios.</p>{habits.some(h=>h.data.active)&&<div className="rosary-link"><label>Marcar también mi compromiso<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Elegir compromiso</option>{habits.filter(h=>h.data.active).map(h=><option key={h.key} value={h.key}>{h.data.title}</option>)}</select></label><button className="soft-button" disabled={!selected||busy||linked} onClick={async()=>{setError('');try{await act({action:'rosary_link',id:r.id,kind:'full',habitKey:selected});setLinked(true);onLinked?.();}catch(e){setError((e as Error).message);}}}>{linked?'Compromiso registrado':'Marcar compromiso'}</button></div>}</>:active?<><p className="eyebrow">{current.decade===0?'ORACIONES INICIALES':current.decade===6?'ORACIONES FINALES':MYSTERIES[r.mystery].items[current.decade-1]}</p><div className="current-prayer" aria-live="polite"><h3>{PRAYERS[current.prayer].name}</h3>{current.bead&&<p>{current.bead} de {current.total}</p>}</div><button className="text-button" aria-expanded={expanded} onClick={()=>setExpanded(!expanded)}>{expanded?'Ocultar oración':'Ver oración'}</button>{expanded&&<p className="prayer-text">{PRAYERS[current.prayer].text}</p>}<div className="guided-actions"><button className="text-button" disabled={busy||step===0} onClick={()=>move(step-1)}><ChevronLeft size={18}/>Atrás</button><button className="primary" disabled={busy} onClick={()=>move(step+1)}>{step===ROSARY_STEPS.length-1?'Terminé el rosario':'Avanzar'}<ChevronRight size={18}/></button></div><button className="text-button" onClick={()=>setActive(false)}>Pausar</button></>:<button className="primary" disabled={busy||r.cancelled} onClick={()=>setActive(true)}><Cross size={18}/>{step?'Continuar rezando':'Empezar a rezar'}</button>}
 {error&&<p role="alert" className="notice">{error}</p>}<a className="quiet-source" href="https://www.vatican.va/special/rosary/documents/misteri_sp.html" target="_blank" rel="noreferrer">Guía del rosario · Santa Sede</a></section>;
}
