import {reflectionText,reflectionFields} from '@/lib/reflections';
import {ReflectionSummary} from './reflection-summary';
import {useState} from 'react';
import {Download} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {ChoiceChips} from './choice-chips';
import {prettyDate,type RecordItem,R_TYPES} from '@/lib/domain';
import {rangeFor} from '@/lib/reports';
import {frequencyLabel} from '@/lib/schedule';
import {commitmentTotals} from '@/lib/commitment-totals';
export default function Reports({own,shared,date,today,edit,linked=false}:{linked?:boolean;own:RecordItem[];shared:RecordItem[];date:string;today:string;edit:(kind:string,key:string,title:string,data:any)=>void}){
 const [downloading,setDownloading]=useState(false),[downloadError,setDownloadError]=useState('');
 const [mode,setMode]=useState('week'),[custom,setCustom]=useState({start:date.slice(0,7)+'-01',end:today}),[open,setOpen]=useState(false),[selected,setSelected]=useState<string[]>([]),[includeCouple,setIncludeCouple]=useState(false),[includeIdeal,setIncludeIdeal]=useState(false);
 const raw=mode==='custom'?custom:rangeFor(mode,date),start=raw.start,end=raw.end>today?today:raw.end,valid=!!start&&!!end&&start<=end;
 const habits=own.filter(r=>r.kind==='habit').map(h=>({...h,totals:commitmentTotals(own,h.key,start,end,today)}));
 const notes=own.filter(r=>r.kind==='journal'?r.key>=start&&r.key<=end&&!!(r.data.gratitude||r.data.offering||r.data.meditation):r.kind==='habit_review'?r.data.start<=end&&r.data.end>=start&&!!r.data.note:r.kind==='review'?r.data.start>=start&&r.data.end<=end:false);
 const textFor=reflectionText;
 const chosen=notes.filter(n=>selected.includes(n.kind+':'+n.key)),ideal=own.find(r=>r.kind==='profile')?.data.ideal||'',purposes=own.filter(r=>r.kind==='purpose'&&r.key>=start.slice(0,7)&&r.key<=end.slice(0,7)&&r.data.text);
 const moments=includeCouple?shared.filter(r=>r.kind==='rs'&&r.data.done&&r.data.doneDate>=start&&r.data.doneDate<=end):[];
 const registered=habits.reduce((sum,h)=>sum+h.totals.done,0),complete=habits.filter(h=>h.totals.target!==null&&h.totals.target>0&&h.totals.done>=h.totals.target).length;
 async function exportPDF(){setDownloading(true);setDownloadError('');try{const {downloadReportPDF}=await import('@/lib/report-pdf');downloadReportPDF({start,end,ideal:includeIdeal?ideal:'',purposes:purposes.map(p=>p.data.text),habits:habits.map(h=>({title:h.data.title,frequency:"Frecuencia actual: "+frequencyLabel(h.data.frequency),...h.totals})),notes:reflectionFields.flatMap(([key,category])=>chosen.filter(n=>n.data[key]?.trim()).map(n=>({date:n.data.start||n.key,text:n.data[key],category}))),moments:moments.map(r=>({date:r.data.doneDate,text:(R_TYPES.find(x=>x.id===r.data.type)?.title||'Encuentro')+(r.data.note?' · '+r.data.note:'')}))});}catch{setDownloadError('No se pudo preparar el PDF. Volvé a intentar.');}finally{setDownloading(false);}}
 return <section className="card report-card"><div className="journey-intro"><h2>{mode==='week'?'Esta semana':mode==='month'?'Este mes':mode==='year'?'Este año':'Período elegido'}</h2><p className="muted">Elegí el período y abrí solo el detalle que necesités.</p></div><ChoiceChips label="Período" value={mode} options={[["week","Semana"],["month","Mes"],["year","Año"],["custom","Fechas"]]} onChange={setMode}/>{mode==='custom'&&<div className="two-fields"><label>Desde<input type="date" value={custom.start} max={today} onChange={e=>setCustom({...custom,start:e.target.value})}/></label><label>Hasta<input type="date" value={custom.end} max={today} onChange={e=>setCustom({...custom,end:e.target.value})}/></label></div>}{valid?<><p className="muted journey-range">{prettyDate(start)} — {prettyDate(end)}</p><div className="journey-summary" aria-label="Resumen del período"><div><strong>{registered}</strong><span>registros</span></div><div><strong>{habits.length}</strong><span>compromisos</span></div><div><strong>{complete}</strong><span>metas completas</span></div></div>{!habits.length&&<p>Cuando registrés compromisos, aquí aparecerá una síntesis.</p>}<details className="journey-details"><summary>Ver compromiso por compromiso</summary>{habits.map(h=><div className="report-commitment" key={h.key}><div className="report-commitment-title"><h3>{h.data.title}</h3><span className="frequency-chip">{frequencyLabel(h.data.frequency)}</span></div><div className="report-numbers"><span><strong>{h.totals.done}</strong> registrados</span><span>{h.totals.target===null?(h.totals.knownTarget?`${h.totals.knownTarget} previstos + período parcial`:'Aún sin meta comparable'):<><strong>{h.totals.target}</strong> previstos</>}</span></div></div>)}</details><details className="journey-details"><summary>Ver mis reflexiones</summary><ReflectionSummary rows={own} start={start} end={end}/></details><div className="journey-actions"><button className="primary" onClick={()=>edit('review',start+':'+end,'Mi revisión del período',{start,end,gratitude:'',learning:'',next:''})}>Escribir mi revisión</button><button className="soft-button" onClick={()=>setOpen(true)}>Preparar reporte para mi asesor</button></div></>:<p role="alert">Revisá las fechas del período.</p>}
 <Dialog open={open&&valid} onOpenChange={setOpen}><DialogContent className="editor-dialog"><DialogTitle>Reporte para mi asesor</DialogTitle><DialogDescription>Elegí qué incluir y revisalo antes de descargar.</DialogDescription>{ideal&&<label className="member-choice"><input type="checkbox" checked={includeIdeal} onChange={e=>setIncludeIdeal(e.target.checked)}/>Incluir mi ideal</label>}{linked&&<label className="member-choice"><input type="checkbox" checked={includeCouple} onChange={e=>setIncludeCouple(e.target.checked)}/>Incluir nuestros registros matrimoniales</label>}{notes.length>0&&<div><h3>Notas para conversar</h3>{notes.map(n=>{const id=n.kind+':'+n.key;return <label key={id} className="report-note-option"><input type="checkbox" checked={selected.includes(id)} onChange={e=>setSelected(e.target.checked?[...selected,id]:selected.filter(x=>x!==id))}/><span><strong>{prettyDate(n.data.start||n.key)}</strong><span className="preserve">{textFor(n)}</span></span></label>;})}</div>}<article className="report-paper"><h2>Alianza · Mi recorrido</h2><p>{prettyDate(start)} — {prettyDate(end)}</p>{includeIdeal&&ideal&&<p>{ideal}</p>}{purposes.map(p=><p key={p.key}>{p.data.text}</p>)}<table><thead><tr><th>Compromiso</th><th>Previstos</th><th>Registrados</th></tr></thead><tbody>{habits.map(h=><tr key={h.key}><td>{h.data.title}</td><td>{h.totals.target??(h.totals.knownTarget?h.totals.knownTarget+' + parcial':'Parcial')}</td><td>{h.totals.done}</td></tr>)}</tbody></table><p className="form-hint">“Parcial”: período en curso, cambios de frecuencia o historia insuficiente. Los días sin registro no se cuentan como faltas.</p><ReflectionSummary rows={chosen} start={start} end={end}/>{chosen.filter(n=>n.kind!=='journal').map(n=><p key={n.kind+n.key} className="preserve">{prettyDate(n.data.start||n.key)}{'\n'}{textFor(n)}</p>)}{moments.map(r=><p key={r.key}>{prettyDate(r.data.doneDate)} · {r.data.note||R_TYPES.find(x=>x.id===r.data.type)?.title}</p>)}</article><button className="primary" disabled={downloading} onClick={exportPDF}><Download size={18}/>{downloading?'Preparando PDF…':'Descargar PDF'}</button>{downloadError&&<p role="alert">{downloadError}</p>}</DialogContent></Dialog></section>;
}
