import {useState} from 'react';
import {UserRound,Heart,Users,Plus,Check} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
export type Spaces={enabled:string[];start:string};
export function SpacesBar({value,onChange,config,onSave,busy,first=false}:{value:string;onChange:(v:string)=>void;config:Spaces;onSave:(v:Spaces)=>Promise<boolean>;busy:boolean;first?:boolean}){
 const [open,setOpen]=useState(false),[draft,setDraft]=useState(config),[error,setError]=useState('');
 const options=[{id:'personal',label:'Personal',hint:'Mi oración, ideal y compromisos',Icon:UserRound},{id:'couple',label:'Pareja',hint:'Nuestro ideal y las 4 Rs',Icon:Heart},{id:'group',label:'Cursos y grupos',hint:'Participar y organizar',Icon:Users}];
 return <><div className="space-switcher"><div className="space-buttons" role="group" aria-label="Espacio actual">{options.filter(o=>config.enabled.includes(o.id)).map(({id,label,Icon})=><button type="button" key={id} aria-pressed={value===id} onClick={()=>onChange(id)}><Icon size={20} aria-hidden="true"/><span>{label}</span></button>)}</div><button className="text-button" onClick={()=>{setDraft(config);setOpen(true);}}><Plus size={16}/>Mis espacios</button></div>
 <Dialog open={open||first} onOpenChange={setOpen}><DialogContent className="editor-dialog" showCloseButton={!first}><DialogTitle>{first?'¿Cómo querés usar Alianza?':'Mis espacios'}</DialogTitle><DialogDescription>Elegí uno o combiná varios. Podés cambiarlo después.</DialogDescription><div className="space-options">{options.map(({id,label,hint,Icon})=><button type="button" key={id} aria-pressed={draft.enabled.includes(id)} onClick={()=>setDraft(d=>{const enabled=d.enabled.includes(id)?d.enabled.filter(v=>v!==id):[...d.enabled,id];return{enabled,start:enabled.includes(d.start)?d.start:enabled[0]||''};})}><Icon size={24}/><span><strong>{label}</strong><small>{hint}</small></span>{draft.enabled.includes(id)&&<Check size={19}/>}</button>)}</div>{draft.enabled.length>1&&<fieldset className="space-default"><legend>Al abrir la app</legend><div className="space-buttons" role="group" aria-label="Espacio al abrir la app">{options.filter(o=>draft.enabled.includes(o.id)).map(({id,label})=><button type="button" key={id} aria-pressed={draft.start===id} onClick={()=>setDraft({...draft,start:id})}>{label}</button>)}</div></fieldset>}{error&&<p role="alert">{error}</p>}<button className="primary" disabled={busy||!draft.enabled.length} onClick={async()=>{setError('');if(await onSave(draft)){onChange(draft.start);setOpen(false);}else setError('No se guardó tu elección. Volvé a intentar.');}}>Guardar mis espacios</button></DialogContent></Dialog></>;
}
