import {useEffect,useRef,useState} from 'react';
import {SymbolProgress} from './symbol-progress';
import {BackButton} from './back-button';
import {SupportForm} from './pilot-support';
import {PersonalSymbol,PERSONAL_SYMBOLS} from './personal-symbol';
export type Appearance={symbol:string;image:string;progressStyle?:'fill'|'ring'};
export const emptyAppearance:Appearance={symbol:'',image:''};
// Only a re-encoded thumbnail is stored, not the original file or metadata.
export async function prepareSymbol(file:File,photo=false,crop?:{zoom:number;x:number;y:number}):Promise<string>{
 if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>5*1024*1024)throw new Error('Elegí un JPG, PNG o WebP de hasta 5 MB.');
 const url=URL.createObjectURL(file);
 try{const img=new Image();img.src=url;await img.decode();if(!img.naturalWidth||img.naturalWidth*img.naturalHeight>24000000)throw new Error('Esta imagen es demasiado grande. Elegí una más pequeña.');
 const c=document.createElement('canvas');const width=photo?800:192,height=photo?450:192;c.width=width;c.height=height;const ctx=c.getContext('2d');if(!ctx)throw new Error('No pudimos preparar la imagen.');ctx.fillStyle='#fff';ctx.fillRect(0,0,width,height);const ratio=crop?Math.max(width/img.naturalWidth,height/img.naturalHeight)*crop.zoom:Math.min(width/img.naturalWidth,height/img.naturalHeight);const w=img.naturalWidth*ratio,h=img.naturalHeight*ratio;ctx.drawImage(img,crop?(width-w)*crop.x/100:(width-w)/2,crop?(height-h)*crop.y/100:(height-h)/2,w,h);
 const image=c.toDataURL('image/jpeg',.7);if(image.length>(photo?180000:30000)||!image.startsWith('data:image/jpeg;base64,/9j/'))throw new Error('Probá con una imagen más sencilla.');return image;
 }finally{URL.revokeObjectURL(url);}
}
export function SymbolPicker({value,onChange,onBusy}:{value:Appearance;onChange:(v:Appearance)=>void;onBusy:(b:boolean)=>void}){
 const [error,setError]=useState(''),[processing,setProcessing]=useState(false),[file,setFile]=useState<File|null>(null),[crop,setCrop]=useState({zoom:1,x:50,y:50}),[preview,setPreview]=useState('');const generation=useRef(0);
 useEffect(()=>{onBusy(!!file||processing);return()=>onBusy(false);},[file,processing,onBusy]);
 useEffect(()=>{if(!file){setPreview('');return;}let active=true;prepareSymbol(file,false,crop).then(image=>{if(active)setPreview(image);}).catch(err=>{if(active)setError(err.message);});return()=>{active=false;};},[file,crop]);
 function choose(v:Appearance){generation.current++;setError('');setFile(null);onChange({...v,progressStyle:value.progressStyle??'fill'});}
 if(file)return <section className="s3-task s3-crop"><BackButton label="Volver sin cambiar la foto" onClick={()=>{setFile(null);setError('');}}/><h3>Acomodá tu imagen</h3>{preview&&<img className="s3-crop-photo" src={preview} alt="Encuadre de mi símbolo"/>}<label>Acercar<input type="range" min="1" max="3" step=".05" value={crop.zoom} onChange={e=>setCrop({...crop,zoom:Number(e.target.value)})}/></label><label>Posición horizontal<input type="range" min="0" max="100" value={crop.x} onChange={e=>setCrop({...crop,x:Number(e.target.value)})}/></label><label>Posición vertical<input type="range" min="0" max="100" value={crop.y} onChange={e=>setCrop({...crop,y:Number(e.target.value)})}/></label><button type="button" className="primary" disabled={!preview||processing} onClick={async()=>{setProcessing(true);onBusy(true);try{choose({symbol:'',image:await prepareSymbol(file,false,crop)});}catch(err){setError((err as Error).message);}finally{setProcessing(false);onBusy(false);}}}>Usar este encuadre</button>{error&&<p role="alert">{error}</p>}</section>;
 return <><div className="symbol-grid" role="group" aria-label="Elegir mi símbolo"><button type="button" aria-pressed={!value.symbol&&!value.image} onClick={()=>choose(emptyAppearance)}>Sin símbolo</button>{PERSONAL_SYMBOLS.map(([id,label])=><button type="button" key={id} aria-pressed={value.symbol===id&&!value.image} onClick={()=>choose({symbol:id,image:''})}><PersonalSymbol symbol={id}/><span>{label}</span></button>)}</div>
 <label className="s3-upload">Subir una imagen propia<input type="file" accept="image/png,image/jpeg,image/webp" disabled={processing} onChange={async e=>{const selected=e.target.files?.[0];e.target.value='';if(!selected)return;const token=++generation.current;setError('');setProcessing(true);onBusy(true);try{await prepareSymbol(selected);if(token===generation.current){setCrop({zoom:1,x:50,y:50});setFile(selected);}}catch(err){if(token===generation.current)setError((err as Error).message);}finally{setProcessing(false);onBusy(false);}}}/></label><small>JPG, PNG o WebP · hasta 5 MB. Se guarda una miniatura al tocar Guardar.</small>
 {(value.symbol||value.image)&&<><h3>Así se verá tu avance</h3><div className="s3-segments" role="group" aria-label="Estilo de avance">{(['fill','ring'] as const).map((style,i)=><button type="button" key={style} aria-pressed={(value.progressStyle??'fill')===style} onClick={()=>onChange({...value,progressStyle:style})}>{['Color gradual','Aro de avance'][i]}</button>)}</div><div className="s3-symbol-preview">{[0,50,100].map(n=><figure key={n}><SymbolProgress value={n} total={100} symbol={value.symbol} image={value.image} progressStyle={value.progressStyle}/><figcaption>{n}%</figcaption></figure>)}</div></>}
 {value.image&&<button type="button" className="action-button" data-action="secondary" onClick={()=>choose(emptyAppearance)}>Quitar imagen</button>}<details className="optional-details"><summary>Solicitar un símbolo</summary><SupportForm/></details>{processing&&<p role="status">Preparando imagen…</p>}{error&&<p role="alert">{error}</p>}</>;
}
