// Traditional public-domain prayer. Vatican Spanish text checked 2026-09-14,
// including Mother of mercy, Mother of hope and Solace of migrants.
export const LITANY_SOURCE='https://www.vatican.va/special/rosary/documents/litanie-lauretane_sp.html';
export const LITANY:{call:string;response:string}[]=[
 ...['Señor, ten piedad.','Cristo, ten piedad.','Señor, ten piedad.','Cristo, óyenos.','Cristo, escúchanos.'].map(call=>({call,response:''})),
 ...['Dios, Padre celestial','Dios, Hijo, Redentor del mundo','Dios, Espíritu Santo','Santísima Trinidad, un solo Dios'].map(call=>({call,response:'Ten piedad de nosotros.'})),
 ...['Santa María','Santa Madre de Dios','Santa Virgen de las Vírgenes','Madre de Cristo','Madre de la Iglesia','Madre de la misericordia','Madre de la divina gracia','Madre de la esperanza','Madre purísima','Madre castísima','Madre siempre virgen','Madre inmaculada','Madre amable','Madre admirable','Madre del buen consejo','Madre del Creador','Madre del Salvador','Virgen prudentísima','Virgen digna de veneración','Virgen digna de alabanza','Virgen poderosa','Virgen clemente','Virgen fiel','Espejo de justicia','Trono de la sabiduría','Causa de nuestra alegría','Vaso espiritual','Vaso digno de honor','Vaso de insigne devoción','Rosa mística','Torre de David','Torre de marfil','Casa de oro','Arca de la Alianza','Puerta del cielo','Estrella de la mañana','Salud de los enfermos','Refugio de los pecadores','Consuelo de los migrantes','Consoladora de los afligidos','Auxilio de los cristianos','Reina de los Ángeles','Reina de los Patriarcas','Reina de los Profetas','Reina de los Apóstoles','Reina de los Mártires','Reina de los Confesores','Reina de las Vírgenes','Reina de todos los Santos','Reina concebida sin pecado original','Reina asunta a los Cielos','Reina del Santísimo Rosario','Reina de la familia','Reina de la paz'].map(call=>({call,response:'Ruega por nosotros.'})),
 ...['Perdónanos, Señor.','Escúchanos, Señor.','Ten misericordia de nosotros.'].map(response=>({call:'Cordero de Dios, que quitas el pecado del mundo',response})),
 {call:'Ruega por nosotros, Santa Madre de Dios.',response:'Para que seamos dignos de las promesas de Cristo.'},
 {call:'Oración',response:'Te rogamos nos concedas, Señor Dios nuestro, gozar de continua salud de alma y cuerpo, y por la gloriosa intercesión de la bienaventurada siempre Virgen María, vernos libres de las tristezas de la vida presente y disfrutar de las alegrías eternas. Por Cristo nuestro Señor. Amén.'},
];
