import React,{useEffect,useState} from 'react';
import type {SupabaseClient} from '@supabase/supabase-js';
export type Activity={startedOn:string;asOf:string;couples:number;accounts:number;activated:number;active7:number;active30:number;members:{email:string;activated:boolean;lastDay:string|null;days7:number;days30:number}[]};
const date=(v:string)=>new Date(v+'T12:00:00').toLocaleDateString('es-CR',{day:'numeric',month:'short',year:'numeric'});
export function AdminPanel({client,onBack}:{client:SupabaseClient;onBack:()=>void}){
 const [data,setData]=useState<Activity|null>(null),[busy,setBusy]=useState(true),[error,setError]=useState('');
 useEffect(()=>{let active=true;setBusy(true);setData(null);client.rpc('alianza_admin_activity').then(({data,error})=>{if(!active)return;setBusy(false);if(error)setError(error.code==='42501'?'Esta cuenta no tiene acceso de administrador.':'No se pudo cargar la actividad. Volvé a intentar.');else setData(data);});return()=>{active=false;};},[client]);
 async function refresh(){setBusy(true);setError('');setData(null);const {data,error}=await client.rpc('alianza_admin_activity');setBusy(false);if(error)setError('No se pudo cargar la actividad o ya no tenés acceso.');else setData(data);}
 return <main className="admin-page"><header><button className="text-button" onClick={onBack}>← Volver a mi espacio</button><h1>Administración del piloto</h1><p>Actividad de uso de Alianza</p></header><section className="admin-privacy"><strong>El contenido personal queda fuera de este panel.</strong><p>Solo se muestra el estado de acceso y los días en que cada cuenta abrió la app. Tu horario y lo que Neca comparta con vos siguen en tu espacio personal.</p></section><button className="primary" onClick={refresh} disabled={busy}>{busy?'Cargando…':'Actualizar actividad'}</button>{error&&<p role="alert" className="notice">{error}</p>}{data&&<><section className="admin-stats" aria-label="Resumen del piloto">{[['Parejas',data.couples],['Cuentas invitadas',data.accounts],['Cuentas activadas',data.activated],['Activas en 7 días',data.active7],['Activas en 30 días',data.active30]].map(([label,value])=><div key={label}><strong>{value}</strong><span>{label}</span></div>)}</section><h2>Acceso y actividad</h2><p className="admin-caption">Conteo desde el {date(data.startedOn)}. Días calendario de Costa Rica, incluido hoy. Abrir la app no indica haber cumplido compromisos.</p><div className="admin-members">{data.members.map(m=><article key={m.email}><h3>{m.email}</h3><span className="admin-state">{m.activated?'Cuenta activada':'Pendiente de activar'}</span><dl><div><dt>Último día de uso</dt><dd>{m.lastDay?date(m.lastDay):'Sin actividad registrada'}</dd></div><div><dt>Días de uso · últimos 7</dt><dd>{m.days7}</dd></div><div><dt>Días de uso · últimos 30</dt><dd>{m.days30}</dd></div></dl></article>)}</div><p className="admin-caption">No se muestran textos, compromisos, marcas, reflexiones, ideales, configuraciones de privacidad ni detalles de las 4 Rs.</p></>}</main>;
}
export function UserEnvironment({client,userId,children}:{client:SupabaseClient;userId:string;children:React.ReactNode}){
 const [admin,setAdmin]=useState(false),[show,setShow]=useState(false);
 useEffect(()=>{let active=true;client.rpc('alianza_is_admin').then(({data,error})=>{if(active)setAdmin(!error&&data===true);});
 const record=()=>{if(document.visibilityState==='visible')void client.rpc('alianza_record_activity').then(()=>{});};record();document.addEventListener('visibilitychange',record);
 return()=>{active=false;document.removeEventListener('visibilitychange',record);};},[client,userId]);
 return <>{show&&<AdminPanel client={client} onBack={()=>setShow(false)}/>}<div hidden={show}>{admin&&<div className="admin-entry"><button onClick={()=>setShow(true)}>Administrar piloto</button></div>}{children}<details className="activity-disclosure"><summary>Privacidad y actividad del piloto</summary><p>El administrador puede ver tu correo, si activaste tu cuenta y los días en que abriste Alianza. Esta medición comienza con esta versión; no incluye horarios exactos ni qué hiciste dentro de la app.</p><p>El panel de administración no puede consultar tus compromisos, reflexiones o registros de las 4 Rs. Compartir contenido personal sigue siendo una decisión tuya, únicamente con tu pareja.</p></details></div></>;
}
