import {useEffect,useState} from 'react';
import type {SupabaseClient} from '@supabase/supabase-js';
type Summary={asOf:string;consenting:number;active7:number;active30:number;totals30:Record<string,{count:number;people:number}>};
export function PilotPanel({client}:{client:SupabaseClient}){
 const [data,setData]=useState<Summary|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function refresh(){setData(null);setBusy(true);setError('');try{const r=await client.rpc('alianza_admin_pilot');if(r.error||!r.data)throw Error();setData(r.data);}catch{setError('No se pudo cargar el piloto o ya no tenés acceso.');}finally{setBusy(false);}}
 useEffect(()=>{void refresh();},[client]);
 const features=[['view_day','Compromisos del día'],['view_week','Metas semanales'],['view_month','Metas mensuales'],['view_review','Revisión del mes'],['view_history','Mi recorrido y reporte'],['view_prayer','Oración'],['view_groups','Cursos y grupos'],['view_personal','Mi espacio'],['view_couple','Pareja']];
 return <section className="card"><h2>Piloto cercano</h2><p>Actividad agregada de quienes aceptaron esta medición, aunque sean menos de cinco.</p><button className="soft-button" disabled={busy} onClick={refresh}>{busy?'Cargando piloto…':'Actualizar piloto'}</button>{error&&<p role="alert">{error}</p>}{data&&<><div className="admin-stats"><div><strong>{data.consenting}</strong><span>Participan en la medición</span></div><div><strong>{data.active7}</strong><span>Activos en 7 días</span></div><div><strong>{data.active30}</strong><span>Activos en 30 días</span></div></div>{data.consenting===0?<p>Para empezar, cada participante activa «Participar en el piloto cercano» en Ayudar a mejorar Alianza. No se reconstruye su actividad anterior.</p>:<><h3>Funciones utilizadas · últimos 30 días</h3><table><thead><tr><th>Función</th><th>Personas</th><th>Días de uso sumados</th></tr></thead><tbody>{features.map(([event,label])=><tr key={event}><td>{label}</td><td>{data.totals30[event]?.people??0}</td><td>{data.totals30[event]?.count??0}</td></tr>)}</tbody></table><h3>Funcionamiento</h3><div className="admin-stats">{[['save_ok','Guardados correctos'],['save_error','Errores al guardar'],['load_ok','Cargas correctas'],['load_error','Errores al cargar'],['slow_load','Cargas de más de 3 segundos']].map(([event,label])=><div key={event}><strong>{data.totals30[event]?.count??0}</strong><span>{label}</span></div>)}</div><p>Una función cuenta una vez por persona y día. Los guardados cuentan solicitudes, no compromisos cumplidos. Cero significa sin eventos recibidos; no garantiza ausencia de uso o errores sin conexión.</p></>}<p>Sin nombres, correos, fichas individuales ni textos. En un grupo pequeño estas cifras pueden permitir deducciones; no se presentan como anónimas. Son señales descriptivas para orientar conversaciones, no conclusiones estadísticas.</p></>}</section>;
}
