import {useEffect,useRef,useState} from 'react';
import type {SupabaseClient} from '@supabase/supabase-js';
import {supportStates,type SupportRequest} from '../app/pilot-support';
export function SupportAdmin({client}:{client:SupabaseClient}){
 const [requests,setRequests]=useState<SupportRequest[]>([]),[filter,setFilter]=useState('pending'),[busy,setBusy]=useState(false),[error,setError]=useState('');const epoch=useRef(0);
 async function load(){const n=++epoch.current;setBusy(true);setRequests([]);setError('');try{const r=await client.rpc('alianza_pilot_support',{p:{action:'list'}});if(r.error)throw r.error;if(n===epoch.current)setRequests(r.data.requests);}catch{if(n===epoch.current)setError('No pudimos cargar las solicitudes o ya no tenés acceso.');}finally{if(n===epoch.current)setBusy(false);}}
 useEffect(()=>{void load();return()=>{epoch.current++;};},[client]);
 async function update(r:SupportRequest,state:string){setBusy(true);setError('');const result=await client.rpc('alianza_pilot_support',{p:{action:'update',id:r.id,version:r.version,state}});if(result.error){setError('No se guardó el cambio. Actualizá para revisar el estado más reciente.');setBusy(false);}else await load();}
 return <section><h2>Solicitudes y mejoras</h2><p>Mensajes enviados expresamente al administrador.</p><div className="invitation-filters"><label>Estado de solicitudes<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Todas</option>{Object.entries(supportStates).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><button disabled={busy} onClick={()=>void load()}>Actualizar solicitudes</button></div>{error&&<p role="alert">{error}</p>}<ul className="invitation-list">{requests.filter(r=>filter==='all'||r.state===filter).map(r=><li key={r.id}><strong>{r.message}</strong><span>{r.email}</span><span>{supportStates[r.state]}</span><div>{Object.entries(supportStates).filter(([k])=>k!==r.state).map(([k,v])=><button disabled={busy} key={k} onClick={()=>void update(r,k)}>{v}</button>)}</div></li>)}</ul>{!busy&&!error&&!requests.some(r=>filter==='all'||r.state===filter)&&<p>No hay solicitudes en este estado.</p>}</section>;
}
