import React, {useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Heart, TreeDeciduous, Cross, Sun, Moon, Star, Flame, Anchor, Leaf, Flower2, Mountain, Compass, Sprout, HandHeart, Church, BookOpen, Home, CalendarDays, UserRound, ChevronRight, Check, ArrowLeft, CircleHelp, LockKeyhole, X, Plus} from 'lucide-react';
import {R_TYPES} from '../lib/domain';

// Review-only prototype: all information is synthetic and held in memory.
// There are deliberately no API, storage, authentication or email calls.
type Focus='schedule'|'rs'|'ideal';
type Screen='welcome'|'setup'|'success'|'home'|'schedule'|'rs'|'profile'|'ideal'|'pair'|'pairIdeal'|'help'|'news';
type Habit={id:number;title:string;frequency:'daily'|'weekly';target:number;anchor:string;minimum:string;active:boolean;checks:Record<string,string>;notes:Record<string,string>};
type Person={name:string;focus:Focus|null;symbol:string;ideal:string;idealStatus:string;idealNotes:string[];shareSchedule:boolean;shareNotes:boolean;habits:Habit[];purposes:Record<string,string>;reviews:Record<string,string>;notes:Record<string,string>;seen:boolean;quiet:boolean};
type Pair={status:'none'|'pending'|'linked';email:string;sender:0|1;ideal:string;idealStatus:string;ideas:string[];confirmed:boolean[];events:Record<string,{note:string;date:string;done:boolean}>};
const TODAY='2026-09-12';
const symbols=[['heart','Corazón',Heart],['tree','Árbol',TreeDeciduous],['rosary','Rosario',null],['cross','Cruz',Cross],['sun','Sol',Sun],['moon','Luna',Moon],['star','Estrella',Star],['flame','Llama',Flame],['anchor','Ancla',Anchor],['leaf','Hoja',Leaf],['flower','Flor',Flower2],['mountain','Montaña',Mountain],['compass','Brújula',Compass],['sprout','Brote',Sprout],['hands','Manos y corazón',HandHeart],['church','Santuario',Church]] as const;
function Symbol({id,size=23}:{id:string;size?:number}){const Icon=symbols.find(s=>s[0]===id)?.[2]||Heart;return id==='rosary'?<svg width={size} height={size} viewBox="0 0 24 28" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true"><ellipse cx="12" cy="9" rx="7" ry="7" strokeDasharray="1 4" strokeLinecap="round"/><path d="M12 16v10m-3-4h6"/></svg>:<Icon size={size} aria-hidden="true"/>;}
function person(name:string):Person{return{name,focus:null,symbol:'heart',ideal:'',idealStatus:'none',idealNotes:['','',''],shareSchedule:false,shareNotes:false,habits:[],purposes:{},reviews:{},notes:{},seen:false,quiet:false};}
function pair():Pair{return{status:'none',email:'',sender:0,ideal:'',idealStatus:'none',ideas:['','',''],confirmed:[false,false],events:{}};}
function newHabit():Habit{return{id:Date.now(),title:'',frequency:'daily',target:3,anchor:'',minimum:'',active:true,checks:{},notes:{}};}
function weekStart(date:string){const d=new Date(date+'T12:00:00Z');d.setUTCDate(d.getUTCDate()-(d.getUTCDay()+6)%7);return d.toISOString().slice(0,10);}
function shift(date:string,n:number){const d=new Date(date+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10);}
function shortDate(d:string){return new Intl.DateTimeFormat('es-CR',{day:'numeric',month:'short',timeZone:'UTC'}).format(new Date(d+'T12:00:00Z'));}
function weekCount(h:Habit,date:string){const start=weekStart(date);return Object.entries(h.checks).filter(([d,v])=>d>=start&&d<=shift(start,6)&&v==='done').length;}
const focusCopy={schedule:['Mi horario espiritual','Cuidar un compromiso personal y seguirlo a mi ritmo.'],rs:['Las cuatro Rs','Preparar un momento para cuidar nuestra vida de pareja.'],ideal:['Mi ideal personal','Escribirlo con mis palabras o comenzar a discernirlo.']};
const personalQuestions=['¿Qué cualidades o dones reconocés en vos y en qué momentos aparecen?','¿Qué experiencias, personas o llamados se repiten en tu historia?','¿Cómo te gustaría responder a Dios y servir a otros con esos dones?'];
const pairQuestions=['¿Qué dones reconocemos en nuestra historia como pareja?','¿Qué valores y experiencias queremos cuidar juntos?','¿Qué sentimos que podemos aportar a nuestra familia y a otros?'];
function Button({children,onClick,soft=false,disabled=false,type='button'}:any){return <button type={type} className={soft?'a-soft':'a-primary'} onClick={onClick} disabled={disabled}>{children}</button>;}
function Help({children,title='¿Necesitás una guía?'}:any){return <details className="a-help"><summary><CircleHelp size={17}/>{title}</summary><div>{children}</div></details>;}
function Card({children,className=''}:any){return <section className={'a-card '+className}>{children}</section>;}

function App(){
 const [people,setPeople]=useState<[Person,Person]>([person(''),person('Luis')]);
 const [who,setWho]=useState<0|1>(0),[couple,setCouple]=useState<Pair>(pair()),[archives,setArchives]=useState<Pair[]>([]);
 const [screen,setScreen]=useState<Screen>('welcome'),[view,setView]=useState('day'),[focus,setFocus]=useState<Focus>('schedule');
 const [editHabit,setEditHabit]=useState<Habit|null>(null),[editNote,setEditNote]=useState<{id:number;date:string;text:string}|null>(null);
 const [date,setDate]=useState(TODAY),[month,setMonth]=useState('2026-09');
 const [name,setName]=useState(''),[mode,setMode]=useState('individual'),[message,setMessage]=useState('');
 const [ideal,setIdeal]=useState(''),[idealStatus,setIdealStatus]=useState('none'),[ideas,setIdeas]=useState(['','','']),[guideStep,setGuideStep]=useState(0);
 const [email,setEmail]=useState(''),[selectedR,setSelectedR]=useState(''),[rDate,setRDate]=useState(TODAY),[rNote,setRNote]=useState(''),[rDone,setRDone]=useState(false);
 const [purpose,setPurpose]=useState(''),[review,setReview]=useState(''),[editingMonth,setEditingMonth]=useState<'purpose'|'review'|null>(null);
 const [confirm,setConfirm]=useState<'unlink'|'cancelInvite'|null>(null),[growth,setGrowth]=useState(''),[sample,setSample]=useState('new');
 const p=people[who],other=people[who===0?1:0],linked=couple.status==='linked';
 const update=(patch:Partial<Person>)=>setPeople(prev=>prev.map((x,i)=>i===who?{...x,...patch}:x) as [Person,Person]);
 const say=(text:string)=>setMessage(text);
 const go=(s:Screen)=>{setScreen(s);setMessage('');setEditingMonth(null);setSelectedR('');setGrowth('');};
 const active=p.habits.filter(h=>h.active);
 const saveHabit=(h:Habit)=>{update({habits:p.habits.some(x=>x.id===h.id)?p.habits.map(x=>x.id===h.id?h:x):[...p.habits,h]});setEditHabit(null);say('Compromiso guardado. Podés retomarlo en Horario.');};
 const mark=(h:Habit,status:string)=>{const checks={...h.checks};if(status)checks[date]=status;else delete checks[date];update({habits:p.habits.map(x=>x.id===h.id?{...x,checks}:x)});say(status==='done'?'Registro guardado.':status==='missed'?'Registrado. Podés anotar qué te costó.':'Registro actualizado.');};
 const openIdeal=(married=false)=>{setIdeal(married?couple.ideal:p.ideal);setIdealStatus(married?couple.idealStatus:p.idealStatus);setIdeas([...(married?couple.ideas:p.idealNotes)]);setGuideStep(0);go(married?'pairIdeal':'ideal');};
 function scenario(value:string){
  setSample(value);setWho(0);setArchives([]);setMessage('');setEditingMonth(null);setEditHabit(null);setEditNote(null);setSelectedR('');setGrowth('');setConfirm(null);setMonth('2026-09');setDate(TODAY);
  const a=person('Ana'),b=person('Luis');const c=pair();
  if(value==='new'){setPeople([person(''),b]);setCouple(c);setScreen('welcome');return;}
  a.focus='schedule';a.seen=value!=='returning';
  const h={...newHabit(),id:1,title:'Hacer ejercicio',frequency:'weekly' as const,target:3,anchor:'Después del trabajo',minimum:'Diez minutos de caminata'};
  h.checks={'2026-08-03':'done','2026-08-05':'done','2026-08-07':'done','2026-08-10':'done','2026-08-12':'missed','2026-08-14':'done','2026-09-07':'done','2026-09-09':'done','2026-09-11':'done'};
  h.notes={'2026-08-12':'La hora de salida del trabajo me dificultó comenzar.'};a.habits=[h];a.purposes={'2026-08':'Cuidar mi salud con un ritmo que pueda sostener.'};a.reviews={'2026-08':'Me ayudó dejar la ropa preparada. Quiero probar una hora más temprana.'};
  if(value==='ready'){for(let w=1;w<=4;w++)for(const d of[0,2,4])h.checks[shift('2026-09-07',-7*w+d)]='done';}
  if(value==='paused'){a.habits=[{...h,checks:{'2026-08-03':'done'}}];}
  if(value==='pair'){c.status='linked';b.focus='rs';b.seen=true;a.focus='rs';}
  if(value==='invite'){c.status='pending';c.sender=0;c.email='luis@example.test';}
  setPeople([a,b]);setCouple(c);setScreen(value==='month'?'schedule':value==='pair'?'rs':value==='invite'?'pair':'home');setView(value==='month'?'month':'day');
 }
 function start(f:Focus){setFocus(f);setName(p.name);setMode(linked?'couple':'individual');setIdeal(p.ideal);setIdealStatus(p.idealStatus);setIdeas([...p.idealNotes]);setGuideStep(0);setSelectedR('rezar');setRDate(TODAY);setRNote('');setRDone(false);if(f==='schedule')setEditHabit(newHabit());go('setup');}
 function finish(h?:Habit){update({name:name.trim()||p.name||'Mi espacio',focus,seen:true,...(h?{habits:[...p.habits,h]}:{}),...(focus==='ideal'?{ideal,idealStatus,idealNotes:ideas}:{}),...(focus==='rs'?{notes:{...p.notes,rs:rNote}}:{})});setEditHabit(null);setScreen('success');}
 function saveR(){const r=R_TYPES.find(x=>x.id===selectedR)!;const key=r.id+':'+(r.id==='rezar'?rDate:r.id==='reencantar'?weekStart(rDate):r.id==='revisar'?rDate.slice(0,7):rDate.slice(0,4));setCouple({...couple,events:{...couple.events,[key]:{date:rDate,note:rNote,done:rDone}}});setSelectedR('');say('Encuentro guardado en el espacio compartido.');}
 const isFirst=screen==='welcome'||screen==='setup'||screen==='success';
 const mainTab=screen==='schedule'?'schedule':screen==='rs'||screen==='pairIdeal'?'rs':['profile','ideal','pair','news','help'].includes(screen)?'profile':'home';
 const modal=editHabit&&screen!=='setup'||editNote||confirm;
 const continuity=active.some(h=>[1,2,3,4].every(w=>{const d=shift(TODAY,-7*w);return weekCount(h,d)>=(h.frequency==='weekly'?h.target:5);}));
 const lastCheck=p.habits.flatMap(h=>Object.keys(h.checks)).sort().at(-1);
 const pause=!!lastCheck&&lastCheck<shift(TODAY,-14);
 const header=(eyebrow:string,title:string,description?:string)=><div className="a-heading"><p className="a-eyebrow">{eyebrow}</p><h1>{title}</h1>{description&&<p>{description}</p>}</div>;
 function idealFields(married:boolean){return <>
  <label>{married?'¿Dónde están con su ideal matrimonial?':'¿Ya tenés un ideal personal?'}<select value={idealStatus} onChange={e=>setIdealStatus(e.target.value)}><option value="none">{married?'Todavía no tenemos uno':'Todavía no tengo uno'}</option><option value="draft">{married?'Estamos discerniéndolo':'Estoy discerniéndolo'}</option><option value="defined">{married?'Ya tenemos uno':'Ya tengo uno'}</option></select></label>
  {idealStatus!=='none'&&<label>{idealStatus==='draft'?'Una frase en borrador':married?'Nuestro ideal matrimonial':'Mi ideal personal'}<textarea aria-label={idealStatus==='draft'?'Una frase en borrador':married?'Nuestro ideal matrimonial':'Mi ideal personal'} rows={3} maxLength={200} value={ideal} onChange={e=>setIdeal(e.target.value)} placeholder={married?'Una expresión que los represente a ambos':'Escribilo con tus propias palabras'}/></label>}
  <Help title={married?'Una guía para discernir juntos':'Una guía para descubrir mi ideal'}><p>Estas preguntas son un apoyo inicial. El discernimiento puede llevar tiempo; conviene trabajarlo con acompañamiento del Movimiento.</p><p className="a-eyebrow">PREGUNTA {guideStep+1} DE 3 · OPCIONAL</p><label>{(married?pairQuestions:personalQuestions)[guideStep]}<textarea rows={4} value={ideas[guideStep]} onChange={e=>setIdeas(ideas.map((x,i)=>i===guideStep?e.target.value:x))}/></label><div className="a-actions"><Button soft disabled={guideStep===0} onClick={()=>setGuideStep(guideStep-1)}>Anterior</Button><Button soft disabled={guideStep===2} onClick={()=>setGuideStep(guideStep+1)}>Siguiente</Button></div><p>Podés guardar una sola respuesta y retomar otro día.</p></Help>
 </>;}
 function habitFields(h:Habit,set:(h:Habit)=>void){return <>
  <label>¿Qué compromiso querés cuidar?<input required maxLength={180} value={h.title} onChange={e=>set({...h,title:e.target.value})} placeholder="Por ejemplo: hacer ejercicio"/></label>
  <label>¿Con qué frecuencia?<select value={h.frequency} onChange={e=>set({...h,frequency:e.target.value as Habit['frequency']})}><option value="daily">Cada día</option><option value="weekly">Varias veces por semana</option></select></label>
  {h.frequency==='weekly'&&<label>Días por semana<select value={h.target} onChange={e=>set({...h,target:Number(e.target.value)})}>{[1,2,3,4,5,6,7].map(n=><option key={n} value={n}>{n} {n===1?'día':'días'}</option>)}</select></label>}
  <Help title="Una ayuda para sostenerlo"><label>Lo haré después de…<input maxLength={240} value={h.anchor} onChange={e=>set({...h,anchor:e.target.value})} placeholder="Un momento conocido de mi día"/></label><label>Si el día se complica, puedo…<input maxLength={240} value={h.minimum} onChange={e=>set({...h,minimum:e.target.value})} placeholder="Mi versión más pequeña"/></label></Help>
 </>;}
 function rEditor(){const r=R_TYPES.find(x=>x.id===selectedR);if(!r)return null;return <Card><h2>{r.title} juntos</h2><p className="a-scope"><Heart size={16}/>Compartido con {other.name}</p><form onSubmit={e=>{e.preventDefault();saveR();}}><label>¿Cuándo quieren vivirlo?<input required type="date" value={rDate} onChange={e=>setRDate(e.target.value)}/></label><Help title="Ideas para este encuentro"><p>{r.suggestion}</p>{r.prompts.map(x=><p key={x}>{x}</p>)}</Help><label>Una reflexión o un acuerdo (opcional)<textarea rows={3} value={rNote} onChange={e=>setRNote(e.target.value)}/></label><label className="a-checkbox"><input type="checkbox" checked={rDone} onChange={e=>setRDone(e.target.checked)}/>Ya vivimos este momento</label>{rDone&&rDate>TODAY&&<p role="alert">Un encuentro vivido debe tener fecha de hoy o anterior.</p>}<div className="a-actions"><Button soft onClick={()=>setSelectedR('')}>Cerrar</Button><Button type="submit" disabled={rDone&&rDate>TODAY}>Guardar encuentro</Button></div></form></Card>;}
 return <div className="a-review">
  <div className="a-reviewbar"><label>Prueba de navegación · datos de ejemplo<select aria-label="Escenario de prueba" value={sample} onChange={e=>scenario(e.target.value)}><option value="new">Primera visita</option><option value="returning">Usuario actual y novedades</option><option value="month">Revisión mensual</option><option value="ready">Continuidad y siguiente práctica</option><option value="paused">Volver después de una pausa</option><option value="invite">Invitación pendiente</option><option value="pair">Pareja sin ideal matrimonial</option></select></label><label>Cuenta de prueba<select aria-label="Cuenta de prueba" value={who} onChange={e=>{setWho(Number(e.target.value) as 0|1);setEditHabit(null);setEditNote(null);setConfirm(null);go(couple.status==='pending'?'pair':'home');}}><option value={0}>{people[0].name||'Persona 1'}</option><option value={1}>Luis</option></select></label></div>
  <div className="a-product"><header className="a-top"><div className="a-brand"><img src="__EMBLEM_DATA__" alt="Árbol y rosario"/><div>Alianza<small>FE Y AMOR</small></div></div><button className="a-icon" aria-label="Abrir ayuda" onClick={()=>go('help')}><CircleHelp size={23}/></button></header>
  <main aria-label="Aplicación Alianza">
   {message&&<div className="a-message" role="status">{message}<button className="a-icon" onClick={()=>setMessage('')} aria-label="Cerrar aviso"><X size={17}/></button></div>}
   {screen==='welcome'&&<>{header('UN COMIENZO A TU MEDIDA','¿Qué te ayudaría más hoy?','Elegí un espacio para comenzar. Los demás estarán disponibles cuando los necesités.')}<div className="a-choices">{(['schedule','rs','ideal'] as Focus[]).map((f,i)=><button className="a-choice" key={f} onClick={()=>start(f)}>{i===0?<CalendarDays/>:i===1?<Heart/>:<Compass/>}<span><strong>{focusCopy[f][0]}</strong><span>{focusCopy[f][1]}</span></span><ChevronRight size={20}/></button>)}</div><p className="a-small a-center">Podés usar Alianza individualmente y vincularte en pareja después.</p></>}
   {screen==='setup'&&<><button className="a-back" onClick={()=>{setEditHabit(null);go('welcome');}}><ArrowLeft size={17}/>Elegir otro comienzo</button>{header('TU PRIMER PASO',focusCopy[focus][0])}<form onSubmit={e=>{e.preventDefault();if(focus==='schedule'&&editHabit){if(editHabit.title.trim())finish(editHabit);}else finish();}}>
    <label>¿Cómo querés que te llamemos? (opcional)<input maxLength={60} value={name} onChange={e=>setName(e.target.value)} placeholder="Tu nombre"/></label>
    {focus==='schedule'&&editHabit&&habitFields(editHabit,setEditHabit)}
    {focus==='ideal'&&idealFields(false)}
    {focus==='rs'&&<><p>Las cuatro Rs cuidan la vida de pareja: rezar, reencantar, revisar y renovar. Podés empezar preparando un solo momento.</p><label>¿Cómo querés comenzar?<select value={mode} onChange={e=>setMode(e.target.value)}><option value="individual">Preparar mi espacio primero</option><option value="couple">Vincularme con mi pareja</option></select></label><label>Una idea para nuestro primer momento<textarea required rows={3} value={rNote} onChange={e=>setRNote(e.target.value)} placeholder="Por ejemplo: conversar después de cenar el domingo"/></label><p className="a-muted">Esta idea queda en tu espacio personal. Cada persona conserva su cuenta y la vinculación requiere la aceptación de ambos.</p><Help title="¿Y si no tenemos ideal matrimonial?"><p>Pueden usar las cuatro Rs desde ahora. El ideal matrimonial tiene un espacio opcional para escribirlo o discernirlo juntos.</p></Help></>}
    <Button type="submit">{focus==='rs'?'Continuar':focus==='ideal'&&idealStatus==='none'&&!ideas.some(Boolean)?'Continuar a mi espacio':'Guardar mi primer paso'}</Button>
   </form></>}
   {screen==='success'&&<><div className="a-success"><Check size={32}/></div>{header('A TU RITMO',focus==='rs'?'Comencemos juntos.':focus==='ideal'&&!p.ideal&&!p.idealNotes.some(Boolean)?'Tu espacio está listo.':'Ya tenés por dónde empezar.',focus==='schedule'?'Tu compromiso quedó guardado. En Horario podés marcarlo cuando lo vivás.':focus==='ideal'?'Podés volver a tu ideal desde Inicio o Mi espacio.':'Podés vincularte ahora o preparar una idea personal mientras tanto.')}<Button onClick={()=>go(focus==='rs'&&mode==='couple'?'pair':'home')}>{focus==='rs'&&mode==='couple'?'Vincularme con mi pareja':'Ir a mi inicio'}</Button><p className="a-small">No hace falta completar nada más ahora.</p></>}
   {screen==='home'&&<>{header('TU ESPACIO',p.name&&p.name!=='Mi espacio'?`Hola, ${p.name}.`:'Un paso a tu ritmo.','Retomá lo que elegiste cuidar.')}
    {!p.seen&&p.focus&&<Card className="a-news"><p className="a-eyebrow">NOVEDADES</p><h2>Ahora es más fácil retomar.</h2><p>Hoy se llama Horario. El propósito y la revisión mensual están juntos en Horario → Mi mes. Tus registros se conservan.</p><div className="a-actions"><Button soft onClick={()=>go('news')}>Ver qué cambió</Button><Button onClick={()=>update({seen:true})}>Entendido</Button></div></Card>}
    {couple.status==='pending'&&couple.sender!==who&&<Card><h2>Tenés una invitación de {other.name||'tu pareja'}</h2><Button onClick={()=>go('pair')}>Revisar invitación</Button></Card>}
    {pause&&<Card><h2>Podés retomar desde hoy.</h2><p>Tu historia sigue aquí. Elegí continuar o ajustar el compromiso para que te resulte más llevadero.</p><Button soft onClick={()=>{go('schedule');setView('day');}}>Retomar mi horario</Button></Card>}
    {!p.focus&&<Card><h2>Elegí lo que más te ayude.</h2><Button onClick={()=>go('welcome')}>Elegir mi comienzo</Button></Card>}
    {p.focus==='schedule'&&<Card><span className="a-kicker">MI HORARIO ESPIRITUAL</span><h2>{active[0]?.title||'Un compromiso a mi medida'}</h2>{active[0]&&<p>{active[0].frequency==='weekly'?`${weekCount(active[0],TODAY)} de ${active[0].target} días registrados esta semana`:'Un momento personal cada día'}</p>}<Button onClick={()=>{go('schedule');setView('day');}}>Abrir mi horario</Button></Card>}
    {p.focus==='ideal'&&<Card><Symbol id={p.symbol}/><h2>{p.idealStatus==='draft'?'Mi ideal en discernimiento':'Mi ideal personal'}</h2><p>{p.ideal||'Un espacio para descubrir lo que da sentido a mi entrega.'}</p><Button onClick={()=>openIdeal()}>Retomar mi ideal</Button></Card>}
    {p.focus==='rs'&&<Card><Heart/><h2>{linked?'Un momento para nosotros':'Preparar nuestro primer momento'}</h2><p>{linked?'Elegí una R y preparen un encuentro a su ritmo.':'Podés anotar una idea propia mientras tu pareja se vincula.'}</p><Button onClick={()=>go('rs')}>Abrir las cuatro Rs</Button></Card>}
    {continuity&&!p.quiet&&<Card><h2>¿Cómo te está resultando?</h2>{!growth?<><p>Tenés continuidad en tus registros. ¿Sentís que este ritmo es llevadero?</p><Button soft onClick={()=>setGrowth('ready')}>Sí, me resulta llevadero</Button><Button soft onClick={()=>setGrowth('hard')}>Todavía me cuesta</Button></>:growth==='ready'?<><p>Podés seguir así o explorar una nueva práctica.</p><Button onClick={()=>{update({quiet:true});go('welcome');}}>Explorar otra práctica</Button><Button soft onClick={()=>update({quiet:true})}>Seguir como estoy</Button></>:<><p>Podemos ajustar lo actual para que sea más sencillo.</p><Button onClick={()=>{update({quiet:true});setEditHabit({...active[0]});}}>Ajustar mi compromiso</Button></>}<button className="a-link" onClick={()=>update({quiet:true})}>Ahora no</button></Card>}
    <button className="a-link" onClick={()=>go('welcome')}>Explorar los otros espacios</button>
   </>}
   {screen==='schedule'&&<>{header('MI HORARIO ESPIRITUAL','Un ritmo que pueda sostener.')}<div className="a-segments" role="group" aria-label="Vista del horario">{[['day','Mi día'],['month','Mi mes'],['history','Historial']].map(([v,t])=><button key={v} aria-pressed={view===v} onClick={()=>{setView(v);setEditingMonth(null);}}>{t}</button>)}</div>
    {view==='day'&&<><label className="a-date">Fecha del registro<input type="date" max={TODAY} value={date} onChange={e=>setDate(e.target.value||TODAY)}/></label>{active.length===0?<Card><h2>Empezá con un compromiso.</h2><p>Elegí algo que ya practicás o que querés comenzar a cuidar.</p><Button onClick={()=>setEditHabit(newHabit())}>Crear mi primer compromiso</Button></Card>:active.map(h=><Card key={h.id}><h2>{h.title}</h2><p className="a-muted">{h.frequency==='weekly'?`${weekCount(h,date)} de ${h.target} días esta semana`:'Cada día'}{h.frequency==='weekly'&&weekCount(h,date)>=h.target?' · Meta registrada':''}</p>{h.anchor&&<p>{h.anchor}</p>}<div className="a-mark"><Button soft={h.checks[date]!=='done'} onClick={()=>mark(h,'done')}><Check size={18}/>Lo viví</Button><Button soft onClick={()=>mark(h,'missed')}>Me costó</Button></div>{h.checks[date]&&<p className="a-small">{shortDate(date)}: {h.checks[date]==='done'?'Lo viví':h.checks[date]==='missed'?'Me costó':'No aplicaba'}</p>}<Help title="Nota y opciones"><label>Nota de este día<textarea rows={2} value={h.notes[date]||''} readOnly placeholder="Todavía no hay una nota"/></label><Button soft onClick={()=>setEditNote({id:h.id,date,text:h.notes[date]||''})}>Anotar qué me ayudó o me costó</Button>{h.minimum&&<p>Mi versión mínima: {h.minimum}</p>}<div className="a-actions"><button className="a-link" onClick={()=>mark(h,'skip')}>No aplicaba</button><button className="a-link" onClick={()=>mark(h,'')}>Quitar registro</button><button className="a-link" onClick={()=>setEditHabit({...h})}>Editar compromiso</button></div></Help></Card>)}<button className="a-link" onClick={()=>setEditHabit(newHabit())}><Plus size={17}/>Añadir un compromiso</button><Help title="¿Cómo se cuenta una meta semanal?"><p>Para tres días por semana, registrá los días en que lo hiciste. Podés registrar más de tres; los días adicionales quedan visibles y no compensan otra semana. La semana va de lunes a domingo.</p><p>Un día vacío significa sin registro. No se marca automáticamente como incumplimiento.</p></Help></>}
    {view==='month'&&<><label>Mes que quiero preparar<input type="month" max="2026-10" value={month} onChange={e=>{setMonth(e.target.value||'2026-09');setEditingMonth(null);}}/></label>{(()=>{const previous=shift(month+'-01',-1).slice(0,7);const rows=p.habits.flatMap(h=>Object.entries(h.notes).filter(([d])=>d.startsWith(previous)).map(([d,n])=>({d,n,title:h.title})));return <>
     <Card><span className="a-kicker">1 · MIRAR EL MES ANTERIOR · {previous}</span><h2>¿Qué aprendí?</h2><p>{p.purposes[previous]||'No guardaste un propósito para ese mes. Podés revisar lo vivido igualmente.'}</p>{p.habits.map(h=><div className="a-reviewrow" key={h.id}><strong>{h.title}</strong><p>{Object.entries(h.checks).filter(([d,v])=>d.startsWith(previous)&&v==='done').length} días registrados como vividos · {Object.entries(h.checks).filter(([d,v])=>d.startsWith(previous)&&v==='missed').length} días en que me costó</p></div>)}{rows.length>0&&<Help title="Leer mis notas del mes">{rows.map((r,i)=><p key={i}><strong>{r.title} · {shortDate(r.d)}</strong><br/>{r.n}</p>)}</Help>}{p.reviews[previous]&&<p className="a-quote">{p.reviews[previous]}</p>}{editingMonth==='review'?<form onSubmit={e=>{e.preventDefault();update({reviews:{...p.reviews,[previous]:review}});setEditingMonth(null);say('Revisión guardada en '+previous);}}><label>Qué ayudó, qué costó y qué quiero ajustar<textarea rows={4} value={review} onChange={e=>setReview(e.target.value)}/></label><div className="a-actions"><Button soft onClick={()=>setEditingMonth(null)}>Cerrar</Button><Button type="submit">Guardar revisión</Button></div></form>:<Button soft onClick={()=>{setReview(p.reviews[previous]||'');setEditingMonth('review');}}>Revisar {previous}</Button>}</Card>
     <Card><span className="a-kicker">2 · PREPARAR ESTE MES · {month}</span><h2>Mi propósito del mes</h2><p>{p.purposes[month]||'Un aspecto concreto que querés cultivar. Podés elegirlo ahora o volver después.'}</p>{editingMonth==='purpose'?<form onSubmit={e=>{e.preventDefault();update({purposes:{...p.purposes,[month]:purpose}});setEditingMonth(null);say('Propósito guardado para '+month);}}><label>¿Qué quiero cuidar este mes?<textarea rows={3} value={purpose} onChange={e=>setPurpose(e.target.value)} placeholder="Por ejemplo: escuchar con calma al llegar a casa"/></label><Help><p>Leé lo que aprendiste el mes anterior. Elegí un aspecto realista y expresalo con tus palabras. No necesitás añadir varios compromisos.</p></Help><div className="a-actions"><Button soft onClick={()=>setEditingMonth(null)}>Cerrar</Button><Button type="submit">Guardar propósito</Button></div></form>:<Button onClick={()=>{setPurpose(p.purposes[month]||'');setEditingMonth('purpose');}}>{p.purposes[month]?'Ajustar propósito':'Elegir propósito'}</Button>}</Card></>;})()}</>}
    {view==='history'&&<><h2>Mi cumplimiento por compromiso</h2><p className="a-muted">Ejemplo de la semana del 7 al 13 de septiembre. El período todavía está en curso.</p>{p.habits.map(h=>{const n=weekCount(h,TODAY),target=h.frequency==='weekly'?h.target:7;return <Card key={h.id}><h3>{h.title}</h3><p className="a-big">{n} / {target}<span>días registrados</span></p><progress max={target} value={Math.min(n,target)} aria-label={'Progreso registrado: '+h.title}/><p>{n>=target?'Meta registrada':`Quedan ${Math.max(0,target-n)} días de la meta por registrar`}</p>{n>target&&<p>{n-target} {n-target===1?'día adicional, conservado':'días adicionales, conservados'} en tu historial.</p>}<p className="a-small">La falta de registro no prueba que no lo hiciste.</p><Button soft onClick={()=>setEditHabit({...h})}>Ajustar compromiso</Button></Card>})}<Help title="Mis revisiones anteriores">{Object.entries(p.reviews).length?Object.entries(p.reviews).map(([m,r])=><p key={m}><strong>{m}</strong><br/>{r}</p>):<p>Tus revisiones aparecerán aquí cuando las guardés.</p>}</Help></>}
   </>}
   {screen==='rs'&&<>{header('LAS CUATRO RS','Cuidar nuestro encuentro.',linked?`Espacio compartido con ${other.name}.`:'Podés empezar preparando una idea personal.')}
    {!linked?<><Card><h2>{couple.status==='pending'?'La vinculación está pendiente':'Vincularme con mi pareja'}</h2><p>Ambos deben aceptar antes de abrir el espacio compartido. Tu horario y tus reflexiones seguirán privados.</p><Button onClick={()=>go('pair')}>{couple.status==='pending'?'Ver invitación':'Vincularnos'}</Button></Card><Card><h2>Una idea para nuestro encuentro</h2><p className="a-scope"><LockKeyhole size={16}/>Solo vos, incluso después de vincularte</p><form onSubmit={e=>{e.preventDefault();update({notes:{...p.notes,rs:rNote}});say('Idea personal guardada. Podés encontrarla en las cuatro Rs.');}}><label>¿Qué me gustaría proponer?<textarea rows={3} value={rNote} onChange={e=>setRNote(e.target.value)} placeholder="Una oración juntos, una conversación, una salida…"/></label><Button type="submit">Guardar mi idea</Button></form>{p.notes.rs&&<p className="a-quote">{p.notes.rs}</p>}</Card></>:<>
     {p.notes.rs&&<Help title="Mi idea personal guardada"><p className="a-scope"><LockKeyhole size={16}/>Solo vos</p><p>{p.notes.rs}</p></Help>}
     {selectedR?rEditor():<div className="a-rlist">{R_TYPES.map(r=><button className="a-choice" key={r.id} onClick={()=>{setSelectedR(r.id);setRDate(TODAY);setRNote('');setRDone(false);}}><Heart size={22}/><span><strong>{r.title}<em>{r.rhythm}</em></strong><span>{r.description}</span></span><ChevronRight size={20}/></button>)}</div>}
     <Help title="Nuestro ideal matrimonial"><p>{couple.ideal||'Pueden vivir las cuatro Rs aunque todavía no tengan un ideal matrimonial.'}</p>{couple.ideal&&<p>{couple.confirmed.every(Boolean)?'Confirmado por ambos':'En espera de la confirmación de ambos'}</p>}<Button soft onClick={()=>openIdeal(true)}>{couple.ideal?'Abrir nuestro ideal':'Explorar cuando queramos'}</Button></Help>
     {Object.entries(couple.events).length>0&&<Help title="Nuestros encuentros guardados">{Object.entries(couple.events).map(([key,v])=><p key={key}><strong>{R_TYPES.find(r=>key.startsWith(r.id+':'))?.title} · {shortDate(v.date)}</strong><br/>{v.done?'Vivido':'Preparado'}{v.note&&<><br/>{v.note}</>}</p>)}</Help>}
    </>}
   </>}
   {screen==='profile'&&<>{header('MI ESPACIO','A mi manera.')}<Card><div className="a-titleline"><Symbol id={p.symbol} size={30}/><h2>{p.name||'Mi perfil'}</h2></div><label>Mi nombre<input maxLength={60} defaultValue={p.name} onBlur={e=>update({name:e.target.value.trim()||p.name})}/></label><Help title="Elegir mi símbolo"><div className="a-symbols">{symbols.map(([id,label])=><button key={id} aria-label={label} aria-pressed={p.symbol===id} onClick={()=>update({symbol:id})}><Symbol id={id}/><span>{label}</span></button>)}</div></Help><Button soft onClick={()=>openIdeal()}>Mi ideal personal</Button></Card>
    <Card><h2>{linked?'Mi espacio en pareja':'Uso individual o en pareja'}</h2><p>{linked?`Vinculado con ${other.name}.`:'Podés vincularte cuando quieras. Tus registros personales se conservan.'}</p><Button soft onClick={()=>go('pair')}>{linked?'Vinculación y privacidad':couple.status==='pending'?'Ver invitación pendiente':'Vincularme con mi pareja'}</Button></Card>
    <Card><h2>Compromisos en pausa</h2>{p.habits.some(h=>!h.active)?p.habits.filter(h=>!h.active).map(h=><div key={h.id}><p>{h.title}</p><Button soft onClick={()=>setEditHabit({...h,active:true})}>Ajustar y retomar</Button></div>):<p>No tenés compromisos en pausa.</p>}</Card>
    {archives.length>0&&<Help title="Archivo compartido"><p>Solo lectura. Estos registros no se trasladan a una nueva vinculación.</p>{archives.map((a,i)=><div key={i}><h3>Vinculación anterior {i+1}</h3><p>{a.ideal||'Sin ideal matrimonial guardado.'}</p>{Object.entries(a.events).map(([k,e])=><p key={k}>{shortDate(e.date)} · {e.note||'Encuentro guardado'}</p>)}</div>)}</Help>}<button className="a-choice" onClick={()=>go('news')}><BookOpen/><span><strong>Novedades</strong><span>Qué cambió y dónde encontrarlo.</span></span><ChevronRight/></button><button className="a-link" onClick={()=>go('welcome')}>Cambiar mi espacio principal</button>
   </>}
   {(screen==='ideal'||screen==='pairIdeal')&&<>{header(screen==='pairIdeal'?'NUESTRO IDEAL MATRIMONIAL':'MI IDEAL PERSONAL','Con nuestras propias palabras.'.replace('nuestras',screen==='ideal'?'mis':'nuestras'))}<form onSubmit={e=>{e.preventDefault();if(screen==='pairIdeal'){const changed=ideal!==couple.ideal||idealStatus!==couple.idealStatus;setCouple({...couple,ideal,idealStatus,ideas,confirmed:changed?[who===0,who===1]:couple.confirmed});say('Guardado. Cada persona confirma por separado la frase que los representa.');}else{update({ideal,idealStatus,idealNotes:ideas});say('Tu ideal y tus notas quedaron guardados.');}}}>{idealFields(screen==='pairIdeal')}<Button type="submit">Guardar y retomar después</Button></form>{screen==='pairIdeal'&&couple.ideal&&<Card><p>{couple.ideal}</p><p>{couple.confirmed.every(Boolean)?'Ambos confirmaron esta frase.':couple.confirmed[who]?'Tu confirmación está registrada. Falta la de tu pareja.':'Tu pareja propone esta frase. Leela antes de confirmar.'}</p>{!couple.confirmed[who]&&<Button onClick={()=>{const confirmed=[...couple.confirmed];confirmed[who]=true;setCouple({...couple,confirmed});}}>Esta frase también me representa</Button>}</Card>}<button className="a-link" onClick={()=>go(screen==='pairIdeal'?'rs':'profile')}>Volver a mi espacio</button></>}
   {screen==='pair'&&<>{header('VINCULACIÓN Y PRIVACIDAD',linked?'Nuestro espacio compartido.':'Vincularme con mi pareja.')}
    {couple.status==='none'&&<Card><p>Cada persona usa su propia cuenta. Tu pareja debe aceptar la invitación; tus registros personales se conservan y siguen privados.</p><form onSubmit={e=>{e.preventDefault();if(email.trim().toLowerCase()===`${p.name.toLowerCase()}@example.test`){say('Elegí el correo de tu pareja.');return;}setCouple({...couple,status:'pending',email:email.trim(),sender:who});say('Invitación preparada en esta prueba. No se envió ningún correo.');}}><label>Correo de mi pareja<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="pareja@correo.com"/></label><p className="a-small">Si todavía no tiene cuenta, primero necesitará su acceso al piloto. La vinculación quedará pendiente hasta que entre y acepte.</p><Button type="submit">Invitar y aceptar la vinculación</Button></form></Card>}
    {couple.status==='pending'&&(couple.sender===who?<Card><h2>Esperando la aceptación de tu pareja</h2><p>{couple.email}</p><p>Podés seguir usando tu espacio mientras tanto. No se ha compartido información personal.</p><Button onClick={()=>go('home')}>Continuar con mi espacio</Button><button className="a-link" onClick={()=>setConfirm('cancelInvite')}>Cancelar invitación</button></Card>:<Card><h2>{other.name||'Tu pareja'} quiere vincularse con vos</h2><p>Al aceptar, podrán usar las cuatro Rs y trabajar su ideal matrimonial. Cada uno decide por separado si comparte su horario o sus reflexiones.</p><Button onClick={()=>{setCouple({...couple,status:'linked'});setPeople(people.map(x=>({...x,shareSchedule:false,shareNotes:false})) as [Person,Person]);say('Vinculación aceptada. Los espacios personales siguen privados.');}}>Aceptar vinculación</Button><Button soft onClick={()=>{setCouple(pair());say('Invitación rechazada. Tu espacio personal se conserva.');}}>Rechazar invitación</Button></Card>)}
    {linked&&<><Card><h2>Vinculado con {other.name}</h2><p>Las cuatro Rs y el ideal matrimonial se trabajan juntos. Tu espacio personal conserva sus propios permisos.</p><label className="a-checkbox"><input type="checkbox" checked={p.shareSchedule} onChange={e=>update({shareSchedule:e.target.checked})}/>Compartir mi horario e historial</label><label className="a-checkbox"><input type="checkbox" checked={p.shareNotes} onChange={e=>update({shareNotes:e.target.checked})}/>Compartir mis reflexiones y revisiones</label><p className="a-small">Al activar un permiso, incluís el historial correspondiente. Al apagarlo, se bloquean nuevas consultas; no se pueden retirar copias ya leídas.</p><Button onClick={()=>go('rs')}>Ir a nuestro espacio</Button></Card><Card><h2>Lo que {other.name} comparte conmigo</h2>{!other.shareSchedule&&!other.shareNotes?<p>Su espacio personal está privado.</p>:<>{other.shareSchedule&&other.habits.filter(h=>h.active).map(h=><p key={h.id}>{h.title} · {weekCount(h,TODAY)} días registrados esta semana</p>)}{other.shareNotes&&Object.entries(other.reviews).map(([m,r])=><p key={m}>{m}: {r}</p>)}</>}</Card><button className="a-link" onClick={()=>setConfirm('unlink')}>Desvincularme</button></>}
   </>}
   {screen==='news'&&<>{header('NOVEDADES','Lo nuevo, a tu alcance.')}<Card><p className="a-eyebrow">PROPUESTA EN REVISIÓN</p><h2>Un comienzo a tu medida</h2><p>Ahora podés elegir qué espacio te sirve más y retomarlo desde Inicio.</p><Button soft onClick={()=>go('welcome')}>Elegir mi espacio principal</Button></Card><Card><h2>Propósito y revisión, en un solo lugar</h2><p>Encontralos en Horario → Mi mes. Revisá el mes anterior y prepará el siguiente sin volver a escribir tus registros diarios.</p><Button soft onClick={()=>{update({seen:true});go('schedule');setView('month');}}>Ver mi mes</Button></Card><Card><h2>¿Dónde quedó lo que usaba?</h2><dl><dt>Hoy</dt><dd>Horario → Mi día</dd><dt>Camino</dt><dd>Horario → Mi mes e Historial; memoria de pareja en Las cuatro Rs</dd><dt>Ajustes</dt><dd>Mi espacio</dd></dl><p>Las guías y novedades quedan disponibles para consultarlas cuando quieras.</p></Card><Button onClick={()=>{update({seen:true});go('home');}}>Entendido, volver a Inicio</Button></>}
   {screen==='help'&&<>{header('AYUDA','Una guía donde la necesitás.')}<Help title="¿Por dónde empiezo?"><p>Elegí lo que te representa mayor beneficio hoy. Con dejar listo ese espacio basta para empezar.</p><Button soft onClick={()=>go('welcome')}>Elegir mi comienzo</Button></Help><Help title="Horario espiritual y cuatro Rs"><p>El horario espiritual reúne compromisos personales. Las cuatro Rs son encuentros para cuidar la vida matrimonial. Podés usar ambos, empezando por el que más te ayude.</p></Help><Help title="Propósito y revisión mensual"><p>Al inicio del mes, revisá el anterior y elegí tu propósito nuevo. En Horario → Mi mes verás tus registros y notas para acompañar esa reflexión.</p><Button soft onClick={()=>{go('schedule');setView('month');}}>Ir a mi mes</Button></Help><Help title="¿Tengo que tener un ideal?"><p>No. Podés usar tu espacio y discernirlo gradualmente. Las preguntas son un apoyo; buscá acompañamiento en el Movimiento.</p></Help><Help title="¿Quién ve mi información?"><p>Tu espacio personal es privado. Vincularse requiere aceptación de ambos y no activa permisos de compartir. Cada persona controla su horario y sus reflexiones.</p><p>El administrador del piloto ve actividad de uso, sin contenido espiritual. La base actual no tiene cifrado de extremo a extremo.</p></Help><Button soft onClick={()=>go(p.focus?'home':'welcome')}>Volver</Button></>}
  </main>
  {!isFirst&&<nav className="a-nav" aria-label="Navegación principal">{[['home','Inicio',Home],['schedule','Horario',CalendarDays],['rs','Las 4 Rs',Heart],['profile','Mi espacio',UserRound]].map(([s,t,Icon]:any)=><button key={s} aria-current={mainTab===s?'page':undefined} onClick={()=>go(s)}><Icon size={21}/><span>{t}</span></button>)}</nav>}
  </div>
  {modal&&<div className="a-overlay"><section className="a-modal" role="dialog" aria-modal="true" aria-label={confirm?'Confirmar acción':editNote?'Nota del compromiso':'Mi compromiso'}>
   {editHabit&&screen!=='setup'&&<><h2>Mi compromiso</h2><form onSubmit={e=>{e.preventDefault();if(editHabit.title.trim())saveHabit(editHabit);}}>{habitFields(editHabit,setEditHabit)}<label className="a-checkbox"><input type="checkbox" checked={editHabit.active} onChange={e=>setEditHabit({...editHabit,active:e.target.checked})}/>Incluir en mi horario</label><p className="a-small">Al pausarlo, se conserva su historial.</p><div className="a-actions"><Button soft onClick={()=>setEditHabit(null)}>Cancelar</Button><Button type="submit">Guardar compromiso</Button></div></form></>}
   {editNote&&<><h2>¿Qué me ayudó o me costó?</h2><form onSubmit={e=>{e.preventDefault();update({habits:p.habits.map(h=>h.id===editNote.id?{...h,notes:{...h.notes,[editNote.date]:editNote.text}}:h)});setEditNote(null);say('Nota guardada. La encontrarás en tu revisión mensual.');}}><label>Mi nota del {shortDate(editNote.date)}<textarea rows={4} value={editNote.text} onChange={e=>setEditNote({...editNote,text:e.target.value})}/></label><div className="a-actions"><Button soft onClick={()=>setEditNote(null)}>Cancelar</Button><Button type="submit">Guardar nota</Button></div></form></>}
   {confirm&&<><h2>{confirm==='unlink'?'¿Desvincularse?':'¿Cancelar la invitación?'}</h2><p>{confirm==='unlink'?'Ambos conservan sus espacios personales. El historial compartido queda archivado y accesible para ambos; no se trasladará a una pareja futura. Se desactivan los permisos personales.':'El espacio personal de ambos se conserva. La otra persona ya no podrá aceptar esta invitación.'}</p><div className="a-actions"><Button soft onClick={()=>setConfirm(null)}>Volver</Button><Button onClick={()=>{if(confirm==='unlink')setArchives([...archives,structuredClone(couple)]);setCouple(pair());setPeople(people.map(x=>({...x,shareSchedule:false,shareNotes:false})) as [Person,Person]);setConfirm(null);say(confirm==='unlink'?'Desvinculación realizada en la prueba. El historial compartido está en Mi espacio → Archivo compartido.':'Invitación cancelada.');}}>Confirmar</Button></div></>}
  </section></div>}
 </div>;
}
createRoot(document.getElementById('alianza-journey-root')!).render(<App/>);
